export type Plan = {
  id: string;
  name: string;
  min: number;
  max: string;
  profit: string;
  duration: string;
  durationDays: number;
  color: string;
  dailyPct: number;
};

export const PLANS: Plan[] = [
  {
    id: "gns",
    name: "GNS PLAN",
    min: 4000,
    max: "10,000 BDX",
    profit: "1.90% ROI",
    duration: "1 Month",
    durationDays: 30,
    color: "#2AF5D4",
    dailyPct: 1.9 / 30,
  },
  {
    id: "build",
    name: "BUILD UP PLAN",
    min: 11000,
    max: "16,000 BDX",
    profit: "2.51% ROI",
    duration: "2 Months",
    durationDays: 60,
    color: "#5EE9FF",
    dailyPct: 2.51 / 60,
  },
  {
    id: "follow",
    name: "FOLLOW UP PLAN",
    min: 17000,
    max: "30,000 BDX",
    profit: "3.92% ROI",
    duration: "2 Months",
    durationDays: 60,
    color: "#A78BFA",
    dailyPct: 3.92 / 60,
  },
  {
    id: "apex",
    name: "APEX PLAN",
    min: 40000,
    max: "80,000 BDX",
    profit: "8.56% ROI",
    duration: "1 Year",
    durationDays: 365,
    color: "#FBBF24",
    dailyPct: 8.56 / 365,
  },
  {
    id: "edifex",
    name: "EDIFEX PLAN",
    min: 90000,
    max: "150,000 BDX",
    profit: "13.43% ROI",
    duration: "2 Years",
    durationDays: 730,
    color: "#FB7185",
    dailyPct: 13.43 / 730,
  },
  {
    id: "dixon",
    name: "DIXON PLAN",
    min: 160000,
    max: "220,000 BDX",
    profit: "15.43% ROI",
    duration: "2 Years",
    durationDays: 730,
    color: "#2AF5D4",
    dailyPct: 15.43 / 730,
  },
  {
    id: "falcon",
    name: "FALCON PLAN",
    min: 220000,
    max: "1,000,000 BDX",
    profit: "23.78% ROI",
    duration: "5 Years",
    durationDays: 1825,
    color: "#FFFFFF",
    dailyPct: 23.78 / 1825,
  },
];

/** Numeric cap from a plan max label, or null when unlimited. */
export function planCeiling(plan: Plan): number | null {
  if (/unlimited/i.test(plan.max)) return null;
  const n = Number(String(plan.max).replace(/[^0-9.]/g, ""));
  return Number.isFinite(n) && n > 0 ? n : null;
}

export function projectedReturn(amount: number, plan: Plan) {
  const profit = amount * (plan.dailyPct / 100) * plan.durationDays;
  return { profit, total: amount + profit };
}

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "DR Congo",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const DEPOSIT_METHODS = {
  BELDEX: {
    id: "BELDEX" as const,
    title: "BELDEX",
    address:
      "bxdRzpW3nTXY3w76CQHHbMCg8TE9rrNdT1maW2PJYmuqS6YLCf16hDaZFcZ226m3SoLaFoSwEgsTA8ET85EdqFfj2nThkg4y3",
    qr: "/deposits/beldex.jpg",
  },
  BTC: {
    id: "BTC" as const,
    title: "Bitcoin",
    address: "bc1qzlq3r8e39pwl8mv3vthdxr7nnxlrq92gvs3p0m",
    qr: "/deposits/bitcoin.jpg",
  },
  ETH: {
    id: "ETH" as const,
    title: "Ethereum",
    address: "0x38f34475671efC1f8084428448803C6f3aeF8dA7",
    qr: "/deposits/ethereum.jpg",
  },
};

export const DEPOSIT_ADDRESS = DEPOSIT_METHODS.BELDEX.address;

export const TRENDING = [
  { name: "Beldex", sym: "BDXUSD", icon: "B", live: true },
  { name: "Bitcoin", sym: "BTC", icon: "₿", live: false },
  { name: "Ethereum", sym: "ETH", icon: "Ξ", live: false },
  { name: "Solana", sym: "SOL", icon: "◎", live: false },
] as const;

export const WITHDRAW_METHODS = [
  { id: "BTC", label: "Bitcoin" },
  { id: "ETH", label: "Ethereum" },
  { id: "BELDEX", label: "Beldex" },
] as const;

export const FAQ = [
  {
    q: "Is this a live brokerage?",
    a: "No. GLOBAL BELDEX here is an educational demo with live Beldex charts from TradingView. Balances, deposits and plans are simulated in your browser.",
  },
  {
    q: "What is the minimum deposit?",
    a: "The demo uses a $300 minimum to match the original product flow. Funds never leave your device.",
  },
  {
    q: "How do investment plans work?",
    a: "Each plan locks a simulated amount for a fixed duration and accrues the listed daily profit. When the term ends, principal plus profit return to your available balance.",
  },
  {
    q: "Where does market data come from?",
    a: "Ticker, overview and candlestick widgets are official TradingView embeds for CRYPTO:BDXUSD and major pairs.",
  },
  {
    q: "Can I refer friends?",
    a: "Yes — every account gets a referral link. In this demo, referral bonuses are simulated when you copy and share your link.",
  },
];