/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDepositRouteImport } from './routes/app/deposit'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppMarketsRouteImport } from './routes/app/markets'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPlansRouteImport } from './routes/app/plans'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppReferralsRouteImport } from './routes/app/referrals'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSupportRouteImport } from './routes/app/support'
import { Route as AppSwapRouteImport } from './routes/app/swap'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositRoute = AppDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSwapRoute = AppSwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/history': typeof AppHistoryRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/swap': typeof AppSwapRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/forgot': typeof ForgotRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/history': typeof AppHistoryRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/swap': typeof AppSwapRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/deposit': typeof AppDepositRoute
  '/app/history': typeof AppHistoryRoute
  '/app/markets': typeof AppMarketsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referrals': typeof AppReferralsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/swap': typeof AppSwapRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot'
    | '/legal'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/login'
    | '/app/admin'
    | '/app/deposit'
    | '/app/history'
    | '/app/markets'
    | '/app/notifications'
    | '/app/plans'
    | '/app/profile'
    | '/app/referrals'
    | '/app/settings'
    | '/app/support'
    | '/app/swap'
    | '/app/withdraw'
    | '/auth/confirm'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/app/admin'
    | '/forgot'
    | '/legal'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/login'
    | '/app/deposit'
    | '/app/history'
    | '/app/markets'
    | '/app/notifications'
    | '/app/plans'
    | '/app/profile'
    | '/app/referrals'
    | '/app/settings'
    | '/app/support'
    | '/app/swap'
    | '/app/withdraw'
    | '/auth/confirm'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot'
    | '/legal'
    | '/login'
    | '/register'
    | '/admin/login'
    | '/app/deposit'
    | '/app/history'
    | '/app/markets'
    | '/app/notifications'
    | '/app/plans'
    | '/app/profile'
    | '/app/referrals'
    | '/app/settings'
    | '/app/support'
    | '/app/swap'
    | '/app/withdraw'
    | '/auth/confirm'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  ForgotRoute: typeof ForgotRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deposit': {
      id: '/app/deposit'
      path: '/deposit'
      fullPath: '/app/deposit'
      preLoaderRoute: typeof AppDepositRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/markets': {
      id: '/app/markets'
      path: '/markets'
      fullPath: '/app/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referrals': {
      id: '/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/swap': {
      id: '/app/swap'
      path: '/swap'
      fullPath: '/app/swap'
      preLoaderRoute: typeof AppSwapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

export interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDepositRoute: typeof AppDepositRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppSwapRoute: typeof AppSwapRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDepositRoute: AppDepositRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppSwapRoute: AppSwapRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthConfirmRoute: AuthConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
