import type { Lang } from "@/lib/platform/i18n";
import { pageFr, pageIt, pageNl, pagePt } from "@/lib/platform/page-copy";

type Dict = Record<string, unknown>;

function merge(base: Dict, over: Dict): Dict {
  const out: Dict = { ...base };
  for (const key of Object.keys(over)) {
    const next = over[key];
    const prev = base[key];
    if (next && typeof next === "object" && !Array.isArray(next) && prev && typeof prev === "object") {
      out[key] = merge(prev as Dict, next as Dict);
    } else {
      out[key] = next;
    }
  }
  return out;
}

const fr = {
  tag: "Plateforme d’investissement avancée",
  signIn: "Connexion",
  openAccount: "Ouvrir un compte",
  investNow: "Investir",
  explore: "Voir le tableau de bord",
  home: "Accueil",
  history: "Historique",
  deposit: "Dépôt",
  withdraw: "Retrait",
  menu: "Menu",
  dashboard: "Tableau de bord",
  markets: "Marchés",
  plans: "Plans",
  swap: "Échange",
  profile: "Profil",
  referrals: "Parrainages",
  notifications: "Notifications",
  settings: "Réglages",
  support: "Assistance",
  logout: "Déconnexion",
  available: "Solde disponible",
  locked: "Solde bloqué",
  welcome: "Bienvenue sur GLOBAL BELDEX",
  welcomeBody: "Votre tableau de bord est prêt. Marché BDXUSD en direct actif.",
  others: "Autres",
  transactions: "Transactions",
  liveMarket: "Marché en direct",
  mainMenu: "Menu principal",
  finance: "Finance",
  account: "Compte",
  ready: "Prêt à avancer ?",
  readyBody: "Commencez dès 300 $ · Marché BDXUSD en direct",
  startInvesting: "Commencer",
  plansTitle: "Plans d’investissement",
  historyTitle: "Historique des transactions",
  noTx: "Aucune transaction",
  noTxBody: "Votre historique {tab} apparaîtra ici",
  depositTitle: "Déposer des fonds",
  depositLead: "Ajoutez des fonds pour commencer · Marché BDXUSD en direct ci-dessous",
  amountUsd: "Montant (USD)",
  minHint: "Dépôt minimum 300 $ · Crédité en quelques secondes, même si vous quittez la page",
  payMethod: "Choisir un moyen de paiement",
  beldexInstant: "BELDEX instantané",
  beldexDetail: "Recommandé · 0 % de frais · BDXUSD en direct",
  continuePay: "Continuer vers le paiement",
  sendExactly: "Envoyez exactement",
  depositAddress: "Adresse de dépôt",
  addressCopied: "Adresse copiée",
  simAddress: "Cette adresse est simulée. Confirmer crédite le solde de démo — aucun transfert on-chain.",
  back: "Retour",
  sentIt: "Je l’ai envoyé",
  depositStarted: "Dépôt lancé — il sera crédité sous peu",
  withdrawTitle: "Retirer vos fonds",
  withdrawLead: "Retraits dans cette démo · Marché en direct ci-dessous",
  chooseMethod: "Choisir l’actif de retrait",
  destination: "Adresse de retrait",
  destPlaceholder: "Collez votre adresse de portefeuille",
  amount: "Montant",
  enterAmount: "Saisir le montant",
  max: "Max",
  withdrawNow: "Retirer",
  withdrawRequested: "Retrait demandé",
  secure: "Traitement sécurisé",
  secureBody: "Chiffrement 256 bits",
  fast: "Retraits rapides",
  fastBody: "Terminé en quelques secondes dans cette démo",
  referralTitle: "Parrainages",
  referralLead: "Invitez des amis et recevez 10 % de chaque dépôt qu’ils terminent.",
  referralEarned: "Bonus de parrainage gagné",
  yourLink: "Votre lien",
  copyLink: "Copier le lien",
  linkCopied: "Lien de parrainage copié",
  referralFine: "Partager le lien ne paie pas. Les 10 % arrivent quand quelqu’un s’inscrit avec votre nom et que son dépôt se termine.",
  loginTitle: "Bon retour",
  loginLead: "Connectez-vous pour continuer",
  emailOrUser: "E-mail ou nom d’utilisateur",
  password: "Mot de passe",
  codeLabel: "Code à 6 chiffres",
  remember: "Se souvenir de moi",
  forgot: "Mot de passe oublié ?",
  notMember: "Pas encore membre ?",
  signUp: "S’inscrire",
  welcomeBack: "Bon retour !",
  needCode: "Saisissez votre code à 6 chiffres",
  createTitle: "Créer un compte",
  createLead: "Commencez aujourd’hui",
  username: "Nom d’utilisateur",
  fullname: "Nom complet",
  email: "E-mail",
  phone: "Téléphone",
  country: "Pays",
  selectCountry: "Choisir un pays",
  referralOptional: "Nom d’utilisateur du parrain (facultatif)",
  repeatPassword: "Répéter le mot de passe",
  createBtn: "Créer le compte",
  haveAccount: "Vous avez déjà un compte ?",
  mismatch: "Les mots de passe ne correspondent pas",
  created: "Compte créé — bonus de 3 $ ajouté",
  checkEmailTitle: "Vérifiez votre e-mail",
  checkEmailBody: "Nous avons envoyé un lien de confirmation. Ouvrez-le dans ce navigateur pour terminer. Les soldes restent simulés sur cet appareil.",
  accept: "Créer un compte signifie que vous acceptez les notes Conditions, Confidentialité et Risque. Les soldes restent simulés sur cet appareil.",
  acceptLead: "Créer un compte signifie que vous acceptez les ",
  termsWord: "Conditions",
  privacyWord: "Confidentialité",
  acceptAnd: " et ",
  riskWord: "Risque",
  acceptTail: ". Les soldes restent simulés sur cet appareil.",
  shortPass: "Utilisez au moins 6 caractères",
  confirming: "Confirmation…",
  useAccountEmail: "Utilisez l’e-mail du compte",
  forgotTitle: "Mot de passe oublié",
  forgotLead: "Saisissez l’e-mail du compte. Nous enverrons un lien. Ouvrez-le dans ce navigateur, puis choisissez un nouveau mot de passe.",
  sendReset: "Continuer",
  setNew: "Choisir un nouveau mot de passe",
  newPassword: "Nouveau mot de passe",
  savePassword: "Enregistrer le mot de passe",
  savedIf: "Si ce compte est sur cet appareil, le nouveau mot de passe est enregistré. Connectez-vous pour voir l’avis.",
  minDepositLabel: "Dépôt min.",
  maxDepositLabel: "Dépôt max.",
  expectedProfit: "Profit attendu",
  duration: "Durée",
  days: "jours",
  unlimited: "Illimité",
  buyPlan: "Acheter le plan",
  openToInvest: "Ouvrir un compte",
  plansLead: "Disponible {amount} · Les plans bloquent les fonds pour la durée indiquée et ajoutent un profit quotidien dans cette démo.",
  lockAmount: "Montant à bloquer (USD)",
  close: "Fermer",
  confirm: "Confirmer",
  heldTerm: "Si conservé jusqu’au terme :",
  profitWord: "de profit",
  returned: "rendus",
  selected: "{name} sélectionné",
  activated: "{name} activé",
  swapTitle: "Échange",
  swapLead: "Convertissez le solde USD et BDX au cours Beldex en direct.",
  rate: "Cours",
  from: "De",
  to: "Vers",
  swapNow: "Échanger",
  swapped: "Échange effectué",
  usdAvail: "USD disponible {usd} · BDX {bdx}",
  profileTitle: "Profil",
  saveChanges: "Enregistrer",
  profileSaved: "Profil enregistré",
  updatePhoto: "Mettre à jour la photo",
  photoUpdated: "Photo de profil mise à jour",
  removePhoto: "Retirer la photo",
  photoTooBig: "Choisis une image plus petite",
  passwordBlock: "Mot de passe",
  passwordHint: "Changez le mot de passe enregistré sur cet appareil.",
  currentPassword: "Mot de passe actuel",
  updatePassword: "Mettre à jour le mot de passe",
  passwordUpdated: "Mot de passe mis à jour",
  settingsLead: "Compte, langue et sécurité.",
  openProfile: "Modifier le profil",
  security: "Sécurité",
  preferences: "Préférences",
  settingsLang: "Langue",
  twoFactor: "Double authentification",
  on: "Oui",
  off: "Non",
  twoOn: "Double authentification activée",
  twoOff: "Double authentification désactivée",
  session: "Session",
  sessionBody: "Uniquement sur cet appareil",
  marketData: "Données de marché",
  supportLead: "GLOBAL BELDEX est une démo éducative. Les graphiques en direct viennent de TradingView.",
  supportEmail: "E-mail d’assistance",
  supportPhone: "Mobile",
  supportAddress: "Adresse",
  messageDesk: "Écrire à l’assistance",
  subject: "Objet",
  message: "Message",
  send: "Envoyer",
  ticketLogged: "Ticket enregistré",
  noNotes: "Aucune notification",
  noNotesBody: "Les dépôts, plans et parrainages apparaissent ici.",
  recent: "Transactions récentes",
  viewAll: "Tout voir",
  referralCard: "Lien de parrainage",
  referralCardLead: "Invitez des amis et recevez 10 % de leurs dépôts",
  quick: "Actions rapides",
  hello: "Bonjour",
  totalProfit: "Profit total",
  bonus: "Bonus",
  referralBonus: "Bonus de parrainage",
  withdrawals: "Retraits",
  bdxWallet: "Portefeuille BDX",
  noPlans: "Aucun plan actif",
  noPlansBody: "Vous n’avez pas encore d’investissement actif",
  activePlans: "Plans actifs",
  accrued: "accumulé",
  marketOverview: "Aperçu du marché",
  sentiment: "Sentiment",
  fear: "Peur",
  greed: "Avidité",
  neutral: "Neutre",
  topMovers: "Plus fortes variations",
  trending: "Actifs tendance",
  how: "Comment ça marche",
  howTitle: "Trois étapes vers le tableau de bord",
  questions: "Questions",
  pending: "en attente",
  completed: "terminé",
  failed: "échoué",
  tx: { deposit: "Dépôt", withdraw: "Retrait", bonus: "Bonus", plan: "Plan", swap: "Échange", referral: "Parrainage" },
  err: {
    FILL: "Remplissez les champs requis",
    NO_ACCOUNT: "Aucun compte pour cet e-mail ou ce nom. Créez-en un.",
    BAD_PASSWORD: "Mot de passe incorrect",
    BAD_CODE: "Code incorrect",
    MIN_DEPOSIT: "Le dépôt minimum est de 300 $",
    NEED_METHOD: "Choisissez un actif de retrait",
    NEED_ADDRESS: "Saisissez une adresse de destination",
    NEED_AMOUNT: "Saisissez un montant",
    INSUFFICIENT: "Solde insuffisant",
    MIN_PLAN: "Le minimum pour {a} est {b} $",
    MAX_PLAN: "Le maximum pour {a} est {b} $",
    NEED_DEPOSIT: "Solde disponible insuffisant — déposez d’abord",
    SWAP_SAME: "Choisissez deux actifs différents",
    BAD_RATE: "Cours indisponible",
    INSUFFICIENT_USD: "Solde USD insuffisant",
    INSUFFICIENT_BDX: "Solde BDX insuffisant",
    NEED_TICKET: "Ajoutez un objet et un message",
    NEED_EMAIL: "Saisissez votre e-mail ou votre nom",
    SHORT_PASSWORD: "Utilisez au moins 4 caractères",
    BAD_CURRENT: "Le mot de passe actuel est incorrect",
    BAD_REF: "Ce nom de parrain est introuvable sur cet appareil",
    REF_SELF: "Vous ne pouvez pas utiliser votre propre parrainage",
    EMAIL_TAKEN: "E-mail déjà enregistré — connectez-vous",
    SIGN_IN: "Connectez-vous d’abord",
  },
  note: {
    depositInitTitle: "Dépôt lancé",
    depositInitBody: "Dépôt {method} de {amount} $ en cours.",
    depositDoneTitle: "Dépôt terminé",
    depositDoneBody: "{amount} $ est maintenant sur votre solde disponible.",
    withdrawReqTitle: "Retrait demandé",
    withdrawReqBody: "{amount} $ via {method} en cours.",
    withdrawDoneTitle: "Retrait terminé",
    withdrawDoneBody: "{amount} $ via {method} a été envoyé.",
    welcomeTitle: "Bonus de bienvenue crédité",
    welcomeBody: "Bonus de bienvenue de 3,00 $ ajouté à votre solde disponible.",
    passwordTitle: "Mot de passe mis à jour",
    passwordBody: "Votre mot de passe a été changé sur cet appareil.",
    twoOnTitle: "Double authentification activée",
    twoOnBody: "Votre code de démo est {code}. Saisissez-le à la prochaine connexion.",
    twoOffTitle: "Double authentification désactivée",
    twoOffBody: "La connexion ne demande plus de code.",
    planTitle: "{name} activé",
    planBody: "{amount} $ bloqués pour {duration}.",
    matureTitle: "Plan arrivé à terme",
    matureBody: "Capital rendu. {amount} $ d’intérêt de cette étape ont été ajoutés à votre solde.",
    dailyTitle: "Intérêt quotidien",
    dailyBody: "{amount} $ d’intérêt quotidien simulé ont été ajoutés à votre solde.",
    swapTitle: "Échange effectué",
    referralTitle: "Bonus de parrainage",
    referralBody: "{user} a déposé. Vous avez gagné {amount} $ (10 %).",
    supportTitle: "L’assistance a répondu",
    supportBody: "Nous avons noté « {subject} ». Cette démo garde les tickets sur votre appareil.",
  },
  page: pageFr,
};

const it = {
  tag: "Piattaforma di investimento avanzata",
  signIn: "Accedi",
  openAccount: "Apri un conto",
  investNow: "Investi",
  explore: "Apri la dashboard",
  home: "Home",
  history: "Cronologia",
  deposit: "Deposito",
  withdraw: "Prelievo",
  menu: "Menu",
  dashboard: "Dashboard",
  markets: "Mercati",
  plans: "Piani",
  swap: "Scambio",
  profile: "Profilo",
  referrals: "Inviti",
  notifications: "Avvisi",
  settings: "Impostazioni",
  support: "Assistenza",
  logout: "Esci",
  available: "Saldo disponibile",
  locked: "Saldo bloccato",
  welcome: "Benvenuto in GLOBAL BELDEX",
  welcomeBody: "La dashboard è pronta. Mercato BDXUSD live attivo.",
  others: "Altro",
  transactions: "Movimenti",
  liveMarket: "Mercato live",
  mainMenu: "Menu principale",
  finance: "Finanza",
  account: "Account",
  ready: "Pronto a iniziare?",
  readyBody: "Parti da 300 $ · Mercato BDXUSD live",
  startInvesting: "Inizia",
  plansTitle: "Piani di investimento",
  historyTitle: "Cronologia movimenti",
  noTx: "Nessun movimento",
  noTxBody: "La cronologia {tab} apparirà qui",
  depositTitle: "Deposita fondi",
  depositLead: "Aggiungi fondi per iniziare · Mercato BDXUSD live sotto",
  amountUsd: "Importo (USD)",
  minHint: "Deposito minimo 300 $ · Accreditato in pochi secondi, anche se lasci la pagina",
  payMethod: "Scegli il metodo di pagamento",
  beldexInstant: "BELDEX istantaneo",
  beldexDetail: "Consigliato · commissione 0% · BDXUSD live",
  continuePay: "Continua al pagamento",
  sendExactly: "Invia esattamente",
  depositAddress: "Indirizzo di deposito",
  addressCopied: "Indirizzo copiato",
  simAddress: "Questo indirizzo è simulato. La conferma accredita il saldo demo — nessun invio on-chain.",
  back: "Indietro",
  sentIt: "L’ho inviato",
  depositStarted: "Deposito avviato — sarà accreditato a breve",
  withdrawTitle: "Preleva i fondi",
  withdrawLead: "Prelievi in questa demo · Mercato live sotto",
  chooseMethod: "Scegli l’asset di prelievo",
  destination: "Indirizzo di prelievo",
  destPlaceholder: "Incolla l’indirizzo del wallet",
  amount: "Importo",
  enterAmount: "Inserisci l’importo",
  max: "Max",
  withdrawNow: "Preleva ora",
  withdrawRequested: "Prelievo richiesto",
  secure: "Elaborazione sicura",
  secureBody: "Cifratura a 256 bit",
  fast: "Prelievi rapidi",
  fastBody: "In questa demo si completano in pochi secondi",
  referralTitle: "Inviti",
  referralLead: "Invita amici e ricevi il 10% di ogni deposito che completano.",
  referralEarned: "Bonus inviti guadagnato",
  yourLink: "Il tuo link",
  copyLink: "Copia link",
  linkCopied: "Link di invito copiato",
  referralFine: "Condividere il link non paga. Il 10% arriva quando qualcuno si registra con il tuo nome utente e il deposito si completa.",
  loginTitle: "Bentornato",
  loginLead: "Accedi per continuare",
  emailOrUser: "Email o nome utente",
  password: "Password",
  codeLabel: "Codice a 6 cifre",
  remember: "Ricordami",
  forgot: "Password dimenticata?",
  notMember: "Non sei ancora iscritto?",
  signUp: "Registrati",
  welcomeBack: "Bentornato!",
  needCode: "Inserisci il codice a 6 cifre",
  createTitle: "Crea account",
  createLead: "Inizia oggi",
  username: "Nome utente",
  fullname: "Nome completo",
  email: "Email",
  phone: "Telefono",
  country: "Paese",
  selectCountry: "Scegli il paese",
  referralOptional: "Nome utente di chi ti invita (facoltativo)",
  repeatPassword: "Ripeti la password",
  createBtn: "Crea account",
  haveAccount: "Hai già un account?",
  mismatch: "Le password non coincidono",
  created: "Account creato — bonus di 3 $ aggiunto",
  checkEmailTitle: "Controlla l’email",
  checkEmailBody: "Abbiamo inviato un link di conferma. Aprilo in questo browser per finire. I saldi restano simulati su questo dispositivo.",
  accept: "Creare un account significa accettare le note Termini, Privacy e Rischio. I saldi restano simulati su questo dispositivo.",
  acceptLead: "Creare un account significa accettare le note ",
  termsWord: "Termini",
  privacyWord: "Privacy",
  acceptAnd: " e ",
  riskWord: "Rischio",
  acceptTail: ". I saldi restano simulati su questo dispositivo.",
  shortPass: "Usa almeno 6 caratteri",
  confirming: "Conferma in corso…",
  useAccountEmail: "Usa l’email dell’account",
  forgotTitle: "Password dimenticata",
  forgotLead: "Inserisci l’email dell’account. Invieremo un link. Aprilo in questo browser e scegli una nuova password.",
  sendReset: "Continua",
  setNew: "Imposta una nuova password",
  newPassword: "Nuova password",
  savePassword: "Salva password",
  savedIf: "Se quell’account è su questo dispositivo, la nuova password è salvata. Accedi per vedere l’avviso.",
  minDepositLabel: "Deposito min.",
  maxDepositLabel: "Deposito max.",
  expectedProfit: "Profitto atteso",
  duration: "Durata",
  days: "giorni",
  unlimited: "Illimitato",
  buyPlan: "Acquista piano",
  openToInvest: "Apri un account",
  plansLead: "Disponibile {amount} · I piani bloccano i fondi per il periodo indicato e accumulano profitto giornaliero in questa demo.",
  lockAmount: "Importo da bloccare (USD)",
  close: "Chiudi",
  confirm: "Conferma",
  heldTerm: "Se tenuto fino a scadenza:",
  profitWord: "di profitto",
  returned: "restituiti",
  selected: "{name} selezionato",
  activated: "{name} attivato",
  swapTitle: "Scambio",
  swapLead: "Converti saldo USD e BDX al prezzo live di Beldex.",
  rate: "Tasso",
  from: "Da",
  to: "A",
  swapNow: "Scambia",
  swapped: "Scambio eseguito",
  usdAvail: "USD disponibile {usd} · BDX {bdx}",
  profileTitle: "Profilo",
  saveChanges: "Salva modifiche",
  profileSaved: "Profilo salvato",
  updatePhoto: "Aggiorna foto",
  photoUpdated: "Foto profilo aggiornata",
  removePhoto: "Rimuovi foto",
  photoTooBig: "Scegli un'immagine più piccola",
  passwordBlock: "Password",
  passwordHint: "Cambia la password salvata su questo dispositivo.",
  currentPassword: "Password attuale",
  updatePassword: "Aggiorna password",
  passwordUpdated: "Password aggiornata",
  settingsLead: "Account, lingua e sicurezza.",
  openProfile: "Modifica profilo",
  security: "Sicurezza",
  preferences: "Preferenze",
  settingsLang: "Lingua",
  twoFactor: "Autenticazione a due fattori",
  on: "Sì",
  off: "No",
  twoOn: "Due fattori attivo",
  twoOff: "Due fattori disattivo",
  session: "Sessione",
  sessionBody: "Solo su questo dispositivo",
  marketData: "Dati di mercato",
  supportLead: "GLOBAL BELDEX è una demo educativa. I grafici live arrivano da TradingView.",
  supportEmail: "Email di assistenza",
  supportPhone: "Cellulare",
  supportAddress: "Indirizzo",
  messageDesk: "Scrivi all’assistenza",
  subject: "Oggetto",
  message: "Messaggio",
  send: "Invia",
  ticketLogged: "Richiesta registrata",
  noNotes: "Nessun avviso",
  noNotesBody: "Depositi, piani e inviti compaiono qui.",
  recent: "Movimenti recenti",
  viewAll: "Vedi tutto",
  referralCard: "Link di invito",
  referralCardLead: "Invita amici e ricevi il 10% dei loro depositi",
  quick: "Azioni rapide",
  hello: "Ciao",
  totalProfit: "Profitto totale",
  bonus: "Bonus",
  referralBonus: "Bonus inviti",
  withdrawals: "Prelievi",
  bdxWallet: "Wallet BDX",
  noPlans: "Nessun piano attivo",
  noPlansBody: "Non hai ancora investimenti attivi",
  activePlans: "Piani attivi",
  accrued: "maturato",
  marketOverview: "Panoramica di mercato",
  sentiment: "Sentiment",
  fear: "Paura",
  greed: "Avidità",
  neutral: "Neutro",
  topMovers: "Più mossi",
  trending: "Asset di tendenza",
  how: "Come funziona",
  howTitle: "Tre passi fino alla dashboard",
  questions: "Domande",
  pending: "in attesa",
  completed: "completato",
  failed: "fallito",
  tx: { deposit: "Deposito", withdraw: "Prelievo", bonus: "Bonus", plan: "Piano", swap: "Scambio", referral: "Invito" },
  err: {
    FILL: "Compila i campi obbligatori",
    NO_ACCOUNT: "Nessun account per quell’email o nome utente. Creane uno.",
    BAD_PASSWORD: "Password errata",
    BAD_CODE: "Codice errato",
    MIN_DEPOSIT: "Il deposito minimo è 300 $",
    NEED_METHOD: "Scegli un asset di prelievo",
    NEED_ADDRESS: "Inserisci un indirizzo di destinazione",
    NEED_AMOUNT: "Inserisci un importo",
    INSUFFICIENT: "Saldo insufficiente",
    MIN_PLAN: "Il minimo per {a} è ${b}",
    MAX_PLAN: "Il massimo per {a} è ${b}",
    NEED_DEPOSIT: "Saldo disponibile insufficiente — deposita prima",
    SWAP_SAME: "Scegli due asset diversi",
    BAD_RATE: "Tasso non disponibile",
    INSUFFICIENT_USD: "Saldo USD insufficiente",
    INSUFFICIENT_BDX: "Saldo BDX insufficiente",
    NEED_TICKET: "Aggiungi oggetto e messaggio",
    NEED_EMAIL: "Inserisci email o nome utente",
    SHORT_PASSWORD: "Usa almeno 4 caratteri",
    BAD_CURRENT: "La password attuale non è corretta",
    BAD_REF: "Quel nome invito non è su questo dispositivo",
    REF_SELF: "Non puoi usare il tuo stesso invito",
    EMAIL_TAKEN: "Email già registrata — accedi",
    SIGN_IN: "Accedi prima",
  },
  note: {
    depositInitTitle: "Deposito avviato",
    depositInitBody: "Deposito {method} di ${amount} in elaborazione.",
    depositDoneTitle: "Deposito completato",
    depositDoneBody: "${amount} è ora nel saldo disponibile.",
    withdrawReqTitle: "Prelievo richiesto",
    withdrawReqBody: "${amount} tramite {method} in elaborazione.",
    withdrawDoneTitle: "Prelievo completato",
    withdrawDoneBody: "${amount} tramite {method} è stato inviato.",
    welcomeTitle: "Bonus di benvenuto accreditato",
    welcomeBody: "Bonus di benvenuto di $3.00 aggiunto al saldo disponibile.",
    passwordTitle: "Password aggiornata",
    passwordBody: "La password di accesso è stata cambiata su questo dispositivo.",
    twoOnTitle: "Due fattori attivo",
    twoOnBody: "Il tuo codice demo è {code}. Inseriscilo al prossimo accesso.",
    twoOffTitle: "Due fattori disattivo",
    twoOffBody: "L’accesso non chiede più un codice.",
    planTitle: "{name} attivato",
    planBody: "${amount} bloccati per {duration}.",
    matureTitle: "Piano scaduto",
    matureBody: "Capitale restituito. ${amount} di interesse di questo passaggio è stato aggiunto al saldo.",
    dailyTitle: "Interesse giornaliero",
    dailyBody: "${amount} di interesse giornaliero simulato è stato aggiunto al saldo.",
    swapTitle: "Scambio eseguito",
    referralTitle: "Bonus invito",
    referralBody: "{user} ha depositato. Hai guadagnato ${amount} (10%).",
    supportTitle: "L’assistenza ha risposto",
    supportBody: "Abbiamo registrato “{subject}”. Questa demo tiene i ticket sul dispositivo.",
  },
  page: pageIt,
};

const pt = {
  tag: "Plataforma de investimento avançada",
  signIn: "Entrar",
  openAccount: "Abrir conta",
  investNow: "Investir",
  explore: "Ver o painel",
  home: "Início",
  history: "Histórico",
  deposit: "Depósito",
  withdraw: "Saque",
  menu: "Menu",
  dashboard: "Painel",
  markets: "Mercados",
  plans: "Planos",
  swap: "Troca",
  profile: "Perfil",
  referrals: "Indicações",
  notifications: "Avisos",
  settings: "Ajustes",
  support: "Suporte",
  logout: "Sair",
  available: "Saldo disponível",
  locked: "Saldo bloqueado",
  welcome: "Bem-vindo à GLOBAL BELDEX",
  welcomeBody: "Seu painel está pronto. Mercado BDXUSD ao vivo ativo.",
  others: "Outros",
  transactions: "Movimentos",
  liveMarket: "Mercado ao vivo",
  mainMenu: "Menu principal",
  finance: "Finanças",
  account: "Conta",
  ready: "Pronto para começar?",
  readyBody: "Comece a partir de $300 · Mercado BDXUSD ao vivo",
  startInvesting: "Começar",
  plansTitle: "Planos de investimento",
  historyTitle: "Histórico de movimentos",
  noTx: "Sem movimentos",
  noTxBody: "Seu histórico de {tab} aparece aqui",
  depositTitle: "Depositar fundos",
  depositLead: "Adicione fundos para começar · Mercado BDXUSD ao vivo abaixo",
  amountUsd: "Valor (USD)",
  minHint: "Depósito mínimo $300 · Creditado em segundos, mesmo se você sair desta página",
  payMethod: "Escolha a forma de pagamento",
  beldexInstant: "BELDEX instantâneo",
  beldexDetail: "Recomendado · taxa 0% · BDXUSD ao vivo",
  continuePay: "Continuar para o pagamento",
  sendExactly: "Envie exatamente",
  depositAddress: "Endereço de depósito",
  addressCopied: "Endereço copiado",
  simAddress: "Este endereço é simulado. Confirmar credita o saldo da demo — não há envio na rede.",
  back: "Voltar",
  sentIt: "Já enviei",
  depositStarted: "Depósito iniciado — será creditado em breve",
  withdrawTitle: "Sacar seus fundos",
  withdrawLead: "Saques nesta demo · Mercado ao vivo abaixo",
  chooseMethod: "Escolha o ativo do saque",
  destination: "Endereço de saque",
  destPlaceholder: "Cole o endereço da carteira",
  amount: "Valor",
  enterAmount: "Digite o valor",
  max: "Máx",
  withdrawNow: "Sacar agora",
  withdrawRequested: "Saque solicitado",
  secure: "Processamento seguro",
  secureBody: "Criptografia de 256 bits",
  fast: "Saques rápidos",
  fastBody: "Nesta demo concluem em alguns segundos",
  referralTitle: "Indicações",
  referralLead: "Convide amigos e receba 10% de cada depósito que eles concluírem.",
  referralEarned: "Bônus de indicação recebido",
  yourLink: "Seu link",
  copyLink: "Copiar link",
  linkCopied: "Link de indicação copiado",
  referralFine: "Compartilhar o link não paga. Os 10% entram quando alguém se registra com seu usuário e o depósito se conclui.",
  loginTitle: "Bem-vindo de volta",
  loginLead: "Entre para continuar",
  emailOrUser: "E-mail ou usuário",
  password: "Senha",
  codeLabel: "Código de 6 dígitos",
  remember: "Lembrar de mim",
  forgot: "Esqueceu a senha?",
  notMember: "Ainda não tem conta?",
  signUp: "Criar conta",
  welcomeBack: "Bem-vindo de volta!",
  needCode: "Digite o código de 6 dígitos",
  createTitle: "Criar conta",
  createLead: "Comece hoje",
  username: "Usuário",
  fullname: "Nome completo",
  email: "E-mail",
  phone: "Telefone",
  country: "País",
  selectCountry: "Escolha o país",
  referralOptional: "Usuário de quem indicou (opcional)",
  repeatPassword: "Repita a senha",
  createBtn: "Criar conta",
  haveAccount: "Já tem uma conta?",
  mismatch: "As senhas não coincidem",
  created: "Conta criada — bônus de $3 adicionado",
  checkEmailTitle: "Confira seu e-mail",
  checkEmailBody: "Enviamos um link de confirmação. Abra neste navegador para terminar. Os saldos continuam simulados neste aparelho.",
  accept: "Criar uma conta significa aceitar as notas de Termos, Privacidade e Risco. Os saldos ficam simulados neste aparelho.",
  acceptLead: "Criar uma conta significa aceitar as notas de ",
  termsWord: "Termos",
  privacyWord: "Privacidade",
  acceptAnd: " e ",
  riskWord: "Risco",
  acceptTail: ". Os saldos ficam simulados neste aparelho.",
  shortPass: "Use pelo menos 6 caracteres",
  confirming: "Confirmando…",
  useAccountEmail: "Use o e-mail da conta",
  forgotTitle: "Esqueci a senha",
  forgotLead: "Digite o e-mail da conta. Enviaremos um link. Abra neste navegador e escolha uma senha nova.",
  sendReset: "Continuar",
  setNew: "Definir uma senha nova",
  newPassword: "Nova senha",
  savePassword: "Salvar senha",
  savedIf: "Se essa conta estiver neste aparelho, a nova senha foi salva. Entre para ver o aviso.",
  minDepositLabel: "Depósito mín.",
  maxDepositLabel: "Depósito máx.",
  expectedProfit: "Lucro esperado",
  duration: "Duração",
  days: "dias",
  unlimited: "Ilimitado",
  buyPlan: "Comprar plano",
  openToInvest: "Abrir uma conta",
  plansLead: "Disponível {amount} · Os planos bloqueiam fundos pelo prazo indicado e acumulam lucro diário nesta demo.",
  lockAmount: "Valor a bloquear (USD)",
  close: "Fechar",
  confirm: "Confirmar",
  heldTerm: "Se mantido até o prazo:",
  profitWord: "de lucro",
  returned: "devolvidos",
  selected: "{name} selecionado",
  activated: "{name} ativado",
  swapTitle: "Troca",
  swapLead: "Converta saldo USD e BDX pelo preço ao vivo da Beldex.",
  rate: "Taxa",
  from: "De",
  to: "Para",
  swapNow: "Trocar",
  swapped: "Troca feita",
  usdAvail: "USD disponível {usd} · BDX {bdx}",
  profileTitle: "Perfil",
  saveChanges: "Salvar alterações",
  profileSaved: "Perfil salvo",
  updatePhoto: "Atualizar foto",
  photoUpdated: "Foto de perfil atualizada",
  removePhoto: "Remover foto",
  photoTooBig: "Escolha uma imagem menor",
  passwordBlock: "Senha",
  passwordHint: "Altere a senha salva neste aparelho.",
  currentPassword: "Senha atual",
  updatePassword: "Atualizar senha",
  passwordUpdated: "Senha atualizada",
  settingsLead: "Conta, idioma e segurança.",
  openProfile: "Editar perfil",
  security: "Segurança",
  preferences: "Preferências",
  settingsLang: "Idioma",
  twoFactor: "Autenticação em dois fatores",
  on: "Sim",
  off: "Não",
  twoOn: "Dois fatores ativado",
  twoOff: "Dois fatores desativado",
  session: "Sessão",
  sessionBody: "Somente neste aparelho",
  marketData: "Dados de mercado",
  supportLead: "GLOBAL BELDEX é uma demo educativa. Os gráficos ao vivo vêm da TradingView.",
  supportEmail: "E-mail de suporte",
  supportPhone: "Celular",
  supportAddress: "Endereço",
  messageDesk: "Mensagem ao suporte",
  subject: "Assunto",
  message: "Mensagem",
  send: "Enviar",
  ticketLogged: "Pedido registrado",
  noNotes: "Sem avisos",
  noNotesBody: "Depósitos, planos e indicações aparecem aqui.",
  recent: "Movimentos recentes",
  viewAll: "Ver tudo",
  referralCard: "Link de indicação",
  referralCardLead: "Convide amigos e receba 10% dos depósitos deles",
  quick: "Ações rápidas",
  hello: "Olá",
  totalProfit: "Lucro total",
  bonus: "Bônus",
  referralBonus: "Bônus de indicação",
  withdrawals: "Saques",
  bdxWallet: "Carteira BDX",
  noPlans: "Nenhum plano ativo",
  noPlansBody: "Você ainda não tem investimentos ativos",
  activePlans: "Planos ativos",
  accrued: "acumulado",
  marketOverview: "Visão do mercado",
  sentiment: "Sentimento",
  fear: "Medo",
  greed: "Ganância",
  neutral: "Neutro",
  topMovers: "Maiores variações",
  trending: "Ativos em alta",
  how: "Como funciona",
  howTitle: "Três passos até o painel",
  questions: "Perguntas",
  pending: "pendente",
  completed: "concluído",
  failed: "falhou",
  tx: { deposit: "Depósito", withdraw: "Saque", bonus: "Bônus", plan: "Plano", swap: "Troca", referral: "Indicação" },
  err: {
    FILL: "Preencha os campos obrigatórios",
    NO_ACCOUNT: "Não há conta com esse e-mail ou usuário. Crie uma primeiro.",
    BAD_PASSWORD: "Senha incorreta",
    BAD_CODE: "Código incorreto",
    MIN_DEPOSIT: "O depósito mínimo é $300",
    NEED_METHOD: "Escolha um ativo de saque",
    NEED_ADDRESS: "Digite um endereço de destino",
    NEED_AMOUNT: "Digite um valor",
    INSUFFICIENT: "Saldo insuficiente",
    MIN_PLAN: "O mínimo de {a} é ${b}",
    MAX_PLAN: "O máximo de {a} é ${b}",
    NEED_DEPOSIT: "Saldo disponível insuficiente — deposite primeiro",
    SWAP_SAME: "Escolha dois ativos diferentes",
    BAD_RATE: "Taxa indisponível",
    INSUFFICIENT_USD: "Saldo USD insuficiente",
    INSUFFICIENT_BDX: "Saldo BDX insuficiente",
    NEED_TICKET: "Adicione um assunto e uma mensagem",
    NEED_EMAIL: "Digite seu e-mail ou usuário",
    SHORT_PASSWORD: "Use pelo menos 4 caracteres",
    BAD_CURRENT: "A senha atual está errada",
    BAD_REF: "Esse usuário de indicação não está neste aparelho",
    REF_SELF: "Você não pode usar a própria indicação",
    EMAIL_TAKEN: "E-mail já registrado — entre",
    SIGN_IN: "Entre primeiro",
  },
  note: {
    depositInitTitle: "Depósito iniciado",
    depositInitBody: "Depósito {method} de ${amount} em processamento.",
    depositDoneTitle: "Depósito concluído",
    depositDoneBody: "${amount} já está no saldo disponível.",
    withdrawReqTitle: "Saque solicitado",
    withdrawReqBody: "${amount} via {method} em processamento.",
    withdrawDoneTitle: "Saque concluído",
    withdrawDoneBody: "${amount} via {method} foi enviado.",
    welcomeTitle: "Bônus de boas-vindas creditado",
    welcomeBody: "Bônus de boas-vindas de $3.00 adicionado ao saldo disponível.",
    passwordTitle: "Senha atualizada",
    passwordBody: "Sua senha de acesso foi alterada neste aparelho.",
    twoOnTitle: "Dois fatores ativado",
    twoOnBody: "Seu código da demo é {code}. Digite-o na próxima entrada.",
    twoOffTitle: "Dois fatores desativado",
    twoOffBody: "A entrada não pede mais um código.",
    planTitle: "{name} ativado",
    planBody: "${amount} bloqueados por {duration}.",
    matureTitle: "Plano vencido",
    matureBody: "Principal devolvido. ${amount} de juros desta etapa foram somados ao saldo.",
    dailyTitle: "Juros diários",
    dailyBody: "${amount} de juros diários simulados foram somados ao saldo.",
    swapTitle: "Troca feita",
    referralTitle: "Bônus de indicação",
    referralBody: "{user} depositou. Você ganhou ${amount} (10%).",
    supportTitle: "O suporte respondeu",
    supportBody: "Registramos “{subject}”. Esta demo guarda os pedidos neste aparelho.",
  },
  page: pagePt,
};

const nl = {
  tag: "Geavanceerd beleggingsplatform",
  signIn: "Inloggen",
  openAccount: "Account openen",
  investNow: "Beleggen",
  explore: "Dashboard openen",
  home: "Home",
  history: "Geschiedenis",
  deposit: "Storting",
  withdraw: "Opname",
  menu: "Menu",
  dashboard: "Dashboard",
  markets: "Markten",
  plans: "Plannen",
  swap: "Wisselen",
  profile: "Profiel",
  referrals: "Verwijzingen",
  notifications: "Meldingen",
  settings: "Instellingen",
  support: "Support",
  logout: "Uitloggen",
  available: "Beschikbaar saldo",
  locked: "Geblokkeerd saldo",
  welcome: "Welkom bij GLOBAL BELDEX",
  welcomeBody: "Je dashboard is klaar. Live BDXUSD-markt is actief.",
  others: "Overig",
  transactions: "Transacties",
  liveMarket: "Live markt",
  mainMenu: "Hoofdmenu",
  finance: "Financiën",
  account: "Account",
  ready: "Klaar om te beginnen?",
  readyBody: "Start vanaf $300 · Live BDXUSD-markt",
  startInvesting: "Beginnen",
  plansTitle: "Beleggingsplannen",
  historyTitle: "Transactiegeschiedenis",
  noTx: "Geen transacties",
  noTxBody: "Je {tab}-geschiedenis verschijnt hier",
  depositTitle: "Geld storten",
  depositLead: "Voeg geld toe om te beginnen · Live BDXUSD-markt hieronder",
  amountUsd: "Bedrag (USD)",
  minHint: "Minimale storting $300 · Bijgeschreven in een paar seconden, ook als je deze pagina verlaat",
  payMethod: "Kies een betaalmethode",
  beldexInstant: "BELDEX direct",
  beldexDetail: "Aanbevolen · 0% kosten · Live BDXUSD",
  continuePay: "Doorgaan naar betaling",
  sendExactly: "Stuur precies",
  depositAddress: "Stortingsadres",
  addressCopied: "Adres gekopieerd",
  simAddress: "Dit adres is gesimuleerd. Bevestigen schrijft je demosaldo bij — er is geen on-chain overboeking.",
  back: "Terug",
  sentIt: "Ik heb het verstuurd",
  depositStarted: "Storting gestart — wordt zo bijgeschreven",
  withdrawTitle: "Geld opnemen",
  withdrawLead: "Opnames in deze demo · Live markt hieronder",
  chooseMethod: "Kies het opname-activum",
  destination: "Opnameadres",
  destPlaceholder: "Plak je walletadres",
  amount: "Bedrag",
  enterAmount: "Vul het bedrag in",
  max: "Max",
  withdrawNow: "Nu opnemen",
  withdrawRequested: "Opname aangevraagd",
  secure: "Veilige verwerking",
  secureBody: "256-bit versleuteling",
  fast: "Snelle opnames",
  fastBody: "In deze demo klaar in een paar seconden",
  referralTitle: "Verwijzingen",
  referralLead: "Nodig vrienden uit en ontvang 10% van elke storting die zij afronden.",
  referralEarned: "Verdiende verwijzingsbonus",
  yourLink: "Jouw link",
  copyLink: "Link kopiëren",
  linkCopied: "Verwijzingslink gekopieerd",
  referralFine: "De link delen betaalt niet. De 10% komt binnen wanneer iemand zich registreert met jouw gebruikersnaam en de storting afrondt.",
  loginTitle: "Welkom terug",
  loginLead: "Log in om verder te gaan",
  emailOrUser: "E-mail of gebruikersnaam",
  password: "Wachtwoord",
  codeLabel: "6-cijferige code",
  remember: "Onthoud mij",
  forgot: "Wachtwoord vergeten?",
  notMember: "Nog geen account?",
  signUp: "Registreren",
  welcomeBack: "Welkom terug!",
  needCode: "Vul je 6-cijferige code in",
  createTitle: "Account aanmaken",
  createLead: "Begin vandaag",
  username: "Gebruikersnaam",
  fullname: "Volledige naam",
  email: "E-mail",
  phone: "Telefoon",
  country: "Land",
  selectCountry: "Kies een land",
  referralOptional: "Gebruikersnaam van verwijzer (optioneel)",
  repeatPassword: "Herhaal wachtwoord",
  createBtn: "Account aanmaken",
  haveAccount: "Heb je al een account?",
  mismatch: "Wachtwoorden komen niet overeen",
  created: "Account aangemaakt — $3 bonus toegevoegd",
  checkEmailTitle: "Controleer je e-mail",
  checkEmailBody: "We hebben een bevestigingslink gestuurd. Open die in deze browser om af te ronden. Saldi blijven gesimuleerd op dit apparaat.",
  accept: "Een account aanmaken betekent dat je de notities Voorwaarden, Privacy en Risico accepteert. Saldi blijven gesimuleerd op dit apparaat.",
  acceptLead: "Een account aanmaken betekent dat je de notities ",
  termsWord: "Voorwaarden",
  privacyWord: "Privacy",
  acceptAnd: " en ",
  riskWord: "Risico",
  acceptTail: " accepteert. Saldi blijven gesimuleerd op dit apparaat.",
  shortPass: "Gebruik minstens 6 tekens",
  confirming: "Bevestigen…",
  useAccountEmail: "Gebruik het e-mailadres van het account",
  forgotTitle: "Wachtwoord vergeten",
  forgotLead: "Vul het e-mailadres van je account in. We sturen een link. Open die in deze browser en kies een nieuw wachtwoord.",
  sendReset: "Doorgaan",
  setNew: "Nieuw wachtwoord instellen",
  newPassword: "Nieuw wachtwoord",
  savePassword: "Wachtwoord opslaan",
  savedIf: "Als dat account op dit apparaat staat, is het nieuwe wachtwoord opgeslagen. Log in om de melding te zien.",
  minDepositLabel: "Min. storting",
  maxDepositLabel: "Max. storting",
  expectedProfit: "Verwachte winst",
  duration: "Duur",
  days: "dagen",
  unlimited: "Onbeperkt",
  buyPlan: "Plan kopen",
  openToInvest: "Account openen",
  plansLead: "Beschikbaar {amount} · Plannen blokkeren geld voor de genoemde termijn en tellen dagelijkse winst op in deze demo.",
  lockAmount: "Te blokkeren bedrag (USD)",
  close: "Sluiten",
  confirm: "Bevestigen",
  heldTerm: "Als je het tot het einde aanhoudt:",
  profitWord: "winst",
  returned: "terug",
  selected: "{name} geselecteerd",
  activated: "{name} geactiveerd",
  swapTitle: "Wisselen",
  swapLead: "Wissel USD-saldo en BDX tegen de live Beldex-koers.",
  rate: "Koers",
  from: "Van",
  to: "Naar",
  swapNow: "Nu wisselen",
  swapped: "Wissel uitgevoerd",
  usdAvail: "USD beschikbaar {usd} · BDX {bdx}",
  profileTitle: "Profiel",
  saveChanges: "Wijzigingen opslaan",
  profileSaved: "Profiel opgeslagen",
  updatePhoto: "Foto bijwerken",
  photoUpdated: "Profielfoto bijgewerkt",
  removePhoto: "Foto verwijderen",
  photoTooBig: "Kies een kleinere afbeelding",
  passwordBlock: "Wachtwoord",
  passwordHint: "Wijzig het wachtwoord dat op dit apparaat staat.",
  currentPassword: "Huidig wachtwoord",
  updatePassword: "Wachtwoord bijwerken",
  passwordUpdated: "Wachtwoord bijgewerkt",
  settingsLead: "Account, taal en beveiliging.",
  openProfile: "Profiel bewerken",
  security: "Beveiliging",
  preferences: "Voorkeuren",
  settingsLang: "Taal",
  twoFactor: "Tweestapsverificatie",
  on: "Aan",
  off: "Uit",
  twoOn: "Tweestapsverificatie aan",
  twoOff: "Tweestapsverificatie uit",
  session: "Sessie",
  sessionBody: "Alleen op dit apparaat",
  marketData: "Marktgegevens",
  supportLead: "GLOBAL BELDEX is een educatieve demo. Live grafieken komen van TradingView.",
  supportEmail: "Support-e-mail",
  supportPhone: "Mobiel",
  supportAddress: "Adres",
  messageDesk: "Bericht aan support",
  subject: "Onderwerp",
  message: "Bericht",
  send: "Versturen",
  ticketLogged: "Ticket opgeslagen",
  noNotes: "Geen meldingen",
  noNotesBody: "Stortingen, plannen en verwijzingen verschijnen hier.",
  recent: "Recente transacties",
  viewAll: "Alles bekijken",
  referralCard: "Verwijzingslink",
  referralCardLead: "Nodig vrienden uit en ontvang 10% van hun stortingen",
  quick: "Snelle acties",
  hello: "Hallo",
  totalProfit: "Totale winst",
  bonus: "Bonus",
  referralBonus: "Verwijzingsbonus",
  withdrawals: "Opnames",
  bdxWallet: "BDX-wallet",
  noPlans: "Geen actieve plannen",
  noPlansBody: "Je hebt nog geen actieve beleggingen",
  activePlans: "Actieve plannen",
  accrued: "opgebouwd",
  marketOverview: "Marktoverzicht",
  sentiment: "Sentiment",
  fear: "Angst",
  greed: "Hebzucht",
  neutral: "Neutraal",
  topMovers: "Grootste bewegers",
  trending: "Trending activa",
  how: "Hoe het werkt",
  howTitle: "Drie stappen naar het dashboard",
  questions: "Vragen",
  pending: "in behandeling",
  completed: "voltooid",
  failed: "mislukt",
  tx: { deposit: "Storting", withdraw: "Opname", bonus: "Bonus", plan: "Plan", swap: "Wissel", referral: "Verwijzing" },
  err: {
    FILL: "Vul de verplichte velden in",
    NO_ACCOUNT: "Geen account voor dat e-mailadres of die gebruikersnaam. Maak er eerst een.",
    BAD_PASSWORD: "Onjuist wachtwoord",
    BAD_CODE: "Onjuiste code",
    MIN_DEPOSIT: "Minimale storting is $300",
    NEED_METHOD: "Kies een opname-activum",
    NEED_ADDRESS: "Vul een bestemmingsadres in",
    NEED_AMOUNT: "Vul een bedrag in",
    INSUFFICIENT: "Onvoldoende saldo",
    MIN_PLAN: "Minimum voor {a} is ${b}",
    MAX_PLAN: "Maximum voor {a} is ${b}",
    NEED_DEPOSIT: "Onvoldoende beschikbaar saldo — stort eerst",
    SWAP_SAME: "Kies twee verschillende activa",
    BAD_RATE: "Koers niet beschikbaar",
    INSUFFICIENT_USD: "Onvoldoende USD-saldo",
    INSUFFICIENT_BDX: "Onvoldoende BDX-saldo",
    NEED_TICKET: "Voeg een onderwerp en een bericht toe",
    NEED_EMAIL: "Vul je e-mail of gebruikersnaam in",
    SHORT_PASSWORD: "Gebruik minstens 4 tekens",
    BAD_CURRENT: "Het huidige wachtwoord klopt niet",
    BAD_REF: "Die verwijzende gebruikersnaam staat niet op dit apparaat",
    REF_SELF: "Je kunt je eigen verwijzing niet gebruiken",
    EMAIL_TAKEN: "E-mail al geregistreerd — log in",
    SIGN_IN: "Log eerst in",
  },
  note: {
    depositInitTitle: "Storting gestart",
    depositInitBody: "{method}-storting van ${amount} wordt verwerkt.",
    depositDoneTitle: "Storting voltooid",
    depositDoneBody: "${amount} staat nu op je beschikbare saldo.",
    withdrawReqTitle: "Opname aangevraagd",
    withdrawReqBody: "${amount} via {method} wordt verwerkt.",
    withdrawDoneTitle: "Opname voltooid",
    withdrawDoneBody: "${amount} via {method} is verstuurd.",
    welcomeTitle: "Welkomstbonus bijgeschreven",
    welcomeBody: "Welkomstbonus van $3.00 toegevoegd aan je beschikbare saldo.",
    passwordTitle: "Wachtwoord bijgewerkt",
    passwordBody: "Je inlogwachtwoord is op dit apparaat gewijzigd.",
    twoOnTitle: "Tweestapsverificatie aan",
    twoOnBody: "Je democode is {code}. Vul die in bij de volgende login.",
    twoOffTitle: "Tweestapsverificatie uit",
    twoOffBody: "Inloggen vraagt geen code meer.",
    planTitle: "{name} geactiveerd",
    planBody: "${amount} geblokkeerd voor {duration}.",
    matureTitle: "Plan afgelopen",
    matureBody: "Inleg terug. ${amount} rente van deze stap is aan je saldo toegevoegd.",
    dailyTitle: "Dagelijkse rente",
    dailyBody: "${amount} gesimuleerde dagelijkse rente is aan je saldo toegevoegd.",
    swapTitle: "Wissel uitgevoerd",
    referralTitle: "Verwijzingsbonus",
    referralBody: "{user} heeft gestort. Je verdiende ${amount} (10%).",
    supportTitle: "Support heeft geantwoord",
    supportBody: "We hebben “{subject}” genoteerd. Deze demo bewaart tickets op je apparaat.",
  },
  page: pageNl,
};

export function extraLangs(en: Dict): Record<Exclude<Lang, "en" | "es">, Dict> {
  return {
    fr: merge(en, fr),
    it: merge(en, it),
    pt: merge(en, pt),
    nl: merge(en, nl),
  };
}
