import type { Lang } from "@/lib/platform/i18n";
import { pageFr, pageIt, pageNl, pagePt } from "@/lib/platform/page-copy";

type Dict = Record<string, unknown>;

function merge(base: Dict, over: Dict): Dict {
  const out: Dict = { ...base };
  for (const key of Object.keys(over)) {
    const next = over[key];
    const prev = base[key];
    if (next && typeof next === "object" && !Array.isArray(next) && prev && typeof prev === "object") {
      out[key] = merge(prev as Dict, next as Dict);
    } else {
      out[key] = next;
    }
  }
  return out;
}

const fr = {
  tag: "Plateforme d’investissement avancée",
  signIn: "Connexion",
  openAccount: "Ouvrir un compte",
  investNow: "Investir",
  explore: "Voir le tableau de bord",
  home: "Accueil",
  history: "Historique",
  deposit: "Dépôt",
  withdraw: "Retrait",
  menu: "Menu",
  dashboard: "Tableau de bord",
  markets: "Marchés",
  plans: "Plans",
  swap: "Échange",
  profile: "Profil",
  referrals: "Parrainages",
  notifications: "Notifications",
  settings: "Réglages",
  support: "Assistance",
  logout: "Déconnexion",
  available: "Solde disponible",
  locked: "Solde bloqué",
  welcome: "Bienvenue sur GLOBAL BELDEX",
  welcomeBody: "Votre tableau de bord est prêt. Marché BDXUSD en direct actif.",
  others: "Autres",
  transactions: "Transactions",
  liveMarket: "Marché en direct",
  mainMenu: "Menu principal",
  finance: "Finance",
  account: "Compte",
  ready: "Prêt à avancer ?",
  readyBody: "Commencez dès 300 $ · Marché BDXUSD en direct",
  startInvesting: "Commencer",
  plansTitle: "Plans d’investissement",
  historyTitle: "Historique des transactions",
  noTx: "Aucune transaction",
  noTxBody: "Votre historique {tab} apparaîtra ici",
  depositTitle: "Déposer des fonds",
  depositLead: "Ajoutez des fonds pour commencer · Marché BDXUSD en direct ci-dessous",
  amountUsd: "Montant (USD)",
  minHint: "Dépôt minimum 300 $ · Crédité en quelques secondes, même si vous quittez la page",
  payMethod: "Choisir un moyen de paiement",
  beldexInstant: "BELDEX instantané",
  beldexDetail: "Recommandé · 0 % de frais · BDXUSD en direct",
  continuePay: "Continuer vers le paiement",
  sendExactly: "Envoyez exactement",
  depositAddress: "Adresse de dépôt",
  addressCopied: "Adresse copiée",
  simAddress: "Cette adresse est simulée. Confirmer crédite le solde de démo — aucun transfert on-chain.",
  back: "Retour",
  sentIt: "Je l’ai envoyé",
  depositStarted: "Dépôt lancé — il sera crédité sous peu",
  withdrawTitle: "Retirer vos fonds",
  withdrawLead: "Retraits dans cette démo · Marché en direct ci-dessous",
  chooseMethod: "Choisir l’actif de retrait",
  destination: "Adresse de retrait",
  destPlaceholder: "Collez votre adresse de portefeuille",
  amount: "Montant",
  enterAmount: "Saisir le montant",
  max: "Max",
  withdrawNow: "Retirer",
  withdrawRequested: "Retrait demandé",
  secure: "Traitement sécurisé",
  secureBody: "Chiffrement 256 bits",
  fast: "Retraits rapides",
  fastBody: "Terminé en quelques secondes dans cette démo",
  referralTitle: "Parrainages",
  referralLead: "Invitez des amis et recevez 10 % de chaque dépôt qu’ils terminent.",
  referralEarned: "Bonus de parrainage gagné",
  yourLink: "Votre lien",
  copyLink: "Copier le lien",
  linkCopied: "Lien de parrainage copié",
  referralFine: "Partager le lien ne paie pas. Les 10 % arrivent quand quelqu’un s’inscrit avec votre nom et que son dépôt se termine.",
  loginTitle: "Bon retour",
  loginLead: "Connectez-vous pour continuer",
  emailOrUser: "E-mail ou nom d’utilisateur",
  password: "Mot de passe",
  codeLabel: "Code à 6 chiffres",
  remember: "Se souvenir de moi",
  forgot: "Mot de passe oublié ?",
  notMember: "Pas encore membre ?",
  signUp: "S’inscrire",
  welcomeBack: "Bon retour !",
  needCode: "Saisissez votre code à 6 chiffres",
  createTitle: "Créer un compte",
  createLead: "Commencez aujourd’hui",
  username: "Nom d’utilisateur",
  fullname: "Nom complet",
  email: "E-mail",
  phone: "Téléphone",
  country: "Pays",
  selectCountry: "Choisir un pays",
  referralOptional: "Nom d’utilisateur du parrain (facultatif)",
  repeatPassword: "Répéter le mot de passe",
  createBtn: "Créer le compte",
  haveAccount: "Vous avez déjà un compte ?",
  mismatch: "Les mots de passe ne correspondent pas",
  created: "Compte créé — bonus de 3 $ ajouté",
  checkEmailTitle: "Vérifiez votre e-mail",
  checkEmailBody: "Nous avons envoyé un lien de confirmation. Ouvrez-le dans ce navigateur pour terminer. Les soldes restent simulés sur cet appareil.",
  accept: "Créer un compte signifie que vous acceptez les notes Conditions, Confidentialité et Risque. Les soldes restent simulés sur cet appareil.",
  acceptLead: "Créer un compte signifie que vous acceptez les ",
  termsWord: "Conditions",
  privacyWord: "Confidentialité",
  acceptAnd: " et ",
  riskWord: "Risque",
  acceptTail: ". Les soldes restent simulés sur cet appareil.",
  shortPass: "Utilisez au moins 6 caractères",
  confirming: "Confirmation…",
  useAccountEmail: "Utilisez l’e-mail du compte",
  forgotTitle: "Mot de passe oublié",
  forgotLead: "Saisissez l’e-mail du compte. Nous enverrons un lien. Ouvrez-le dans ce navigateur, puis choisissez un nouveau mot de passe.",
  sendReset: "Continuer",
  setNew: "Choisir un nouveau mot de passe",
  newPassword: "Nouveau mot de passe",
  savePassword: "Enregistrer le mot de passe",
  savedIf: "Si ce compte est sur cet appareil, le nouveau mot de passe est enregistré. Connectez-vous pour voir l’avis.",
  minDepositLabel: "Dépôt min.",
  maxDepositLabel: "Dépôt max.",
  expectedProfit: "Profit attendu",
  duration: "Durée",
  days: "jours",
  unlimited: "Illimité",
  buyPlan: "Acheter le plan",
  openToInvest: "Ouvrir un compte",
  plansLead: "Disponible {amount} · Les plans bloquent les fonds pour la durée indiquée et ajoutent un profit quotidien dans cette démo.",
  lockAmount: "Montant à bloquer (USD)",
  close: "Fermer",
  confirm: "Confirmer",
  heldTerm: "Si conservé jusqu’au terme :",
  profitWord: "de profit",
  returned: "rendus",
  selected: "{name} sélectionné",
  activated: "{name} activé",
  swapTitle: "Échange",
  swapLead: "Convertissez le solde USD et BDX au cours Beldex en direct.",
  rate: "Cours",
  from: "De",
  to: "Vers",
  swapNow: "Échanger",
  swapped: "Échange effectué",
  usdAvail: "USD disponible {usd} · BDX {bdx}",
  profileTitle: "Profil",
  saveChanges: "Enregistrer",
  profileSaved: "Profil enregistré",
  updatePhoto: "Mettre à jour la photo",
  photoUpdated: "Photo de profil mise à jour",
  removePhoto: "Retirer la photo",
  photoTooBig: "Choisis une image plus petite",
  passwordBlock: "Mot de passe",
  passwordHint: "Changez le mot de passe enregistré sur cet appareil.",
  currentPassword: "Mot de passe actuel",
  updatePassword: "Mettre à jour le mot de passe",
  passwordUpdated: "Mot de passe mis à jour",
  settingsLead: "Compte, langue et sécurité.",
  openProfile: "Modifier le profil",
  security: "Sécurité",
  preferences: "Préférences",
  settingsLang: "Langue",
  twoFactor: "Double authentification",
  on: "Oui",
  off: "Non",
  twoOn: "Double authentification activée",
  twoOff: "Double authentification désactivée",
  session: "Session",
  sessionBody: "Uniquement sur cet appareil",
  marketData: "Données de marché",
  supportLead: "GLOBAL BELDEX est une démo éducative. Les graphiques en direct viennent de TradingView.",
  supportEmail: "E-mail d’assistance",
  supportPhone: "Mobile",
  supportAddress: "Adresse",
  messageDesk: "Écrire à l’assistance",
  subject: "Objet",
  message: "Message",
  send: "Envoyer",
  ticketLogged: "Ticket enregistré",
  noNotes: "Aucune notification",
  noNotesBody: "Les dépôts, plans et parrainages apparaissent ici.",
  recent: "Transactions récentes",
  viewAll: "Tout voir",
  referralCard: "Lien de parrainage",
  referralCardLead: "Invitez des amis et recevez 10 % de leurs dépôts",
  quick: "Actions rapides",
  hello: "Bonjour",
  totalProfit: "Profit total",
  bonus: "Bonus",
  referralBonus: "Bonus de parrainage",
  withdrawals: "Retraits",
  bdxWallet: "Portefeuille BDX",
  noPlans: "Aucun plan actif",
  noPlansBody: "Vous n’avez pas encore d’investissement actif",
  activePlans: "Plans actifs",
  accrued: "accumulé",
  marketOverview: "Aperçu du marché",
  sentiment: "Sentiment",
  fear: "Peur",
  greed: "Avidité",
  neutral: "Neutre",
  topMovers: "Plus fortes variations",
  trending: "Actifs tendance",
  how: "Comment ça marche",
  howTitle: "Trois étapes vers le tableau de bord",
  questions: "Questions",
  pending: "en attente",
  completed: "terminé",
  failed: "échoué",
  tx: { deposit: "Dépôt", withdraw: "Retrait", bonus: "Bonus", plan: "Plan", swap: "Échange", referral: "Parrainage" },
  err: {
    FILL: "Remplissez les champs requis",
    NO_ACCOUNT: "Aucun compte pour cet e-mail ou ce nom. Créez-en un.",
    BAD_PASSWORD: "Mot de passe incorrect",
    BAD_CODE: "Code incorrect",
    MIN_DEPOSIT: "Le dépôt minimum est de 300 $",
    NEED_METHOD: "Choisissez un actif de retrait",
    NEED_ADDRESS: "Saisissez une adresse de destination",
    NEED_AMOUNT: "Saisissez un montant",
    INSUFFICIENT: "Solde insuffisant",
    MIN_PLAN: "Le minimum pour {a} est {b} $",
    MAX_PLAN: "Le maximum pour {a} est {b} $",
    NEED_DEPOSIT: "Solde disponible insuffisant — déposez d’abord",
    SWAP_SAME: "Choisissez deux actifs différents",
    BAD_RATE: "Cours indisponible",
    INSUFFICIENT_USD: "Solde USD insuffisant",
    INSUFFICIENT_BDX: "Solde BDX insuffisant",
    NEED_TICKET: "Ajoutez un objet et un message",
    NEED_EMAIL: "Saisissez votre e-mail ou votre nom",
    SHORT_PASSWORD: "Utilisez au moins 4 caractères",
    BAD_CURRENT: "Le mot de passe actuel est incorrect",
    BAD_REF: "Ce nom de parrain est introuvable sur cet appareil",
    REF_SELF: "Vous ne pouvez pas utiliser votre propre parrainage",
    EMAIL_TAKEN: "E-mail déjà enregistré — connectez-vous",
    SIGN_IN: "Connectez-vous d’abord",
  },
  note: {
    depositInitTitle: "Dépôt lancé",
    depositInitBody: "Dépôt {method} de {amount} $ en cours.",
    depositDoneTitle: "Dépôt terminé",
    depositDoneBody: "{amount} $ est maintenant sur votre solde disponible.",
    withdrawReqTitle: "Retrait demandé",
    withdrawReqBody: "{amount} $ via {method} en cours.",
    withdrawDoneTitle: "Retrait terminé",
    withdrawDoneBody: "{amount} $ via {method} a été envoyé.",
    welcomeTitle: "Bonus de bienvenue crédité",
    welcomeBody: "Bonus de bienvenue de 3,00 $ ajouté à votre solde disponible.",
    passwordTitle: "Mot de passe mis à jour",
    passwordBody: "Votre mot de passe a été changé sur cet appareil.",
    twoOnTitle: "Double authentification activée",
    twoOnBody: "Votre code de démo est {code}. Saisissez-le à la prochaine connexion.",
    twoOffTitle: "Double authentification désactivée",
    twoOffBody: "La connexion ne demande plus de code.",
    planTitle: "{name} activé",
    planBody: "{amount} $ bloqués pour {duration}.",
    matureTitle: "Plan arrivé à terme",
    matureBody: "Capital rendu. {amount} $ d’intérêt de cette étape ont été ajoutés à votre solde.",
    dailyTitle: "Intérêt quotidien",
    dailyBody: "{amount} $ d’intérêt quotidien simulé ont été ajoutés à votre solde.",
    swapTitle: "Échange effectué",
    referralTitle: "Bonus de parrainage",
    referralBody: "{user} a déposé. Vous avez gagné {amount} $ (10 %).",
    supportTitle: "L’assistance a répondu",
    supportBody: "Nous avons noté « {subject} ». Cette démo garde les tickets sur votre appareil.",
  },
  page: pageFr,
};

const it = {
  tag: "Piattaforma di investimento avanzata",
  signIn: "Accedi",
  openAccount: "Apri un conto",
  investNow: "Investi",
  explore: "Apri la dashboard",
  home: "Home",
  history: "Cronologia",
  deposit: "Deposito",
  withdraw: "Prelievo",
  menu: "Menu",
  dashboard: "Dashboard",
  markets: "Mercati",
  plans: "Piani",
  swap: "Scambio",
  profile: "Profilo",
  referrals: "Inviti",
  notifications: "Avvisi",
  settings: "Impostazioni",
  support: "Assistenza",
  logout: "Esci",
  available: "Saldo disponibile",
  locked: "Saldo bloccato",
  welcome: "Benvenuto in GLOBAL BELDEX",
  welcomeBody: "La dashboard è pronta. Mercato BDXUSD live attivo.",
  others: "Altro",
  transactions: "Movimenti",
  liveMarket: "Mercato live",
  mainMenu: "Menu principale",
  finance: "Finanza",
  account: "Account",
  ready: "Pronto a iniziare?",
  readyBody: "Parti da 300 $ · Mercato BDXUSD live",
  startInvesting: "Inizia",
  plansTitle: "Piani di investimento",
  historyTitle: "Cronologia movimenti",
  noTx: "Nessun movimento",
  noTxBody: "La cronologia {tab} apparirà qui",
  depositTitle: "Deposita fondi",
  depositLead: "Aggiungi fondi per iniziare · Mercato BDXUSD live sotto",
  amountUsd: "Importo (USD)",
  minHint: "Deposito minimo 300 $ · Accreditato in pochi secondi, anche se lasci la pagina",
  payMethod: "Scegli il metodo di pagamento",
  beldexInstant: "BELDEX istantaneo",
  beldexDetail: "Consigliato · commissione 0% · BDXUSD live",
  continuePay: "Continua al pagamento",
  sendExactly: "Invia esattamente",
  depositAddress: "Indirizzo di deposito",
  addressCopied: "Indirizzo copiato",
  simAddress: "Questo indirizzo è simulato. La conferma accredita il saldo demo — nessun invio on-chain.",
  back: "Indietro",
  sentIt: "L’ho inviato",
  depositStarted: "Deposito avviato — sarà accreditato a breve",
  withdrawTitle: "Preleva i fondi",
  withdrawLead: "Prelievi in questa demo · Mercato live sotto",
  chooseMethod: "Scegli l’asset di prelievo",
  destination: "Indirizzo di prelievo",
  destPlaceholder: "Incolla l’indirizzo del wallet",
  amount: "Importo",
  enterAmount: "Inserisci l’importo",
  max: "Max",
  withdrawNow: "Preleva ora",
  withdrawRequested: "Prelievo richiesto",
  secure: "Elaborazione sicura",
  secureBody: "Cifratura a 256 bit",
  fast: "Prelievi rapidi",
  fastBody: "In questa demo si completano in pochi secondi",
  referralTitle: "Inviti",
  referralLead: "Invita amici e ricevi il 10% di ogni deposito che completano.",
  referralEarned: "Bonus inviti guadagnato",
  yourLink: "Il tuo link",
  copyLink: "Copia link",
  linkCopied: "Link di invito copiato",
  referralFine: "Condividere il link non paga. Il 10% arriva quando qualcuno si registra con il tuo nome utente e il deposito si completa.",
  loginTitle: "Bentornato",
  loginLead: "Accedi per continuare",
  emailOrUser: "Email o nome utente",
  password: "Password",
  codeLabel: "Codice a 6 cifre",
  remember: "Ricordami",
  forgot: "Password dimenticata?",
  notMember: "Non sei ancora iscritto?",
  signUp: "Registrati",
  welcomeBack: "Bentornato!",
  needCode: "Inserisci il codice a 6 cifre",
  createTitle: "Crea account",
  createLead: "Inizia oggi",
  username: "Nome utente",
  fullname: "Nome completo",
  email: "Email",
  phone: "Telefono",
  country: "Paese",
  selectCountry: "Scegli il paese",
  referralOptional: "Nome utente di chi ti invita (facoltativo)",
  repeatPassword: "Ripeti la password",
  createBtn: "Crea account",
  haveAccount: "Hai già un account?",
  mismatch: "Le password non coincidono",
  created: "Account creato — bonus di 3 $ aggiunto",
  checkEmailTitle: "Controlla l’email",
  checkEmailBody: "Abbiamo inviato un link di conferma. Aprilo in questo browser per finire. I saldi restano simulati su questo dispositivo.",
  accept: "Creare un account significa accettare le note Termini, Privacy e Rischio. I saldi restano simulati su questo dispositivo.",
  acceptLead: "Creare un account significa accettare le note ",
  termsWord: "Termini",
  privacyWord: "Privacy",
  acceptAnd: " e ",
  riskWord: "Rischio",
  acceptTail: ". I saldi restano simulati su questo dispositivo.",
  shortPass: "Usa almeno 6 caratteri",
  confirming: "Conferma in corso…",
  useAccountEmail: "Usa l’email dell’account",
  forgotTitle: "Password dimenticata",
  forgotLead: "Inserisci l’email dell’account. Invieremo un link. Aprilo in questo browser e scegli una nuova password.",
  sendReset: "Continua",
  setNew: "Imposta una nuova password",
  newPassword: "Nuova password",
  savePassword: "Salva password",
  savedIf: "Se quell’account è su questo dispositivo, la nuova password è salvata. Accedi per vedere l’avviso.",
  minDepositLabel: "Deposito min.",
  maxDepositLabel: "Deposito max.",
  expectedProfit: "Profitto atteso",
  duration: "Durata",
  days: "giorni",
  unlimited: "Illimitato",
  buyPlan: "Acquista piano",
  openToInvest: "Apri un account",
  plansLead: "Disponibile {amount} · I piani bloccano i fondi per il periodo indicato e accumulano profitto giornaliero in questa demo.",
  lockAmount: "Importo da bloccare (USD)",
  close: "Chiudi",
  confirm: "Conferma",
  heldTerm: "Se tenuto fino a scadenza:",
  profitWord: "di profitto",
  returned: "restituiti",
  selected: "{name} selezionato",
  activated: "{name} attivato",
  swapTitle: "Scambio",
  swapLead: "Converti saldo USD e BDX al prezzo live di Beldex.",
  rate: "Tasso",
  from: "Da",
  to: "A",
  swapNow: "Scambia",
  swapped: "Scambio eseguito",
  usdAvail: "USD disponibile {usd} · BDX {bdx}",
  profileTitle: "Profilo",
  saveChanges: "Salva modifiche",
  profileSaved: "Profilo salvato",
  updatePhoto: "Aggiorna foto",
  photoUpdated: "Foto profilo aggiornata",
  removePhoto: "Rimuovi foto",
  photoTooBig: "Scegli un'immagine più piccola",
  passwordBlock: "Password",
  passwordHint: "Cambia la password salvata su questo dispositivo.",
  currentPassword: "Password attuale",
  updatePassword: "Aggiorna password",
  passwordUpdated: "Password aggiornata",
  settingsLead: "Account, lingua e sicurezza.",
  openProfile: "Modifica profilo",
  security: "Sicurezza",
  preferences: "Preferenze",
  settingsLang: "Lingua",
  twoFactor: "Autenticazione a due fattori",
  on: "Sì",
  off: "No",
  twoOn: "Due fattori attivo",
  twoOff: "Due fattori disattivo",
  session: "Sessione",
  sessionBody: "Solo su questo dispositivo",
  marketData: "Dati di mercato",
  supportLead: "GLOBAL BELDEX è una demo educativa. I grafici live arrivano da TradingView.",
  supportEmail: "Email di assistenza",
  supportPhone: "Cellulare",
  supportAddress: "Indirizzo",
  messageDesk: "Scrivi all’assistenza",
  subject: "Oggetto",
  message: "Messaggio",
  send: "Invia",
  ticketLogged: "Richiesta registrata",
  noNotes: "Nessun avviso",
  noNotesBody: "Depositi, piani e inviti compaiono qui.",
  recent: "Movimenti recenti",
  viewAll: "Vedi tutto",
  referralCard: "Link di invito",
  referralCardLead: "Invita amici e ricevi il 10% dei loro depositi",
  quick: "Azioni rapide",
  hello: "Ciao",
  totalProfit: "Profitto totale",
  bonus: "Bonus",
  referralBonus: "Bonus inviti",
  withdrawals: "Prelievi",
  bdxWallet: "Wallet BDX",
  noPlans: "Nessun piano attivo",
  noPlansBody: "Non hai ancora investimenti attivi",
  activePlans: "Piani attivi",
  accrued: "maturato",
  marketOverview: "Panoramica di mercato",
  sentiment: "Sentiment",
  fear: "Paura",
  greed: "Avidità",
  neutral: "Neutro",
  topMovers: "Più mossi",
  trending: "Asset di tendenza",
  how: "Come funziona",
  howTitle: "Tre passi fino alla dashboard",
  questions: "Domande",
  pending: "in attesa",
  completed: "completato",
  failed: "fallito",
  tx: { deposit: "Deposito", withdraw: "Prelievo", bonus: "Bonus", plan: "Piano", swap: "Scambio", referral: "Invito" },
  err: {
    FILL: "Compila i campi obbligatori",
    NO_ACCOUNT: "Nessun account per quell’email o nome utente. Creane uno.",
    BAD_PASSWORD: "Password errata",
    BAD_CODE: "Codice errato",
    MIN_DEPOSIT: "Il deposito minimo è 300 $",
    NEED_METHOD: "Scegli un asset di prelievo",
    NEED_ADDRESS: "Inserisci un indirizzo di destinazione",
    NEED_AMOUNT: "Inserisci un importo",
    INSUFFICIENT: "Saldo insufficiente",
    MIN_PLAN: "Il minimo per {a} è ${b}",
    MAX_PLAN: "Il massimo per {a} è ${b}",
    NEED_DEPOSIT: "Saldo disponibile insufficiente — deposita prima",
    SWAP_SAME: "Scegli due asset diversi",
    BAD_RATE: "Tasso non disponibile",
    INSUFFICIENT_USD: "Saldo USD insufficiente",
    INSUFFICIENT_BDX: "Saldo BDX insufficiente",
    NEED_TICKET: "Aggiungi oggetto e messaggio",
    NEED_EMAIL: "Inserisci email o nome utente",
    SHORT_PASSWORD: "Usa almeno 4 caratteri",
    BAD_CURRENT: "La password attuale non è corretta",
    BAD_REF: "Quel nome invito non è su questo dispositivo",
    REF_SELF: "Non puoi usare il tuo stesso invito",
    EMAIL_TAKEN: "Email già registrata — accedi",
    SIGN_IN: "Accedi prima",
  },
  note: {
    depositInitTitle: "Deposito avviato",
    depositInitBody: "Deposito {method} di ${amount} in elaborazione.",
    depositDoneTitle: "Deposito completato",
    depositDoneBody: "${amount} è ora nel saldo disponibile.",
    withdrawReqTitle: "Prelievo richiesto",
    withdrawReqBody: "${amount} tramite {method} in elaborazione.",
    withdrawDoneTitle: "Prelievo completato",
    withdrawDoneBody: "${amount} tramite {method} è stato inviato.",
    welcomeTitle: "Bonus di benvenuto accreditato",
    welcomeBody: "Bonus di benvenuto di $3.00 aggiunto al saldo disponibile.",
    passwordTitle: "Password aggiornata",
    passwordBody: "La password di accesso è stata cambiata su questo dispositivo.",
    twoOnTitle: "Due fattori attivo",
    twoOnBody: "Il tuo codice demo è {code}. Inseriscilo al prossimo accesso.",
    twoOffTitle: "Due fattori disattivo",
    twoOffBody: "L’accesso non chiede più un codice.",
    planTitle: "{name} attivato",
    planBody: "${amount} bloccati per {duration}.",
    matureTitle: "Piano scaduto",
    matureBody: "Capitale restituito. ${amount} di interesse di questo passaggio è stato aggiunto al saldo.",
    dailyTitle: "Interesse giornaliero",
    dailyBody: "${amount} di interesse giornaliero simulato è stato aggiunto al saldo.",
    swapTitle: "Scambio eseguito",
    referralTitle: "Bonus invito",
    referralBody: "{user} ha depositato. Hai guadagnato ${amount} (10%).",
    supportTitle: "L’assistenza ha risposto",
    supportBody: "Abbiamo registrato “{subject}”. Questa demo tiene i ticket sul dispositivo.",
  },
  page: pageIt,
};

const pt = {
  tag: "Plataforma de investimento avançada",
  signIn: "Entrar",
  openAccount: "Abrir conta",
  investNow: "Investir",
  explore: "Ver o painel",
  home: "Início",
  history: "Histórico",
  deposit: "Depósito",
  withdraw: "Saque",
  menu: "Menu",
  dashboard: "Painel",
  markets: "Mercados",
  plans: "Planos",
  swap: "Troca",
  profile: "Perfil",
  referrals: "Indicações",
  notifications: "Avisos",
  settings: "Ajustes",
  support: "Suporte",
  logout: "Sair",
  available: "Saldo disponível",
  locked: "Saldo bloqueado",
  welcome: "Bem-vindo à GLOBAL BELDEX",
  welcomeBody: "Seu painel está pronto. Mercado BDXUSD ao vivo ativo.",
  others: "Outros",
  transactions: "Movimentos",
  liveMarket: "Mercado ao vivo",
  mainMenu: "Menu principal",
  finance: "Finanças",
  account: "Conta",
  ready: "Pronto para começar?",
  readyBody: "Comece a partir de $300 · Mercado BDXUSD ao vivo",
  startInvesting: "Começar",
  plansTitle: "Planos de investimento",
  historyTitle: "Histórico de movimentos",
  noTx: "Sem movimentos",
  noTxBody: "Seu histórico de {tab} aparece aqui",
  depositTitle: "Depositar fundos",
  depositLead: "Adicione fundos para começar · Mercado BDXUSD ao vivo abaixo",
  amountUsd: "Valor (USD)",
  minHint: "Depósito mínimo $300 · Creditado em segundos, mesmo se você sair desta página",
  payMethod: "Escolha a forma de pagamento",
  beldexInstant: "BELDEX instantâneo",
  beldexDetail: "Recomendado · taxa 0% · BDXUSD ao vivo",
  continuePay: "Continuar para o pagamento",
  sendExactly: "Envie exatamente",
  depositAddress: "Endereço de depósito",
  addressCopied: "Endereço copiado",
  simAddress: "Este endereço é simulado. Confirmar credita o saldo da demo — não há envio na rede.",
  back: "Voltar",
  sentIt: "Já enviei",
  depositStarted: "Depósito iniciado — será creditado em breve",
  withdrawTitle: "Sacar seus fundos",
  withdrawLead: "Saques nesta demo · Mercado ao vivo abaixo",
  chooseMethod: "Escolha o ativo do saque",
  destination: "Endereço de saque",
  destPlaceholder: "Cole o endereço da carteira",
  amount: "Valor",
  enterAmount: "Digite o valor",
  max: "Máx",
  withdrawNow: "Sacar agora",
  withdrawRequested: "Saque solicitado",
  secure: "Processamento seguro",
  secureBody: "Criptografia de 256 bits",
  fast: "Saques rápidos",
  fastBody: "Nesta demo concluem em alguns segundos",
  referralTitle: "Indicações",
  referralLead: "Convide amigos e receba 10% de cada depósito que eles concluírem.",
  referralEarned: "Bônus de indicação recebido",
  yourLink: "Seu link",
  copyLink: "Copiar link",
  linkCopied: "Link de indicação copiado",
  referralFine: "Compartilhar o link não paga. Os 10% entram quando alguém se registra com seu usuário e o depósito se conclui.",
  loginTitle: "Bem-vindo de volta",
  loginLead: "Entre para continuar",
  emailOrUser: "E-mail ou usuário",
  password: "Senha",
  codeLabel: "Código de 6 dígitos",
  remember: "Lembrar de mim",
  forgot: "Esqueceu a senha?",
  notMember: "Ainda não tem conta?",
  signUp: "Criar conta",
  welcomeBack: "Bem-vindo de volta!",
  needCode: "Digite o código de 6 dígitos",
  createTitle: "Criar conta",
  createLead: "Comece hoje",
  username: "Usuário",
  fullname: "Nome completo",
  email: "E-mail",
  phone: "Telefone",
  country: "País",
  selectCountry: "Escolha o país",
  referralOptional: "Usuário de quem indicou (opcional)",
  repeatPassword: "Repita a senha",
  createBtn: "Criar conta",
  haveAccount: "Já tem uma conta?",
  mismatch: "As senhas não coincidem",
  created: "Conta criada — bônus de $3 adicionado",
  checkEmailTitle: "Confira seu e-mail",
  checkEmailBody: "Enviamos um link de confirmação. Abra neste navegador para terminar. Os saldos continuam simulados neste aparelho.",
  accept: "Criar uma conta significa aceitar as notas de Termos, Privacidade e Risco. Os saldos ficam simulados neste aparelho.",
  acceptLead: "Criar uma conta significa aceitar as notas de ",
  termsWord: "Termos",
  privacyWord: "Privacidade",
  acceptAnd: " e ",
  riskWord: "Risco",
  acceptTail: ". Os saldos ficam simulados neste aparelho.",
  shortPass: "Use pelo menos 6 caracteres",
  confirming: "Confirmando…",
  useAccountEmail: "Use o e-mail da conta",
  forgotTitle: "Esqueci a senha",
  forgotLead: "Digite o e-mail da conta. Enviaremos um link. Abra neste navegador e escolha uma senha nova.",
  sendReset: "Continuar",
  setNew: "Definir uma senha nova",
  newPassword: "Nova senha",
  savePassword: "Salvar senha",
  savedIf: "Se essa conta estiver neste aparelho, a nova senha foi salva. Entre para ver o aviso.",
  minDepositLabel: "Depósito mín.",
  maxDepositLabel: "Depósito máx.",
  expectedProfit: "Lucro esperado",
  duration: "Duração",
  days: "dias",
  unlimited: "Ilimitado",
  buyPlan: "Comprar plano",
  openToInvest: "Abrir uma conta",
  plansLead: "Disponível {amount} · Os planos bloqueiam fundos pelo prazo indicado e acumulam lucro diário nesta demo.",
  lockAmount: "Valor a bloquear (USD)",
  close: "Fechar",
  confirm: "Confirmar",
  heldTerm: "Se mantido até o prazo:",
  profitWord: "de lucro",
  returned: "devolvidos",
  selected: "{name} selecionado",
  activated: "{name} ativado",
  swapTitle: "Troca",
  swapLead: "Converta saldo USD e BDX pelo preço ao vivo da Beldex.",
  rate: "Taxa",
  from: "De",
  to: "Para",
  swapNow: "Trocar",
  swapped: "Troca feita",
  usdAvail: "USD disponível {usd} · BDX {bdx}",
  profileTitle: "Perfil",
  saveChanges: "Salvar alterações",
  profileSaved: "Perfil salvo",
  updatePhoto: "Atualizar foto",
  photoUpdated: "Foto de perfil atualizada",
  removePhoto: "Remover foto",
  photoTooBig: "Escolha uma imagem menor",
  passwordBlock: "Senha",
  passwordHint: "Altere a senha salva neste aparelho.",
  currentPassword: "Senha atual",
  updatePassword: "Atualizar senha",
  passwordUpdated: "Senha atualizada",
  settingsLead: "Conta, idioma e segurança.",
  openProfile: "Editar perfil",
  security: "Segurança",
  preferences: "Preferências",
  settingsLang: "Idioma",
  twoFactor: "Autenticação em dois fatores",
  on: "Sim",
  off: "Não",
  twoOn: "Dois fatores ativado",
  twoOff: "Dois fatores desativado",
  session: "Sessão",
  sessionBody: "Somente neste aparelho",
  marketData: "Dados de mercado",
  supportLead: "GLOBAL BELDEX é uma demo educativa. Os gráficos ao vivo vêm da TradingView.",
  supportEmail: "E-mail de suporte",
  supportPhone: "Celular",
  supportAddress: "Endereço",
  messageDesk: "Mensagem ao suporte",
  subject: "Assunto",
  message: "Mensagem",
  send: "Enviar",
  ticketLogged: "Pedido registrado",
  noNotes: "Sem avisos",
  noNotesBody: "Depósitos, planos e indicações aparecem aqui.",
  recent: "Movimentos recentes",
  viewAll: "Ver tudo",
  referralCard: "Link de indicação",
  referralCardLead: "Convide amigos e receba 10% dos depósitos deles",
  quick: "Ações rápidas",
  hello: "Olá",
  totalProfit: "Lucro total",
  bonus: "Bônus",
  referralBonus: "Bônus de indicação",
  withdrawals: "Saques",
  bdxWallet: "Carteira BDX",
  noPlans: "Nenhum plano ativo",
  noPlansBody: "Você ainda não tem investimentos ativos",
  activePlans: "Planos ativos",
  accrued: "acumulado",
  marketOverview: "Visão do mercado",
  sentiment: "Sentimento",
  fear: "Medo",
  greed: "Ganância",
  neutral: "Neutro",
  topMovers: "Maiores variações",
  trending: "Ativos em alta",
  how: "Como funciona",
  howTitle: "Três passos até o painel",
  questions: "Perguntas",
  pending: "pendente",
  completed: "concluído",
  failed: "falhou",
  tx: { deposit: "Depósito", withdraw: "Saque", bonus: "Bônus", plan: "Plano", swap: "Troca", referral: "Indicação" },
  err: {
    FILL: "Preencha os campos obrigatórios",
    NO_ACCOUNT: "Não há conta com esse e-mail ou usuário. Crie uma primeiro.",
    BAD_PASSWORD: "Senha incorreta",
    BAD_CODE: "Código incorreto",
    MIN_DEPOSIT: "O depósito mínimo é $300",
    NEED_METHOD: "Escolha um ativo de saque",
    NEED_ADDRESS: "Digite um endereço de destino",
    NEED_AMOUNT: "Digite um valor",
    INSUFFICIENT: "Saldo insuficiente",
    MIN_PLAN: "O mínimo de {a} é ${b}",
    MAX_PLAN: "O máximo de {a} é ${b}",
    NEED_DEPOSIT: "Saldo disponível insuficiente — deposite primeiro",
    SWAP_SAME: "Escolha dois ativos diferentes",
    BAD_RATE: "Taxa indisponível",
    INSUFFICIENT_USD: "Saldo USD insuficiente",
    INSUFFICIENT_BDX: "Saldo BDX insuficiente",
    NEED_TICKET: "Adicione um assunto e uma mensagem",
    NEED_EMAIL: "Digite seu e-mail ou usuário",
    SHORT_PASSWORD: "Use pelo menos 4 caracteres",
    BAD_CURRENT: "A senha atual está errada",
    BAD_REF: "Esse usuário de indicação não está neste aparelho",
    REF_SELF: "Você não pode usar a própria indicação",
    EMAIL_TAKEN: "E-mail já registrado — entre",
    SIGN_IN: "Entre primeiro",
  },
  note: {
    depositInitTitle: "Depósito iniciado",
    depositInitBody: "Depósito {method} de ${amount} em processamento.",
    depositDoneTitle: "Depósito concluído",
    depositDoneBody: "${amount} já está no saldo disponível.",
    withdrawReqTitle: "Saque solicitado",
    withdrawReqBody: "${amount} via {method} em processamento.",
    withdrawDoneTitle: "Saque concluído",
    withdrawDoneBody: "${amount} via {method} foi enviado.",
    welcomeTitle: "Bônus de boas-vindas creditado",
    welcomeBody: "Bônus de boas-vindas de $3.00 adicionado ao saldo disponível.",
    passwordTitle: "Senha atualizada",
    passwordBody: "Sua senha de acesso foi alterada neste aparelho.",
    twoOnTitle: "Dois fatores ativado",
    twoOnBody: "Seu código da demo é {code}. Digite-o na próxima entrada.",
    twoOffTitle: "Dois fatores desativado",
    twoOffBody: "A entrada não pede mais um código.",
    planTitle: "{name} ativado",
    planBody: "${amount} bloqueados por {duration}.",
    matureTitle: "Plano vencido",
    matureBody: "Principal devolvido. ${amount} de juros desta etapa foram somados ao saldo.",
    dailyTitle: "Juros diários",
    dailyBody: "${amount} de juros diários simulados foram somados ao saldo.",
    swapTitle: "Troca feita",
    referralTitle: "Bônus de indicação",
    referralBody: "{user} depositou. Você ganhou ${amount} (10%).",
    supportTitle: "O suporte respondeu",
    supportBody: "Registramos “{subject}”. Esta demo guarda os pedidos neste aparelho.",
  },
  page: pagePt,
};

const nl = {
  tag: "Geavanceerd beleggingsplatform",
  signIn: "Inloggen",
  openAccount: "Account openen",
  investNow: "Beleggen",
  explore: "Dashboard openen",
  home: "Home",
  history: "Geschiedenis",
  deposit: "Storting",
  withdraw: "Opname",
  menu: "Menu",
  dashboard: "Dashboard",
  markets: "Markten",
  plans: "Plannen",
  swap: "Wisselen",
  profile: "Profiel",
  referrals: "Verwijzingen",
  notifications: "Meldingen",
  settings: "Instellingen",
  support: "Support",
  logout: "Uitloggen",
  available: "Beschikbaar saldo",
  locked: "Geblokkeerd saldo",
  welcome: "Welkom bij GLOBAL BELDEX",
  welcomeBody: "Je dashboard is klaar. Live BDXUSD-markt is actief.",
  others: "Overig",
  transactions: "Transacties",
  liveMarket: "Live markt",
  mainMenu: "Hoofdmenu",
  finance: "Financiën",
  account: "Account",
  ready: "Klaar om te beginnen?",
  readyBody: "Start vanaf $300 · Live BDXUSD-markt",
  startInvesting: "Beginnen",
  plansTitle: "Beleggingsplannen",
  historyTitle: "Transactiegeschiedenis",
  noTx: "Geen transacties",
  noTxBody: "Je {tab}-geschiedenis verschijnt hier",
  depositTitle: "Geld storten",
  depositLead: "Voeg geld toe om te beginnen · Live BDXUSD-markt hieronder",
  amountUsd: "Bedrag (USD)",
  minHint: "Minimale storting $300 · Bijgeschreven in een paar seconden, ook als je deze pagina verlaat",
  payMethod: "Kies een betaalmethode",
  beldexInstant: "BELDEX direct",
  beldexDetail: "Aanbevolen · 0% kosten · Live BDXUSD",
  continuePay: "Doorgaan naar betaling",
  sendExactly: "Stuur precies",
  depositAddress: "Stortingsadres",
  addressCopied: "Adres gekopieerd",
  simAddress: "Dit adres is gesimuleerd. Bevestigen schrijft je demosaldo bij — er is geen on-chain overboeking.",
  back: "Terug",
  sentIt: "Ik heb het verstuurd",
  depositStarted: "Storting gestart — wordt zo bijgeschreven",
  withdrawTitle: "Geld opnemen",
  withdrawLead: "Opnames in deze demo · Live markt hieronder",
  chooseMethod: "Kies het opname-activum",
  destination: "Opnameadres",
  destPlaceholder: "Plak je walletadres",
  amount: "Bedrag",
  enterAmount: "Vul het bedrag in",
  max: "Max",
  withdrawNow: "Nu opnemen",
  withdrawRequested: "Opname aangevraagd",
  secure: "Veilige verwerking",
  secureBody: "256-bit versleuteling",
  fast: "Snelle opnames",
  fastBody: "In deze demo klaar in een paar seconden",
  referralTitle: "Verwijzingen",
  referralLead: "Nodig vrienden uit en ontvang 10% van elke storting die zij afronden.",
  referralEarned: "Verdiende verwijzingsbonus",
  yourLink: "Jouw link",
  copyLink: "Link kopiëren",
  linkCopied: "Verwijzingslink gekopieerd",
  referralFine: "De link delen betaalt niet. De 10% komt binnen wanneer iemand zich registreert met jouw gebruikersnaam en de storting afrondt.",
  loginTitle: "Welkom terug",
  loginLead: "Log in om verder te gaan",
  emailOrUser: "E-mail of gebruikersnaam",
  password: "Wachtwoord",
  codeLabel: "6-cijferige code",
  remember: "Onthoud mij",
  forgot: "Wachtwoord vergeten?",
  notMember: "Nog geen account?",
  signUp: "Registreren",
  welcomeBack: "Welkom terug!",
  needCode: "Vul je 6-cijferige code in",
  createTitle: "Account aanmaken",
  createLead: "Begin vandaag",
  username: "Gebruikersnaam",
  fullname: "Volledige naam",
  email: "E-mail",
  phone: "Telefoon",
  country: "Land",
  selectCountry: "Kies een land",
  referralOptional: "Gebruikersnaam van verwijzer (optioneel)",
  repeatPassword: "Herhaal wachtwoord",
  createBtn: "Account aanmaken",
  haveAccount: "Heb je al een account?",
  mismatch: "Wachtwoorden komen niet overeen",
  created: "Account aangemaakt — $3 bonus toegevoegd",
  checkEmailTitle: "Controleer je e-mail",
  checkEmailBody: "We hebben een bevestigingslink gestuurd. Open die in deze browser om af te ronden. Saldi blijven gesimuleerd op dit apparaat.",
  accept: "Een account aanmaken betekent dat je de notities Voorwaarden, Privacy en Risico accepteert. Saldi blijven gesimuleerd op dit apparaat.",
  acceptLead: "Een account aanmaken betekent dat je de notities ",
  termsWord: "Voorwaarden",
  privacyWord: "Privacy",
  acceptAnd: " en ",
  riskWord: "Risico",
  acceptTail: " accepteert. Saldi blijven gesimuleerd op dit apparaat.",
  shortPass: "Gebruik minstens 6 tekens",
  confirming: "Bevestigen…",
  useAccountEmail: "Gebruik het e-mailadres van het account",
  forgotTitle: "Wachtwoord vergeten",
  forgotLead: "Vul het e-mailadres van je account in. We sturen een link. Open die in deze browser en kies een nieuw wachtwoord.",
  sendReset: "Doorgaan",
  setNew: "Nieuw wachtwoord instellen",
  newPassword: "Nieuw wachtwoord",
  savePassword: "Wachtwoord opslaan",
  savedIf: "Als dat account op dit apparaat staat, is het nieuwe wachtwoord opgeslagen. Log in om de melding te zien.",
  minDepositLabel: "Min. storting",
  maxDepositLabel: "Max. storting",
  expectedProfit: "Verwachte winst",
  duration: "Duur",
  days: "dagen",
  unlimited: "Onbeperkt",
  buyPlan: "Plan kopen",
  openToInvest: "Account openen",
  plansLead: "Beschikbaar {amount} · Plannen blokkeren geld voor de genoemde termijn en tellen dagelijkse winst op in deze demo.",
  lockAmount: "Te blokkeren bedrag (USD)",
  close: "Sluiten",
  confirm: "Bevestigen",
  heldTerm: "Als je het tot het einde aanhoudt:",
  profitWord: "winst",
  returned: "terug",
  selected: "{name} geselecteerd",
  activated: "{name} geactiveerd",
  swapTitle: "Wisselen",
  swapLead: "Wissel USD-saldo en BDX tegen de live Beldex-koers.",
  rate: "Koers",
  from: "Van",
  to: "Naar",
  swapNow: "Nu wisselen",
  swapped: "Wissel uitgevoerd",
  usdAvail: "USD beschikbaar {usd} · BDX {bdx}",
  profileTitle: "Profiel",
  saveChanges: "Wijzigingen opslaan",
  profileSaved: "Profiel opgeslagen",
  updatePhoto: "Foto bijwerken",
  photoUpdated: "Profielfoto bijgewerkt",
  removePhoto: "Foto verwijderen",
  photoTooBig: "Kies een kleinere afbeelding",
  passwordBlock: "Wachtwoord",
  passwordHint: "Wijzig het wachtwoord dat op dit apparaat staat.",
  currentPassword: "Huidig wachtwoord",
  updatePassword: "Wachtwoord bijwerken",
  passwordUpdated: "Wachtwoord bijgewerkt",
  settingsLead: "Account, taal en beveiliging.",
  openProfile: "Profiel bewerken",
  security: "Beveiliging",
  preferences: "Voorkeuren",
  settingsLang: "Taal",
  twoFactor: "Tweestapsverificatie",
  on: "Aan",
  off: "Uit",
  twoOn: "Tweestapsverificatie aan",
  twoOff: "Tweestapsverificatie uit",
  session: "Sessie",
  sessionBody: "Alleen op dit apparaat",
  marketData: "Marktgegevens",
  supportLead: "GLOBAL BELDEX is een educatieve demo. Live grafieken komen van TradingView.",
  supportEmail: "Support-e-mail",
  supportPhone: "Mobiel",
  supportAddress: "Adres",
  messageDesk: "Bericht aan support",
  subject: "Onderwerp",
  message: "Bericht",
  send: "Versturen",
  ticketLogged: "Ticket opgeslagen",
  noNotes: "Geen meldingen",
  noNotesBody: "Stortingen, plannen en verwijzingen verschijnen hier.",
  recent: "Recente transacties",
  viewAll: "Alles bekijken",
  referralCard: "Verwijzingslink",
  referralCardLead: "Nodig vrienden uit en ontvang 10% van hun stortingen",
  quick: "Snelle acties",
  hello: "Hallo",
  totalProfit: "Totale winst",
  bonus: "Bonus",
  referralBonus: "Verwijzingsbonus",
  withdrawals: "Opnames",
  bdxWallet: "BDX-wallet",
  noPlans: "Geen actieve plannen",
  noPlansBody: "Je hebt nog geen actieve beleggingen",
  activePlans: "Actieve plannen",
  accrued: "opgebouwd",
  marketOverview: "Marktoverzicht",
  sentiment: "Sentiment",
  fear: "Angst",
  greed: "Hebzucht",
  neutral: "Neutraal",
  topMovers: "Grootste bewegers",
  trending: "Trending activa",
  how: "Hoe het werkt",
  howTitle: "Drie stappen naar het dashboard",
  questions: "Vragen",
  pending: "in behandeling",
  completed: "voltooid",
  failed: "mislukt",
  tx: { deposit: "Storting", withdraw: "Opname", bonus: "Bonus", plan: "Plan", swap: "Wissel", referral: "Verwijzing" },
  err: {
    FILL: "Vul de verplichte velden in",
    NO_ACCOUNT: "Geen account voor dat e-mailadres of die gebruikersnaam. Maak er eerst een.",
    BAD_PASSWORD: "Onjuist wachtwoord",
    BAD_CODE: "Onjuiste code",
    MIN_DEPOSIT: "Minimale storting is $300",
    NEED_METHOD: "Kies een opname-activum",
    NEED_ADDRESS: "Vul een bestemmingsadres in",
    NEED_AMOUNT: "Vul een bedrag in",
    INSUFFICIENT: "Onvoldoende saldo",
    MIN_PLAN: "Minimum voor {a} is ${b}",
    MAX_PLAN: "Maximum voor {a} is ${b}",
    NEED_DEPOSIT: "Onvoldoende beschikbaar saldo — stort eerst",
    SWAP_SAME: "Kies twee verschillende activa",
    BAD_RATE: "Koers niet beschikbaar",
    INSUFFICIENT_USD: "Onvoldoende USD-saldo",
    INSUFFICIENT_BDX: "Onvoldoende BDX-saldo",
    NEED_TICKET: "Voeg een onderwerp en een bericht toe",
    NEED_EMAIL: "Vul je e-mail of gebruikersnaam in",
    SHORT_PASSWORD: "Gebruik minstens 4 tekens",
    BAD_CURRENT: "Het huidige wachtwoord klopt niet",
    BAD_REF: "Die verwijzende gebruikersnaam staat niet op dit apparaat",
    REF_SELF: "Je kunt je eigen verwijzing niet gebruiken",
    EMAIL_TAKEN: "E-mail al geregistreerd — log in",
    SIGN_IN: "Log eerst in",
  },
  note: {
    depositInitTitle: "Storting gestart",
    depositInitBody: "{method}-storting van ${amount} wordt verwerkt.",
    depositDoneTitle: "Storting voltooid",
    depositDoneBody: "${amount} staat nu op je beschikbare saldo.",
    withdrawReqTitle: "Opname aangevraagd",
    withdrawReqBody: "${amount} via {method} wordt verwerkt.",
    withdrawDoneTitle: "Opname voltooid",
    withdrawDoneBody: "${amount} via {method} is verstuurd.",
    welcomeTitle: "Welkomstbonus bijgeschreven",
    welcomeBody: "Welkomstbonus van $3.00 toegevoegd aan je beschikbare saldo.",
    passwordTitle: "Wachtwoord bijgewerkt",
    passwordBody: "Je inlogwachtwoord is op dit apparaat gewijzigd.",
    twoOnTitle: "Tweestapsverificatie aan",
    twoOnBody: "Je democode is {code}. Vul die in bij de volgende login.",
    twoOffTitle: "Tweestapsverificatie uit",
    twoOffBody: "Inloggen vraagt geen code meer.",
    planTitle: "{name} geactiveerd",
    planBody: "${amount} geblokkeerd voor {duration}.",
    matureTitle: "Plan afgelopen",
    matureBody: "Inleg terug. ${amount} rente van deze stap is aan je saldo toegevoegd.",
    dailyTitle: "Dagelijkse rente",
    dailyBody: "${amount} gesimuleerde dagelijkse rente is aan je saldo toegevoegd.",
    swapTitle: "Wissel uitgevoerd",
    referralTitle: "Verwijzingsbonus",
    referralBody: "{user} heeft gestort. Je verdiende ${amount} (10%).",
    supportTitle: "Support heeft geantwoord",
    supportBody: "We hebben “{subject}” genoteerd. Deze demo bewaart tickets op je apparaat.",
  },
  page: pageNl,
};


// Asian language packs. These override the English base dictionary, so newly
// added UI keys remain safely readable until a native translation is supplied.
const yue = {
  tag: "進階投資平台", signIn: "登入", openAccount: "開立帳戶", investNow: "立即投資",
  explore: "探索控制面板", home: "首頁", history: "歷史", deposit: "存款", withdraw: "提款",
  menu: "選單", dashboard: "控制面板", markets: "市場", plans: "投資計劃", swap: "兌換",
  profile: "個人資料", referrals: "推薦", notifications: "通知", settings: "設定", support: "支援",
  logout: "登出", available: "可用餘額", locked: "鎖定餘額", welcome: "歡迎來到 GLOBAL BELDEX",
  welcomeBody: "你的進階投資控制面板已準備就緒。BDXUSD 即時市場已啟用。",
  others: "其他", transactions: "交易", liveMarket: "即時市場", mainMenu: "主選單",
  finance: "財務", account: "帳戶", ready: "準備好增長財富？", startInvesting: "開始投資",
  plansTitle: "投資計劃", historyTitle: "交易歷史", noTx: "暫無交易", depositTitle: "存入資金",
  amountUsd: "金額（USD）", payMethod: "選擇付款方式", back: "返回", sentIt: "我已完成轉賬",
  withdrawTitle: "提取資金", chooseMethod: "選擇提款資產", destination: "提款地址",
  amount: "金額", enterAmount: "輸入金額", max: "最大", withdrawNow: "立即提款",
  withdrawRequested: "提款已申請", secure: "安全處理", fast: "快速提款",
  referralTitle: "推薦", referralLead: "邀請朋友，賺取他們完成存款的 10%。",
  yourLink: "你的連結", copyLink: "複製連結", linkCopied: "推薦連結已複製",
  loginTitle: "歡迎回來", loginLead: "登入以繼續投資", emailOrUser: "電郵或用戶名稱",
  password: "密碼", remember: "記住我", forgot: "忘記密碼？", notMember: "還未成為會員？",
  signUp: "註冊", welcomeBack: "歡迎回來！", createTitle: "建立帳戶", createLead: "立即開始你的投資旅程",
  username: "用戶名稱", fullname: "全名", email: "電郵", phone: "電話", country: "國家",
  selectCountry: "選擇國家", repeatPassword: "再次輸入密碼", createBtn: "建立帳戶",
  haveAccount: "已經有帳戶？", mismatch: "兩次密碼不一致", created: "帳戶已建立 — 已加入 $3 獎勵",
  forgotTitle: "忘記密碼", sendReset: "繼續", setNew: "設定新密碼", newPassword: "新密碼",
  savePassword: "儲存密碼", minDepositLabel: "最低存款", maxDepositLabel: "最高存款",
  expectedProfit: "預期收益", duration: "期限", days: "天", unlimited: "不限", buyPlan: "購買計劃",
  openToInvest: "開立帳戶", lockAmount: "鎖定金額（USD）", close: "關閉", confirm: "確認",
  heldTerm: "持有至期限：", profitWord: "收益", returned: "返還", selected: "{name} 已選擇",
  activated: "{name} 已啟用", swapTitle: "兌換", rate: "匯率", from: "由", to: "至",
  swapNow: "立即兌換", swapped: "兌換已完成", profileTitle: "個人資料", saveChanges: "儲存變更",
  profileSaved: "個人資料已儲存", updatePhoto: "更新照片", removePhoto: "移除照片",
  passwordBlock: "密碼", currentPassword: "目前密碼", updatePassword: "更新密碼", passwordUpdated: "密碼已更新",
  settingsLead: "帳戶、語言及安全性。", openProfile: "編輯個人資料", security: "安全性",
  preferences: "偏好設定", settingsLang: "語言", session: "工作階段", sessionBody: "管理目前裝置",
  marketData: "市場數據", supportEmail: "支援電郵", supportPhone: "手機", supportAddress: "地址",
  messageDesk: "聯絡支援", subject: "主題", message: "訊息", send: "發送", ticketLogged: "支援工單已建立",
  noNotes: "沒有通知", noNotesBody: "存款、計劃及推薦通知會顯示在這裡。",
  recent: "最近交易", viewAll: "查看全部", quick: "快速操作", hello: "你好", totalProfit: "總收益",
  bonus: "獎勵", referralBonus: "推薦獎勵", withdrawals: "提款", bdxWallet: "BDX 錢包",
  noPlans: "沒有活躍計劃", activePlans: "活躍計劃", accrued: "已累積", marketOverview: "市場概覽",
  sentiment: "市場情緒", fear: "恐慌", greed: "貪婪", neutral: "中性", topMovers: "升跌幅榜",
  trending: "熱門資產", how: "運作方式", questions: "常見問題", pending: "處理中", completed: "已完成", failed: "失敗",
  realTimeAlerts: "即時通知", liveAccountUpdates: "即時帳戶更新", notificationSound: "通知聲音",
  browserNotifications: "瀏覽器通知", enable: "啟用",
  tx: { deposit: "存款", withdraw: "提款", bonus: "獎勵", plan: "計劃", swap: "兌換", referral: "推薦" },
  page: {
    heroTitle: "以遠見建立財富。", heroSub: "今天投資，成就明天。", registerNow: "立即註冊",
    conditionsCharges: "投資條件及費用", platformsLead: "GLOBAL BELDEX 為不同程度的投資者提供多元化平台。",
    goodCompany: "你與優秀投資者同行", compareTitle: "加密貨幣價格比較", minFunding: "最低資金",
    openingAccount: "開立帳戶流程", liveMarketTv: "BDXUSD 即時市場 - TradingView 提供",
    trackBdx: "追蹤 BDXUSD", featured: "精選產品", trustTitle: "值得信賴的強大平台",
    safeTitle: "安全可靠", execTitle: "即時執行", awardTitle: "屢獲殊榮", liveOverview: "BDXUSD 即時概覽",
    accountOverview: "帳戶概覽", viewChart: "查看圖表", liveBdx: "BDXUSD 即時市場",
    livePrice: "即時市場價格", marketWord: "市場", liveWord: "即時", calculator: "金額計算器",
    errorTitle: "發生錯誤", legalTitle: "條款、私隱及風險"
  }
};

const zh = {
  tag: "先进投资平台", signIn: "登录", openAccount: "开立账户", investNow: "立即投资",
  explore: "查看控制面板", home: "首页", history: "历史记录", deposit: "存款", withdraw: "提现",
  menu: "菜单", dashboard: "控制面板", markets: "市场", plans: "投资计划", swap: "兑换",
  profile: "个人资料", referrals: "推荐", notifications: "通知", settings: "设置", support: "支持",
  logout: "退出登录", available: "可用余额", locked: "锁定余额", welcome: "欢迎来到 GLOBAL BELDEX",
  welcomeBody: "你的高级投资控制面板已准备就绪。BDXUSD 实时市场已启用。",
  others: "其他", transactions: "交易", liveMarket: "实时市场", mainMenu: "主菜单", finance: "财务", account: "账户",
  ready: "准备好增长财富？", startInvesting: "开始投资", plansTitle: "投资计划", historyTitle: "交易历史",
  noTx: "暂无交易", depositTitle: "存入资金", amountUsd: "金额（USD）", payMethod: "选择付款方式",
  back: "返回", sentIt: "我已完成转账", withdrawTitle: "提取资金", chooseMethod: "选择提现资产",
  destination: "提现地址", amount: "金额", enterAmount: "输入金额", max: "最大", withdrawNow: "立即提现",
  withdrawRequested: "提现申请已提交", secure: "安全处理", fast: "快速提现", referralTitle: "推荐",
  referralLead: "邀请朋友并获得他们完成存款的 10%。", yourLink: "你的链接", copyLink: "复制链接",
  linkCopied: "推荐链接已复制", loginTitle: "欢迎回来", loginLead: "登录以继续投资", emailOrUser: "邮箱或用户名",
  password: "密码", remember: "记住我", forgot: "忘记密码？", notMember: "还不是会员？", signUp: "注册",
  welcomeBack: "欢迎回来！", createTitle: "创建账户", createLead: "今天开始你的投资之旅", username: "用户名",
  fullname: "姓名", email: "邮箱", phone: "电话", country: "国家", selectCountry: "选择国家",
  repeatPassword: "再次输入密码", createBtn: "创建账户", haveAccount: "已有账户？", mismatch: "两次密码不一致",
  created: "账户已创建 — 已添加 $3 奖励", forgotTitle: "忘记密码", sendReset: "继续", setNew: "设置新密码",
  newPassword: "新密码", savePassword: "保存密码", minDepositLabel: "最低存款", maxDepositLabel: "最高存款",
  expectedProfit: "预期收益", duration: "期限", days: "天", unlimited: "不限", buyPlan: "购买计划",
  openToInvest: "开立账户", lockAmount: "锁定金额（USD）", close: "关闭", confirm: "确认",
  heldTerm: "持有至期限：", profitWord: "收益", returned: "返还", selected: "{name} 已选择", activated: "{name} 已启用",
  swapTitle: "兑换", rate: "汇率", from: "从", to: "到", swapNow: "立即兑换", swapped: "兑换完成",
  profileTitle: "个人资料", saveChanges: "保存更改", profileSaved: "个人资料已保存", updatePhoto: "更新照片",
  removePhoto: "删除照片", passwordBlock: "密码", currentPassword: "当前密码", updatePassword: "更新密码",
  passwordUpdated: "密码已更新", settingsLead: "账户、语言和安全。", openProfile: "编辑资料", security: "安全",
  preferences: "偏好设置", settingsLang: "语言", session: "会话", sessionBody: "管理当前设备",
  marketData: "市场数据", supportEmail: "客服邮箱", supportPhone: "手机", supportAddress: "地址",
  messageDesk: "联系支持", subject: "主题", message: "消息", send: "发送", ticketLogged: "支持请求已记录",
  noNotes: "没有通知", noNotesBody: "存款、计划和推荐通知会显示在这里。", recent: "最近交易", viewAll: "查看全部",
  quick: "快捷操作", hello: "你好", totalProfit: "总收益", bonus: "奖励", referralBonus: "推荐奖励", withdrawals: "提现",
  bdxWallet: "BDX 钱包", noPlans: "没有活跃计划", activePlans: "活跃计划", accrued: "已累计", marketOverview: "市场概览",
  sentiment: "市场情绪", fear: "恐惧", greed: "贪婪", neutral: "中性", topMovers: "涨跌幅", trending: "热门资产",
  how: "运作方式", questions: "常见问题", pending: "处理中", completed: "已完成", failed: "失败",
  realTimeAlerts: "实时通知", liveAccountUpdates: "实时账户更新", notificationSound: "通知声音",
  browserNotifications: "浏览器通知", enable: "启用",
  tx: { deposit: "存款", withdraw: "提现", bonus: "奖励", plan: "计划", swap: "兑换", referral: "推荐" },
  page: {
    heroTitle: "以远见创造财富。", heroSub: "今天投资，成就明天。", registerNow: "立即注册",
    conditionsCharges: "投资条件与费用", platformsLead: "GLOBAL BELDEX 为不同层级的投资者提供多元化平台。",
    goodCompany: "你与优秀投资者同行", compareTitle: "加密货币价格比较", minFunding: "最低资金",
    openingAccount: "开户流程", liveMarketTv: "BDXUSD 实时市场 - TradingView 提供", trackBdx: "追踪 BDXUSD",
    featured: "精选产品", trustTitle: "值得信赖的强大平台", safeTitle: "安全可靠", execTitle: "即时执行",
    awardTitle: "屡获殊荣", liveOverview: "BDXUSD 实时概览", accountOverview: "账户概览", viewChart: "查看图表",
    liveBdx: "BDXUSD 实时市场", livePrice: "实时市场价格", marketWord: "市场", liveWord: "实时",
    calculator: "金额计算器", errorTitle: "发生错误", legalTitle: "条款、隐私与风险"
  }
};

const hi = {
  tag: "उन्नत निवेश प्लेटफ़ॉर्म", signIn: "साइन इन", openAccount: "खाता खोलें", investNow: "अभी निवेश करें",
  explore: "डैशबोर्ड देखें", home: "होम", history: "इतिहास", deposit: "जमा", withdraw: "निकासी",
  menu: "मेन्यू", dashboard: "डैशबोर्ड", markets: "मार्केट", plans: "निवेश योजनाएँ", swap: "स्वैप",
  profile: "प्रोफ़ाइल", referrals: "रेफ़रल", notifications: "सूचनाएँ", settings: "सेटिंग्स", support: "सहायता",
  logout: "लॉग आउट", available: "उपलब्ध शेष", locked: "लॉक्ड बैलेंस", welcome: "GLOBAL BELDEX में आपका स्वागत है",
  welcomeBody: "आपका उन्नत निवेश डैशबोर्ड तैयार है। लाइव BDXUSD मार्केट सक्रिय है।", others: "अन्य",
  transactions: "लेन-देन", liveMarket: "लाइव मार्केट", mainMenu: "मुख्य मेन्यू", finance: "वित्त", account: "खाता",
  ready: "बढ़ने के लिए तैयार हैं?", startInvesting: "निवेश शुरू करें", plansTitle: "निवेश योजनाएँ",
  historyTitle: "लेन-देन इतिहास", noTx: "कोई लेन-देन नहीं", depositTitle: "फंड जमा करें", amountUsd: "राशि (USD)",
  payMethod: "भुगतान विधि चुनें", back: "वापस", sentIt: "मैंने भेज दिया", withdrawTitle: "फंड निकालें",
  chooseMethod: "निकासी एसेट चुनें", destination: "निकासी पता", amount: "राशि", enterAmount: "राशि दर्ज करें",
  max: "अधिकतम", withdrawNow: "अभी निकालें", withdrawRequested: "निकासी अनुरोध भेजा गया", secure: "सुरक्षित प्रोसेसिंग",
  fast: "तेज़ निकासी", referralTitle: "रेफ़रल", referralLead: "दोस्तों को आमंत्रित करें और उनके पूरे किए गए जमा पर 10% कमाएँ।",
  yourLink: "आपका लिंक", copyLink: "लिंक कॉपी करें", linkCopied: "रेफ़रल लिंक कॉपी हो गया", loginTitle: "वापसी पर स्वागत है",
  loginLead: "निवेश जारी रखने के लिए साइन इन करें", emailOrUser: "ईमेल या यूज़रनेम", password: "पासवर्ड",
  remember: "मुझे याद रखें", forgot: "पासवर्ड भूल गए?", notMember: "अभी सदस्य नहीं हैं?", signUp: "साइन अप",
  welcomeBack: "वापसी पर स्वागत है!", createTitle: "खाता बनाएँ", createLead: "आज अपनी निवेश यात्रा शुरू करें", username: "यूज़रनेम",
  fullname: "पूरा नाम", email: "ईमेल", phone: "फ़ोन", country: "देश", selectCountry: "देश चुनें",
  repeatPassword: "पासवर्ड दोहराएँ", createBtn: "खाता बनाएँ", haveAccount: "पहले से खाता है?", mismatch: "पासवर्ड मेल नहीं खाते",
  created: "खाता बन गया — $3 बोनस जोड़ा गया", forgotTitle: "पासवर्ड भूल गए", sendReset: "जारी रखें", setNew: "नया पासवर्ड सेट करें",
  newPassword: "नया पासवर्ड", savePassword: "पासवर्ड सहेजें", minDepositLabel: "न्यूनतम जमा", maxDepositLabel: "अधिकतम जमा",
  expectedProfit: "अपेक्षित लाभ", duration: "अवधि", days: "दिन", unlimited: "असीमित", buyPlan: "योजना खरीदें",
  openToInvest: "खाता खोलें", lockAmount: "लॉक करने की राशि (USD)", close: "बंद करें", confirm: "पुष्टि करें",
  heldTerm: "अवधि तक रखने पर:", profitWord: "लाभ", returned: "वापस", selected: "{name} चुना गया", activated: "{name} सक्रिय",
  swapTitle: "स्वैप", rate: "दर", from: "से", to: "तक", swapNow: "अभी स्वैप करें", swapped: "स्वैप पूरा हुआ",
  profileTitle: "प्रोफ़ाइल", saveChanges: "बदलाव सहेजें", profileSaved: "प्रोफ़ाइल सहेजी गई", updatePhoto: "फ़ोटो अपडेट करें",
  removePhoto: "फ़ोटो हटाएँ", passwordBlock: "पासवर्ड", currentPassword: "वर्तमान पासवर्ड", updatePassword: "पासवर्ड अपडेट करें",
  passwordUpdated: "पासवर्ड अपडेट हुआ", settingsLead: "खाता, भाषा और सुरक्षा।", openProfile: "प्रोफ़ाइल संपादित करें",
  security: "सुरक्षा", preferences: "प्राथमिकताएँ", settingsLang: "भाषा", session: "सेशन", sessionBody: "सक्रिय डिवाइस प्रबंधित करें",
  marketData: "मार्केट डेटा", supportEmail: "सपोर्ट ईमेल", supportPhone: "मोबाइल", supportAddress: "पता",
  messageDesk: "सपोर्ट को संदेश", subject: "विषय", message: "संदेश", send: "भेजें", ticketLogged: "सपोर्ट टिकट दर्ज हुआ",
  noNotes: "कोई सूचना नहीं", noNotesBody: "जमा, योजनाएँ और रेफ़रल यहाँ दिखाई देंगे।", recent: "हाल के लेन-देन", viewAll: "सभी देखें",
  quick: "त्वरित कार्रवाइयाँ", hello: "नमस्ते", totalProfit: "कुल लाभ", bonus: "बोनस", referralBonus: "रेफ़रल बोनस",
  withdrawals: "निकासी", bdxWallet: "BDX वॉलेट", noPlans: "कोई सक्रिय योजना नहीं", activePlans: "सक्रिय योजनाएँ",
  accrued: "संचित", marketOverview: "मार्केट अवलोकन", sentiment: "मार्केट भावना", fear: "भय", greed: "लालच",
  neutral: "तटस्थ", topMovers: "शीर्ष बदलाव", trending: "ट्रेंडिंग एसेट", how: "कैसे काम करता है", questions: "प्रश्न",
  pending: "लंबित", completed: "पूर्ण", failed: "विफल", realTimeAlerts: "रियल-टाइम अलर्ट",
  liveAccountUpdates: "लाइव अकाउंट अपडेट", notificationSound: "नोटिफिकेशन ध्वनि", browserNotifications: "ब्राउज़र सूचनाएँ",
  enable: "सक्षम करें",
  tx: { deposit: "जमा", withdraw: "निकासी", bonus: "बोनस", plan: "योजना", swap: "स्वैप", referral: "रेफ़रल" },
  page: {
    heroTitle: "दूरदृष्टि के साथ संपत्ति बनाएँ।", heroSub: "आज निवेश करें, कल बनाएँ।", registerNow: "अभी रजिस्टर करें",
    conditionsCharges: "निवेश शर्तें और शुल्क", platformsLead: "GLOBAL BELDEX सभी स्तरों के निवेशकों के लिए कई प्लेटफ़ॉर्म प्रदान करता है।",
    goodCompany: "आप अच्छे साथियों के बीच हैं", compareTitle: "क्रिप्टो मूल्य तुलना", minFunding: "न्यूनतम फंडिंग",
    openingAccount: "खाता खोलने की प्रक्रिया", liveMarketTv: "लाइव BDXUSD मार्केट - TradingView द्वारा",
    trackBdx: "BDXUSD ट्रैक करें", featured: "विशेष उत्पाद", trustTitle: "विश्वसनीय शक्तिशाली प्लेटफ़ॉर्म",
    safeTitle: "सुरक्षित और संरक्षित", execTitle: "तुरंत निष्पादन", awardTitle: "पुरस्कार विजेता",
    liveOverview: "लाइव BDXUSD अवलोकन", accountOverview: "खाता अवलोकन", viewChart: "चार्ट देखें",
    liveBdx: "लाइव BDXUSD", livePrice: "लाइव मार्केट मूल्य", marketWord: "मार्केट", liveWord: "लाइव",
    calculator: "राशि कैलकुलेटर", errorTitle: "कुछ गलत हो गया", legalTitle: "शर्तें, गोपनीयता और जोखिम"
  }
};

const ta = {
  tag: "மேம்பட்ட முதலீட்டு தளம்", signIn: "உள்நுழைக", openAccount: "கணக்கைத் திற", investNow: "இப்போது முதலீடு செய்",
  explore: "டாஷ்போர்டைப் பார்க்க", home: "முகப்பு", history: "வரலாறு", deposit: "வைப்பு", withdraw: "திரும்பப் பெறுதல்",
  menu: "மெனு", dashboard: "டாஷ்போர்டு", markets: "சந்தைகள்", plans: "முதலீட்டுத் திட்டங்கள்", swap: "மாற்று",
  profile: "சுயவிவரம்", referrals: "பரிந்துரைகள்", notifications: "அறிவிப்புகள்", settings: "அமைப்புகள்", support: "ஆதரவு",
  logout: "வெளியேறு", available: "கிடைக்கும் இருப்பு", locked: "பூட்டிய இருப்பு", welcome: "GLOBAL BELDEX-க்கு வரவேற்கிறோம்",
  welcomeBody: "உங்கள் மேம்பட்ட முதலீட்டு டாஷ்போர்டு தயாராக உள்ளது. நேரடி BDXUSD சந்தை செயல்பாட்டில் உள்ளது.",
  others: "மற்றவை", transactions: "பரிவர்த்தனைகள்", liveMarket: "நேரடி சந்தை", mainMenu: "முதன்மை மெனு",
  finance: "நிதி", account: "கணக்கு", ready: "வளரத் தயாரா?", startInvesting: "முதலீட்டைத் தொடங்கு",
  plansTitle: "முதலீட்டுத் திட்டங்கள்", historyTitle: "பரிவர்த்தனை வரலாறு", noTx: "பரிவர்த்தனைகள் இல்லை",
  depositTitle: "நிதி வைப்பு", amountUsd: "தொகை (USD)", payMethod: "கட்டண முறையைத் தேர்வு செய்",
  back: "பின்", sentIt: "நான் அனுப்பிவிட்டேன்", withdrawTitle: "நிதியைத் திரும்பப் பெறு",
  chooseMethod: "திரும்பப் பெறும் சொத்தைத் தேர்வு செய்", destination: "திரும்பப் பெறும் முகவரி",
  amount: "தொகை", enterAmount: "தொகையை உள்ளிடுக", max: "அதிகபட்சம்", withdrawNow: "இப்போது திரும்பப் பெறு",
  withdrawRequested: "திரும்பப் பெறுதல் கோரப்பட்டது", secure: "பாதுகாப்பான செயலாக்கம்", fast: "வேகமான திரும்பப் பெறுதல்",
  referralTitle: "பரிந்துரைகள்", referralLead: "நண்பர்களை அழைத்து, அவர்கள் நிறைவு செய்யும் ஒவ்வொரு வைப்பிலும் 10% சம்பாதிக்கவும்.",
  yourLink: "உங்கள் இணைப்பு", copyLink: "இணைப்பை நகலெடு", linkCopied: "பரிந்துரை இணைப்பு நகலெடுக்கப்பட்டது",
  loginTitle: "மீண்டும் வரவேற்கிறோம்", loginLead: "முதலீட்டைத் தொடர உள்நுழைக", emailOrUser: "மின்னஞ்சல் அல்லது பயனர்பெயர்",
  password: "கடவுச்சொல்", remember: "என்னை நினைவில் கொள்", forgot: "கடவுச்சொல் மறந்துவிட்டதா?", notMember: "இன்னும் உறுப்பினர் இல்லையா?",
  signUp: "பதிவு செய்", welcomeBack: "மீண்டும் வரவேற்கிறோம்!", createTitle: "கணக்கை உருவாக்கு", createLead: "இன்றே உங்கள் முதலீட்டு பயணத்தைத் தொடங்குங்கள்",
  username: "பயனர்பெயர்", fullname: "முழுப் பெயர்", email: "மின்னஞ்சல்", phone: "தொலைபேசி", country: "நாடு",
  selectCountry: "நாட்டைத் தேர்வு செய்", repeatPassword: "கடவுச்சொல்லை மீண்டும் உள்ளிடுக", createBtn: "கணக்கை உருவாக்கு",
  haveAccount: "ஏற்கனவே கணக்கு உள்ளதா?", mismatch: "கடவுச்சொற்கள் பொருந்தவில்லை", created: "கணக்கு உருவாக்கப்பட்டது — $3 போனஸ் சேர்க்கப்பட்டது",
  forgotTitle: "கடவுச்சொல் மறந்துவிட்டது", sendReset: "தொடரவும்", setNew: "புதிய கடவுச்சொல்லை அமை", newPassword: "புதிய கடவுச்சொல்",
  savePassword: "கடவுச்சொல்லைச் சேமி", minDepositLabel: "குறைந்தபட்ச வைப்பு", maxDepositLabel: "அதிகபட்ச வைப்பு",
  expectedProfit: "எதிர்பார்க்கப்படும் லாபம்", duration: "காலம்", days: "நாட்கள்", unlimited: "வரம்பற்றது", buyPlan: "திட்டத்தை வாங்கு",
  openToInvest: "கணக்கைத் திற", lockAmount: "பூட்ட வேண்டிய தொகை (USD)", close: "மூடு", confirm: "உறுதிசெய்",
  heldTerm: "காலம் வரை வைத்திருந்தால்:", profitWord: "லாபம்", returned: "திருப்பித் தரப்பட்டது", selected: "{name} தேர்ந்தெடுக்கப்பட்டது",
  activated: "{name} செயல்படுத்தப்பட்டது", swapTitle: "மாற்று", rate: "விகிதம்", from: "இருந்து", to: "க்கு",
  swapNow: "இப்போது மாற்று", swapped: "மாற்று முடிந்தது", profileTitle: "சுயவிவரம்", saveChanges: "மாற்றங்களைச் சேமி",
  profileSaved: "சுயவிவரம் சேமிக்கப்பட்டது", updatePhoto: "புகைப்படத்தைப் புதுப்பி", removePhoto: "புகைப்படத்தை அகற்று",
  passwordBlock: "கடவுச்சொல்", currentPassword: "தற்போதைய கடவுச்சொல்", updatePassword: "கடவுச்சொல்லைப் புதுப்பி",
  passwordUpdated: "கடவுச்சொல் புதுப்பிக்கப்பட்டது", settingsLead: "கணக்கு, மொழி மற்றும் பாதுகாப்பு.", openProfile: "சுயவிவரத்தைத் திருத்து",
  security: "பாதுகாப்பு", preferences: "விருப்பங்கள்", settingsLang: "மொழி", session: "அமர்வு", sessionBody: "செயலில் உள்ள சாதனங்களை நிர்வகி",
  marketData: "சந்தைத் தரவு", supportEmail: "ஆதரவு மின்னஞ்சல்", supportPhone: "மொபைல்", supportAddress: "முகவரி",
  messageDesk: "ஆதரவுக்கு செய்தி", subject: "தலைப்பு", message: "செய்தி", send: "அனுப்பு", ticketLogged: "ஆதரவு கோரிக்கை பதிவு செய்யப்பட்டது",
  noNotes: "அறிவிப்புகள் இல்லை", noNotesBody: "வைப்புகள், திட்டங்கள் மற்றும் பரிந்துரைகள் இங்கே தோன்றும்.", recent: "சமீபத்திய பரிவர்த்தனைகள்",
  viewAll: "அனைத்தையும் காண்க", quick: "விரைவு செயல்கள்", hello: "வணக்கம்", totalProfit: "மொத்த லாபம்", bonus: "போனஸ்",
  referralBonus: "பரிந்துரை போனஸ்", withdrawals: "திரும்பப் பெறுதல்கள்", bdxWallet: "BDX வாலெட்", noPlans: "செயலில் உள்ள திட்டங்கள் இல்லை",
  activePlans: "செயலில் உள்ள திட்டங்கள்", accrued: "சேர்ந்தது", marketOverview: "சந்தை மேலோட்டம்", sentiment: "சந்தை உணர்வு",
  fear: "பயம்", greed: "பேராசை", neutral: "நடுநிலை", topMovers: "முக்கிய மாற்றங்கள்", trending: "பிரபல சொத்துகள்",
  how: "எப்படி செயல்படுகிறது", questions: "கேள்விகள்", pending: "நிலுவையில்", completed: "முடிந்தது", failed: "தோல்வி",
  realTimeAlerts: "நேரடி அறிவிப்புகள்", liveAccountUpdates: "நேரடி கணக்கு புதுப்பிப்புகள்", notificationSound: "அறிவிப்பு ஒலி",
  browserNotifications: "உலாவி அறிவிப்புகள்", enable: "இயக்கு",
  tx: { deposit: "வைப்பு", withdraw: "திரும்பப் பெறுதல்", bonus: "போனஸ்", plan: "திட்டம்", swap: "மாற்று", referral: "பரிந்துரை" },
  page: {
    heroTitle: "தொலைநோக்குடன் செல்வத்தை உருவாக்குங்கள்.", heroSub: "இன்றே முதலீடு செய்து, நாளையை உருவாக்குங்கள்.",
    registerNow: "இப்போது பதிவு செய்", conditionsCharges: "முதலீட்டு நிபந்தனைகள் மற்றும் கட்டணங்கள்",
    platformsLead: "GLOBAL BELDEX அனைத்து நிலை முதலீட்டாளர்களுக்கும் பல்வேறு தளங்களை வழங்குகிறது.",
    goodCompany: "நீங்கள் சிறந்த முதலீட்டாளர்களுடன் உள்ளீர்கள்", compareTitle: "கிரிப்டோ விலை ஒப்பீடு",
    minFunding: "குறைந்தபட்ச நிதி", openingAccount: "கணக்கு திறக்கும் நடைமுறை",
    liveMarketTv: "நேரடி BDXUSD சந்தை - TradingView மூலம்", trackBdx: "BDXUSD-ஐ கண்காணிக்க",
    featured: "சிறப்பு தயாரிப்பு", trustTitle: "நம்பகமான சக்திவாய்ந்த தளம்", safeTitle: "பாதுகாப்பானது",
    execTitle: "உடனடி செயலாக்கம்", awardTitle: "விருது பெற்றது", liveOverview: "நேரடி BDXUSD மேலோட்டம்",
    accountOverview: "கணக்கு மேலோட்டம்", viewChart: "விளக்கப்படத்தைப் பார்க்க", liveBdx: "நேரடி BDXUSD",
    livePrice: "நேரடி சந்தை விலை", marketWord: "சந்தை", liveWord: "நேரடி", calculator: "தொகை கணிப்பான்",
    errorTitle: "ஏதோ தவறு ஏற்பட்டது", legalTitle: "விதிமுறைகள், தனியுரிமை மற்றும் அபாயம்"
  }
};

export function extraLangs(en: Dict): Record<Exclude<Lang, "en" | "es">, Dict> {
  return {
    fr: merge(en, fr),
    it: merge(en, it),
    pt: merge(en, pt),
    nl: merge(en, nl),
    yue: merge(en, yue),
    zh: merge(en, zh),
    hi: merge(en, hi),
    ta: merge(en, ta),
  };
}
