const faqsEn = [
  { q: "Is this a live brokerage?", a: "No. GLOBAL BELDEX here is an educational demo with live Beldex charts from TradingView. Balances, deposits and plans are simulated in your browser." },
  { q: "What is the minimum deposit?", a: "The demo uses a $300 minimum to match the original product flow. Funds never leave your device." },
  { q: "How do investment plans work?", a: "Each plan locks a simulated amount for a fixed duration and accrues the listed daily profit. When the term ends, principal plus profit return to your available balance." },
  { q: "Where does market data come from?", a: "Ticker, overview and candlestick widgets are official TradingView embeds for CRYPTO:BDXUSD and major pairs." },
  { q: "Can I refer friends?", a: "Yes — every account gets a referral link. In this demo, referral bonuses are simulated when you copy and share your link." },
];

export const pageEn = {
  heroTitle: "Building Wealth with Vision.",
  heroSub: "Investing in Tomorrow, Today.",
  heroLead:
    "Global Beldex empowers investors to confidently invest CFDs on Forex, BDX, Crypto, and Indices. Benefit from advanced investing tools, tailored support, and industry-leading security. Whether you're a beginner or experienced investor, Global Beldex offers a seamless, secure platform designed to elevate your investment experience with precision and control.",
  registerNow: "Register Now",
  conditionsCharges: "Investment Conditions & Charges",
  platformsLead:
    "At GLOBAL BELDEX, we offer a wide variety of platforms for investors of all levels.",
  goodCompany: "You're In Good Company",
  companyCards: [
    {
      title: "Beginners",
      body: "Open an account, follow the live Beldex price, and start from the plan that matches your balance.",
    },
    {
      title: "Experienced investors",
      body: "Forex, BDX, crypto and indices sit on one desk, with the same charts and calculator.",
    },
    {
      title: "Support on call",
      body: "Reach the desk by phone, email, or the Newcastle office listed on this site.",
    },
  ],
  compareTitle: "Crypto Price Comparison",
  minFunding: "Minimum funding",
  openingAccount: "Opening account flow",
  openingLogin: "Opening login",
  statZero: "Zero fees",
  statZeroBody: "No commissions on trades",
  statLev: "Up to 400:1",
  statLevBody: "Maximum leverage",
  statInst: "Instant",
  statInstBody: "Execution < 12ms",
  liveMarketTv: "Live BDXUSD Market - Powered by TradingView",
  trackBdx: "Track BDXUSD",
  featured: "Featured Product",
  tvChartTitle: "Beldex Price Today — BDXUSD Chart — TradingView",
  liveFromTv: "Live data from TradingView · CRYPTO:BDXUSD",
  liveOverview: "Live BDXUSD Overview",
  poweredBy: "Powered by TradingView · CRYPTO:BDXUSD",
  conditions: "INVESTMENT CONDITIONS",
  trustTitle: "Powerful Platforms You Can Trust",
  safeTitle: "Safe & Secure",
  safeBody: "Bank-grade encryption and cold storage for all assets.",
  execTitle: "Instant Execution",
  execBody: "<12ms order execution with 99.9% uptime.",
  awardTitle: "Award Winning",
  awardBody: "Best Investment Platform 2024 — FinTech Awards.",
  step1t: "Open an account",
  step1d: "Register with email — a $3 welcome bonus is credited instantly in this demo.",
  step2t: "Fund the wallet",
  step2d: "Simulate a BELDEX deposit from $300. Credits complete in under two seconds.",
  step3t: "Activate a plan",
  step3d: "Lock funds into GNS through Falcon. Daily profit accrues until the term ends.",
  plansBoard: "GNS starts at 4,000 BDX. Build Up through Falcon use the same terms inside the account.",
  footerEdu: "© GLOBAL BELDEX — Live data from TradingView · Educational use only.",
  createToInvest: "Create account to invest",
  accountOverview: "Account Overview",
  liveDot: "Live · TradingView",
  viewChart: "View Chart",
  symbolLine: "Symbol: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFFICIAL",
  realtimeBlurb: "Real-time Beldex price, chart, market cap and stats from TradingView",
  overviewStats: "BDXUSD Overview & Stats",
  chartMeta: "1D · MA 9 · Volume",
  copyBtn: "Copy",
  planMeta: "{amount} locked · {pct}% ROI · {days} days",
  demoFoot: "Demo UI · Live data from TradingView · Educational template only",
  dashPreview: "DASHBOARD PREVIEW",
  availableTape: "Available · live BDXUSD tape",
  signInSim: "Sign in to load your simulated book",
  badLogin: "Email or password is wrong.",
  subjectPh: "Deposit timing",
  messagePh: "Tell us what you need",
  amountPh: "Enter amount... Min $300",
  liveBdx: "Live BDXUSD",
  livePrice: "Live market price",
  marketWord: "Market",
  liveWord: "Live",
  liveBeldex: "Live Beldex price",
  converter: "BDX CONVERTER",
  calculator: "Amount calculator",
  waitingPrice: "Waiting for the live Beldex price",
  intraday: "Intraday (60m)",
  codePrefix: "Code",
  chartFallback: "Chart powered by TradingView. If the widget is blocked in this preview, open the official BDXUSD page.",
  trackOnTv: "Track BDXUSD on TradingView",
  liveBadge: "Live BDXUSD · Powered by TradingView",
  eduDemo: "Live data from TradingView · Educational demo",
  linkExpired: "That link expired.",
  errorTitle: "Something went wrong",
  errorFallback: "An unexpected error occurred. Try reloading the page.",
  legalTitle: "Terms, privacy and risk",
  legalIntro: "This desk is an educational demo. Nothing here is a brokerage, a wallet, or an offer to buy Beldex or any other asset. Charts are embedded from TradingView. Balances never leave your browser.",
  legalBack: "Back to the platform",
  legalTerms: [
    "You can open an account, deposit a simulated amount from $300, swap between the USD book and BDX, and lock funds into GNS through Falcon. Those actions update numbers stored on this device only.",
    "Passwords live on your Supabase account. A reset email can set a new one. Demo balances, two-factor codes, tickets and referral bonuses stay on this device.",
    "Don’t use this interface to send real coins. Deposit addresses shown after “Continue to Payment” are fake marks for the demo flow.",
  ],
  legalPrivacy: [
    "Profile fields, transaction history and support tickets stay in local storage on your device. They are not uploaded to a GLOBAL BELDEX server, because there isn’t one.",
    "Live prices, when the network allows it, are requested from public market feeds. Candles and the ticker load from TradingView’s public widgets. Those third parties see a normal browser request, not your demo balance.",
  ],
  legalRisk: [
    "The plan figures — 1.90% over 1 month through 23.78% over 5 years — are illustrative. They are not a forecast, not a promise, and not how Beldex or any market actually pays.",
    "Leverage copy on the landing page (“up to 400:1”) describes the original product screen. This demo does not place leveraged orders.",
    "If you trade real assets anywhere else, you can lose money. Nothing on these screens is financial, legal or tax advice.",
  ],
  faqs: faqsEn,
};

export const pageEs: typeof pageEn = {
  heroTitle: "Construye patrimonio con visión.",
  heroSub: "Invierte en el mañana, hoy.",
  heroLead:
    "Global Beldex permite invertir con confianza en CFDs de Forex, BDX, cripto e índices. Herramientas avanzadas, soporte a medida y seguridad de primer nivel, tanto si empiezas como si ya inviertes.",
  registerNow: "Regístrate ahora",
  conditionsCharges: "Condiciones y cargos",
  platformsLead: "En GLOBAL BELDEX hay plataformas para inversores de todos los niveles.",
  goodCompany: "Estás en buena compañía",
  companyCards: [
    { title: "Principiantes", body: "Abre una cuenta, sigue el precio de Beldex en vivo y elige el plan que encaja con tu saldo." },
    { title: "Inversores con experiencia", body: "Forex, BDX, cripto e índices en un mismo escritorio, con los mismos gráficos y la calculadora." },
    { title: "Soporte", body: "Habla con el escritorio por teléfono, correo o la oficina de Newcastle que aparece en este sitio." },
  ],
  compareTitle: "Comparación de precio cripto",
  minFunding: "Fondeo mínimo",
  openingAccount: "Abriendo el registro",
  openingLogin: "Abriendo el acceso",
  statZero: "Cero comisiones",
  statZeroBody: "Sin comisiones en las operaciones",
  statLev: "Hasta 400:1",
  statLevBody: "Apalancamiento máximo",
  statInst: "Instantáneo",
  statInstBody: "Ejecución < 12 ms",
  liveMarketTv: "Mercado BDXUSD en vivo · TradingView",
  trackBdx: "Seguir BDXUSD",
  featured: "Producto destacado",
  tvChartTitle: "Precio de Beldex hoy — Gráfico BDXUSD — TradingView",
  liveFromTv: "Datos en vivo de TradingView · CRYPTO:BDXUSD",
  liveOverview: "Resumen BDXUSD en vivo",
  poweredBy: "Con tecnología de TradingView · CRYPTO:BDXUSD",
  conditions: "CONDICIONES DE INVERSIÓN",
  trustTitle: "Plataformas potentes en las que puedes confiar",
  safeTitle: "Seguro",
  safeBody: "Cifrado de nivel bancario y custodia en frío de los activos.",
  execTitle: "Ejecución instantánea",
  execBody: "Órdenes en menos de 12 ms con 99,9% de disponibilidad.",
  awardTitle: "Premiada",
  awardBody: "Mejor plataforma de inversión 2024 — FinTech Awards.",
  step1t: "Abre una cuenta",
  step1d: "Regístrate con el correo — el bono de bienvenida de $3 se acredita al instante en esta demo.",
  step2t: "Fondea la wallet",
  step2d: "Simula un depósito BELDEX desde $300. El crédito llega en menos de dos segundos.",
  step3t: "Activa un plan",
  step3d: "Bloquea fondos de GNS a Falcon. La ganancia diaria se acumula hasta que termina el plazo.",
  plansBoard: "GNS empieza en 4.000 BDX. De Build Up a Falcon se usan los mismos plazos dentro de la cuenta.",
  footerEdu: "© GLOBAL BELDEX — Datos en vivo de TradingView · Solo uso educativo.",
  createToInvest: "Crea una cuenta para invertir",
  accountOverview: "Resumen de la cuenta",
  liveDot: "En vivo · TradingView",
  viewChart: "Ver gráfico",
  symbolLine: "Símbolo: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFICIAL",
  realtimeBlurb: "Precio, gráfico, capitalización y datos de Beldex en tiempo real desde TradingView",
  overviewStats: "Resumen y datos de BDXUSD",
  chartMeta: "1D · MA 9 · Volumen",
  copyBtn: "Copiar",
  planMeta: "{amount} bloqueados · {pct}% ROI · {days} días",
  demoFoot: "Interfaz demo · Datos en vivo de TradingView · Solo plantilla educativa",
  dashPreview: "VISTA DEL PANEL",
  availableTape: "Disponible · cinta BDXUSD en vivo",
  signInSim: "Entra para cargar tu libro simulado",
  badLogin: "El correo o la contraseña no son correctos.",
  subjectPh: "Tiempo del depósito",
  messagePh: "Cuéntanos qué necesitas",
  amountPh: "Introduce el importe… mín. $300",
  liveBdx: "BDXUSD en vivo",
  livePrice: "Precio de mercado en vivo",
  marketWord: "Mercado",
  liveWord: "En vivo",
  liveBeldex: "Precio de Beldex en vivo",
  converter: "CONVERSOR BDX",
  calculator: "Calculadora de importe",
  waitingPrice: "Esperando el precio de Beldex en vivo",
  intraday: "Intradía (60 min)",
  codePrefix: "Código",
  chartFallback: "Gráfico de TradingView. Si el widget está bloqueado en esta vista, abre la página oficial de BDXUSD.",
  trackOnTv: "Seguir BDXUSD en TradingView",
  liveBadge: "BDXUSD en vivo · Con TradingView",
  eduDemo: "Datos en vivo de TradingView · Demo educativa",
  linkExpired: "Ese enlace caducó.",
  errorTitle: "Algo salió mal",
  errorFallback: "Ocurrió un error inesperado. Recarga la página.",
  legalTitle: "Términos, privacidad y riesgo",
  legalIntro: "Este escritorio es una demo educativa. Nada aquí es una casa de bolsa, una wallet ni una oferta de compra de Beldex u otro activo. Los gráficos vienen de TradingView. Los saldos no salen de tu navegador.",
  legalBack: "Volver a la plataforma",
  legalTerms: [
    "Puedes abrir una cuenta, depositar un importe simulado desde $300, cambiar entre el libro USD y BDX, y bloquear fondos de GNS a Falcon. Esas acciones solo cambian números guardados en este dispositivo.",
    "Las contraseñas están en tu cuenta de Supabase. Un correo de restablecimiento puede fijar una nueva. Los saldos demo, los códigos de doble factor, los tickets y los bonos de referido se quedan en este dispositivo.",
    "No uses esta interfaz para enviar monedas reales. Las direcciones que aparecen tras “Continuar al pago” son marcas falsas del flujo de la demo.",
  ],
  legalPrivacy: [
    "Los datos del perfil, el historial y los tickets de soporte se quedan en el almacenamiento local de tu dispositivo. No se suben a un servidor de GLOBAL BELDEX, porque no hay uno.",
    "Los precios en vivo, si la red lo permite, se piden a fuentes públicas. Las velas y la cinta cargan desde los widgets públicos de TradingView. Esos terceros ven una petición normal del navegador, no tu saldo demo.",
  ],
  legalRisk: [
    "Las cifras de los planes — 1,90% en 1 mes hasta 23,78% en 5 años — son ilustrativas. No son un pronóstico, ni una promesa, ni cómo paga Beldex o cualquier mercado.",
    "El texto de apalancamiento de la portada (“hasta 400:1”) describe la pantalla original del producto. Esta demo no coloca órdenes apalancadas.",
    "Si operas activos reales en otro sitio, puedes perder dinero. Nada en estas pantallas es asesoramiento financiero, legal o fiscal.",
  ],
  faqs: [
    { q: "¿Esto es una casa de bolsa real?", a: "No. GLOBAL BELDEX aquí es una demo educativa con gráficos de Beldex en vivo de TradingView. Saldos, depósitos y planes se simulan en tu navegador." },
    { q: "¿Cuál es el depósito mínimo?", a: "La demo usa un mínimo de $300 para seguir el flujo original. Los fondos no salen de tu dispositivo." },
    { q: "¿Cómo funcionan los planes?", a: "Cada plan bloquea un importe simulado por un plazo fijo y acumula la ganancia diaria indicada. Al terminar, principal más ganancia vuelven al saldo disponible." },
    { q: "¿De dónde salen los datos de mercado?", a: "La cinta, el resumen y las velas son widgets oficiales de TradingView para CRYPTO:BDXUSD y los pares principales." },
    { q: "¿Puedo invitar amigos?", a: "Sí. Cada cuenta tiene un enlace. En esta demo, el bono de referido se simula cuando copias y compartes el enlace." },
  ],
};

export const pageFr: typeof pageEn = {
  heroTitle: "Construire un patrimoine avec une vision.",
  heroSub: "Investir dans demain, aujourd’hui.",
  heroLead:
    "Global Beldex permet d’investir en CFD sur le Forex, BDX, la crypto et les indices. Outils avancés, accompagnement et sécurité de haut niveau, que vous débutiez ou non.",
  registerNow: "S’inscrire",
  conditionsCharges: "Conditions et frais",
  platformsLead: "Chez GLOBAL BELDEX, des plateformes pour les investisseurs de tous niveaux.",
  goodCompany: "Vous êtes en bonne compagnie",
  companyCards: [
    { title: "Débutants", body: "Ouvrez un compte, suivez le prix Beldex en direct et choisissez le plan qui correspond à votre solde." },
    { title: "Investisseurs expérimentés", body: "Forex, BDX, crypto et indices sur le même bureau, avec les mêmes graphiques et le convertisseur." },
    { title: "Assistance", body: "Joignez le bureau par téléphone, e-mail ou l’adresse de Newcastle indiquée sur ce site." },
  ],
  compareTitle: "Comparaison de prix crypto",
  minFunding: "Financement minimum",
  openingAccount: "Ouverture de l’inscription",
  openingLogin: "Ouverture de la connexion",
  statZero: "Zéro frais",
  statZeroBody: "Aucune commission sur les opérations",
  statLev: "Jusqu’à 400:1",
  statLevBody: "Levier maximum",
  statInst: "Instantané",
  statInstBody: "Exécution < 12 ms",
  liveMarketTv: "Marché BDXUSD en direct · TradingView",
  trackBdx: "Suivre BDXUSD",
  featured: "Produit en avant",
  tvChartTitle: "Prix Beldex aujourd’hui — Graphique BDXUSD — TradingView",
  liveFromTv: "Données en direct de TradingView · CRYPTO:BDXUSD",
  liveOverview: "Aperçu BDXUSD en direct",
  poweredBy: "Propulsé par TradingView · CRYPTO:BDXUSD",
  conditions: "CONDITIONS D’INVESTISSEMENT",
  trustTitle: "Des plateformes solides, dignes de confiance",
  safeTitle: "Sûr",
  safeBody: "Chiffrement de niveau bancaire et stockage à froid des actifs.",
  execTitle: "Exécution instantanée",
  execBody: "Ordres en moins de 12 ms avec 99,9 % de disponibilité.",
  awardTitle: "Récompensée",
  awardBody: "Meilleure plateforme d’investissement 2024 — FinTech Awards.",
  step1t: "Ouvrir un compte",
  step1d: "Inscrivez-vous par e-mail — le bonus de 3 $ est crédité tout de suite dans cette démo.",
  step2t: "Alimenter le portefeuille",
  step2d: "Simulez un dépôt BELDEX à partir de 300 $. Le crédit arrive en moins de deux secondes.",
  step3t: "Activer un plan",
  step3d: "Bloquez des fonds de GNS à Falcon. Le profit quotidien court jusqu’à la fin du terme.",
  plansBoard: "GNS commence à 4 000 BDX. De Build Up à Falcon, les mêmes conditions valent dans le compte.",
  footerEdu: "© GLOBAL BELDEX — Données en direct de TradingView · Usage éducatif seulement.",
  createToInvest: "Créez un compte pour investir",
  accountOverview: "Aperçu du compte",
  liveDot: "En direct · TradingView",
  viewChart: "Voir le graphique",
  symbolLine: "Symbole : CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFFICIEL",
  realtimeBlurb: "Prix, graphique, capitalisation et stats Beldex en temps réel depuis TradingView",
  overviewStats: "Aperçu et stats BDXUSD",
  chartMeta: "1D · MM 9 · Volume",
  copyBtn: "Copier",
  planMeta: "{amount} bloqués · {pct} % ROI · {days} jours",
  demoFoot: "Interface démo · Données en direct de TradingView · Modèle éducatif seulement",
  dashPreview: "APERÇU DU TABLEAU",
  availableTape: "Disponible · bande BDXUSD en direct",
  signInSim: "Connectez-vous pour charger votre livre simulé",
  badLogin: "E-mail ou mot de passe incorrect.",
  subjectPh: "Délai du dépôt",
  messagePh: "Dites-nous ce qu’il vous faut",
  amountPh: "Saisir le montant… min. 300 $",
  liveBdx: "BDXUSD en direct",
  livePrice: "Prix du marché en direct",
  marketWord: "Marché",
  liveWord: "En direct",
  liveBeldex: "Prix Beldex en direct",
  converter: "CONVERTISSEUR BDX",
  calculator: "Calculateur de montant",
  waitingPrice: "En attente du prix Beldex en direct",
  intraday: "Intraday (60 min)",
  codePrefix: "Code",
  chartFallback: "Graphique TradingView. Si le widget est bloqué dans cet aperçu, ouvrez la page officielle BDXUSD.",
  trackOnTv: "Suivre BDXUSD sur TradingView",
  liveBadge: "BDXUSD en direct · TradingView",
  eduDemo: "Données en direct de TradingView · Démo éducative",
  linkExpired: "Ce lien a expiré.",
  errorTitle: "Un problème est survenu",
  errorFallback: "Une erreur inattendue s’est produite. Rechargez la page.",
  legalTitle: "Conditions, confidentialité et risque",
  legalIntro: "Ce bureau est une démo éducative. Rien ici n’est un courtier, un portefeuille, ni une offre d’achat de Beldex ou d’un autre actif. Les graphiques viennent de TradingView. Les soldes ne quittent pas votre navigateur.",
  legalBack: "Retour à la plateforme",
  legalTerms: [
    "Vous pouvez ouvrir un compte, déposer un montant simulé à partir de 300 $, échanger entre le livre USD et BDX, et bloquer des fonds de GNS à Falcon. Ces actions ne changent que des nombres stockés sur cet appareil.",
    "Les mots de passe sont sur votre compte Supabase. Un e-mail de réinitialisation peut en définir un nouveau. Les soldes de démo, codes à deux facteurs, tickets et bonus de parrainage restent sur cet appareil.",
    "N’utilisez pas cette interface pour envoyer de vraies pièces. Les adresses après « Continuer vers le paiement » sont de fausses marques du parcours de démo.",
  ],
  legalPrivacy: [
    "Le profil, l’historique et les tickets restent dans le stockage local de votre appareil. Ils ne sont pas envoyés à un serveur GLOBAL BELDEX, parce qu’il n’y en a pas.",
    "Les prix en direct, si le réseau le permet, viennent de flux publics. Les bougies et le bandeau chargent les widgets publics de TradingView. Ces tiers voient une requête de navigateur normale, pas votre solde de démo.",
  ],
  legalRisk: [
    "Les chiffres des plans — 1,90 % sur 1 mois jusqu’à 23,78 % sur 5 ans — sont illustratifs. Ce n’est ni une prévision, ni une promesse, ni la façon dont Beldex ou un marché paie vraiment.",
    "Le texte sur le levier de la page d’accueil (« jusqu’à 400:1 ») décrit l’écran d’origine. Cette démo ne passe pas d’ordres à effet de levier.",
    "Si vous tradez de vrais actifs ailleurs, vous pouvez perdre de l’argent. Rien sur ces écrans n’est un conseil financier, juridique ou fiscal.",
  ],
  faqs: [
    { q: "Est-ce un courtier réel ?", a: "Non. GLOBAL BELDEX ici est une démo éducative avec des graphiques Beldex en direct de TradingView. Soldes, dépôts et plans sont simulés dans votre navigateur." },
    { q: "Quel est le dépôt minimum ?", a: "La démo utilise un minimum de 300 $ pour suivre le parcours d’origine. Les fonds ne quittent pas votre appareil." },
    { q: "Comment fonctionnent les plans ?", a: "Chaque plan bloque un montant simulé pour une durée fixe et ajoute le profit quotidien indiqué. À la fin, capital et profit reviennent au solde disponible." },
    { q: "D’où viennent les données de marché ?", a: "Le bandeau, l’aperçu et les bougies sont des widgets officiels TradingView pour CRYPTO:BDXUSD et les grandes paires." },
    { q: "Puis-je parrainer des amis ?", a: "Oui. Chaque compte a un lien. Dans cette démo, le bonus est simulé quand vous copiez et partagez le lien." },
  ],
};

export const pageIt: typeof pageEn = {
  heroTitle: "Costruire patrimonio con una visione.",
  heroSub: "Investire nel domani, oggi.",
  heroLead:
    "Global Beldex permette di investire in CFD su Forex, BDX, crypto e indici. Strumenti avanzati, supporto su misura e sicurezza di alto livello, per chi inizia e per chi ha già esperienza.",
  registerNow: "Registrati ora",
  conditionsCharges: "Condizioni e costi",
  platformsLead: "In GLOBAL BELDEX ci sono piattaforme per investitori di ogni livello.",
  goodCompany: "Sei in buona compagnia",
  companyCards: [
    { title: "Principianti", body: "Apri un account, segui il prezzo Beldex live e scegli il piano adatto al tuo saldo." },
    { title: "Investitori esperti", body: "Forex, BDX, crypto e indici sulla stessa scrivania, con gli stessi grafici e il convertitore." },
    { title: "Supporto", body: "Contatta la scrivania per telefono, email o l’ufficio di Newcastle indicato su questo sito." },
  ],
  compareTitle: "Confronto prezzi crypto",
  minFunding: "Finanziamento minimo",
  openingAccount: "Apertura della registrazione",
  openingLogin: "Apertura dell’accesso",
  statZero: "Zero commissioni",
  statZeroBody: "Nessuna commissione sulle operazioni",
  statLev: "Fino a 400:1",
  statLevBody: "Leva massima",
  statInst: "Istantaneo",
  statInstBody: "Esecuzione < 12 ms",
  liveMarketTv: "Mercato BDXUSD live · TradingView",
  trackBdx: "Segui BDXUSD",
  featured: "Prodotto in evidenza",
  tvChartTitle: "Prezzo Beldex oggi — Grafico BDXUSD — TradingView",
  liveFromTv: "Dati live da TradingView · CRYPTO:BDXUSD",
  liveOverview: "Panoramica BDXUSD live",
  poweredBy: "Con tecnologia TradingView · CRYPTO:BDXUSD",
  conditions: "CONDIZIONI DI INVESTIMENTO",
  trustTitle: "Piattaforme solide di cui ti puoi fidare",
  safeTitle: "Sicuro",
  safeBody: "Cifratura di livello bancario e custodia a freddo degli asset.",
  execTitle: "Esecuzione istantanea",
  execBody: "Ordini sotto i 12 ms con uptime del 99,9%.",
  awardTitle: "Premiata",
  awardBody: "Miglior piattaforma di investimento 2024 — FinTech Awards.",
  step1t: "Apri un account",
  step1d: "Registrati con l’email — il bonus di benvenuto di $3 è accreditato subito in questa demo.",
  step2t: "Finanzia il wallet",
  step2d: "Simula un deposito BELDEX da $300. L’accredito arriva in meno di due secondi.",
  step3t: "Attiva un piano",
  step3d: "Blocca fondi da GNS a Falcon. Il profitto giornaliero cresce fino alla fine del periodo.",
  plansBoard: "GNS parte da 4.000 BDX. Da Build Up a Falcon valgono le stesse condizioni nel conto.",
  footerEdu: "© GLOBAL BELDEX — Dati live da TradingView · Solo uso educativo.",
  createToInvest: "Crea un account per investire",
  accountOverview: "Panoramica account",
  liveDot: "Live · TradingView",
  viewChart: "Vedi grafico",
  symbolLine: "Simbolo: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW UFFICIALE",
  realtimeBlurb: "Prezzo, grafico, capitalizzazione e dati Beldex in tempo reale da TradingView",
  overviewStats: "Panoramica e dati BDXUSD",
  chartMeta: "1D · MA 9 · Volume",
  copyBtn: "Copia",
  planMeta: "{amount} bloccati · {pct}% ROI · {days} giorni",
  demoFoot: "Interfaccia demo · Dati live da TradingView · Solo modello educativo",
  dashPreview: "ANTEPRIMA DASHBOARD",
  availableTape: "Disponibile · nastro BDXUSD live",
  signInSim: "Accedi per caricare il libro simulato",
  badLogin: "Email o password errate.",
  subjectPh: "Tempi del deposito",
  messagePh: "Dicci di cosa hai bisogno",
  amountPh: "Inserisci l’importo… min. $300",
  liveBdx: "BDXUSD live",
  livePrice: "Prezzo di mercato live",
  marketWord: "Mercato",
  liveWord: "Live",
  liveBeldex: "Prezzo Beldex live",
  converter: "CONVERTITORE BDX",
  calculator: "Calcolatore di importo",
  waitingPrice: "In attesa del prezzo Beldex live",
  intraday: "Intraday (60 min)",
  codePrefix: "Codice",
  chartFallback: "Grafico TradingView. Se il widget è bloccato in questa anteprima, apri la pagina ufficiale BDXUSD.",
  trackOnTv: "Segui BDXUSD su TradingView",
  liveBadge: "BDXUSD live · TradingView",
  eduDemo: "Dati live da TradingView · Demo educativa",
  linkExpired: "Quel link è scaduto.",
  errorTitle: "Qualcosa è andato storto",
  errorFallback: "Si è verificato un errore imprevisto. Ricarica la pagina.",
  legalTitle: "Termini, privacy e rischio",
  legalIntro: "Questa scrivania è una demo educativa. Niente qui è un broker, un wallet o un’offerta di acquisto di Beldex o di un altro asset. I grafici arrivano da TradingView. I saldi non lasciano il browser.",
  legalBack: "Torna alla piattaforma",
  legalTerms: [
    "Puoi aprire un account, depositare un importo simulato da $300, scambiare tra il libro USD e BDX e bloccare fondi da GNS a Falcon. Queste azioni aggiornano solo numeri salvati su questo dispositivo.",
    "Le password stanno sul tuo account Supabase. Un’email di reset può impostarne una nuova. Saldi demo, codici a due fattori, ticket e bonus invito restano su questo dispositivo.",
    "Non usare questa interfaccia per inviare monete reali. Gli indirizzi dopo “Continua al pagamento” sono segni finti del flusso demo.",
  ],
  legalPrivacy: [
    "Profilo, cronologia e ticket restano nella memoria locale del dispositivo. Non vengono caricati su un server GLOBAL BELDEX, perché non esiste.",
    "I prezzi live, se la rete lo consente, arrivano da feed pubblici. Candele e ticker caricano i widget pubblici di TradingView. Quei terzi vedono una richiesta normale del browser, non il tuo saldo demo.",
  ],
  legalRisk: [
    "Le cifre dei piani — 1,90% in 1 mese fino a 23,78% in 5 anni — sono illustrative. Non sono una previsione, né una promessa, né il modo in cui Beldex o un mercato paga davvero.",
    "Il testo sulla leva in home (“fino a 400:1”) descrive la schermata originale. Questa demo non invia ordini a leva.",
    "Se scambi asset reali altrove, puoi perdere denaro. Nulla in queste schermate è consulenza finanziaria, legale o fiscale.",
  ],
  faqs: [
    { q: "È un broker vero?", a: "No. GLOBAL BELDEX qui è una demo educativa con grafici Beldex live da TradingView. Saldi, depositi e piani sono simulati nel browser." },
    { q: "Qual è il deposito minimo?", a: "La demo usa un minimo di $300 per seguire il flusso originale. I fondi non lasciano il dispositivo." },
    { q: "Come funzionano i piani?", a: "Ogni piano blocca un importo simulato per una durata fissa e accumula il profitto giornaliero indicato. A scadenza, capitale e profitto tornano al saldo disponibile." },
    { q: "Da dove arrivano i dati di mercato?", a: "Ticker, panoramica e candele sono widget ufficiali TradingView per CRYPTO:BDXUSD e le coppie principali." },
    { q: "Posso invitare amici?", a: "Sì. Ogni account ha un link. In questa demo il bonus è simulato quando copi e condividi il link." },
  ],
};

export const pagePt: typeof pageEn = {
  heroTitle: "Construir patrimônio com visão.",
  heroSub: "Investir no amanhã, hoje.",
  heroLead:
    "A Global Beldex permite investir em CFDs de Forex, BDX, cripto e índices. Ferramentas avançadas, suporte sob medida e segurança de alto nível, para iniciantes e investidores experientes.",
  registerNow: "Cadastre-se agora",
  conditionsCharges: "Condições e taxas",
  platformsLead: "Na GLOBAL BELDEX há plataformas para investidores de todos os níveis.",
  goodCompany: "Você está em boa companhia",
  companyCards: [
    { title: "Iniciantes", body: "Abra uma conta, acompanhe o preço ao vivo da Beldex e escolha o plano do seu saldo." },
    { title: "Investidores experientes", body: "Forex, BDX, cripto e índices na mesma mesa, com os mesmos gráficos e a calculadora." },
    { title: "Suporte", body: "Fale com a mesa por telefone, e-mail ou o escritório de Newcastle listado neste site." },
  ],
  compareTitle: "Comparação de preço cripto",
  minFunding: "Aporte mínimo",
  openingAccount: "Abrindo o cadastro",
  openingLogin: "Abrindo o acesso",
  statZero: "Zero taxas",
  statZeroBody: "Sem comissões nas operações",
  statLev: "Até 400:1",
  statLevBody: "Alavancagem máxima",
  statInst: "Instantâneo",
  statInstBody: "Execução < 12 ms",
  liveMarketTv: "Mercado BDXUSD ao vivo · TradingView",
  trackBdx: "Acompanhar BDXUSD",
  featured: "Produto em destaque",
  tvChartTitle: "Preço da Beldex hoje — Gráfico BDXUSD — TradingView",
  liveFromTv: "Dados ao vivo da TradingView · CRYPTO:BDXUSD",
  liveOverview: "Visão BDXUSD ao vivo",
  poweredBy: "Com tecnologia TradingView · CRYPTO:BDXUSD",
  conditions: "CONDIÇÕES DE INVESTIMENTO",
  trustTitle: "Plataformas fortes em que você pode confiar",
  safeTitle: "Seguro",
  safeBody: "Criptografia de nível bancário e custódia fria dos ativos.",
  execTitle: "Execução instantânea",
  execBody: "Ordens em menos de 12 ms com 99,9% de disponibilidade.",
  awardTitle: "Premiada",
  awardBody: "Melhor plataforma de investimento 2024 — FinTech Awards.",
  step1t: "Abra uma conta",
  step1d: "Cadastre-se com o e-mail — o bônus de $3 entra na hora nesta demo.",
  step2t: "Abasteça a carteira",
  step2d: "Simule um depósito BELDEX a partir de $300. O crédito chega em menos de dois segundos.",
  step3t: "Ative um plano",
  step3d: "Bloqueie fundos de GNS até Falcon. O lucro diário acumula até o fim do prazo.",
  plansBoard: "GNS começa em 4.000 BDX. De Build Up a Falcon valem os mesmos prazos dentro da conta.",
  footerEdu: "© GLOBAL BELDEX — Dados ao vivo da TradingView · Somente uso educativo.",
  createToInvest: "Crie uma conta para investir",
  accountOverview: "Visão da conta",
  liveDot: "Ao vivo · TradingView",
  viewChart: "Ver gráfico",
  symbolLine: "Símbolo: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFICIAL",
  realtimeBlurb: "Preço, gráfico, valor de mercado e dados da Beldex em tempo real da TradingView",
  overviewStats: "Visão e dados de BDXUSD",
  chartMeta: "1D · MM 9 · Volume",
  copyBtn: "Copiar",
  planMeta: "{amount} bloqueados · {pct}% ROI · {days} dias",
  demoFoot: "Interface demo · Dados ao vivo da TradingView · Somente modelo educativo",
  dashPreview: "PRÉVIA DO PAINEL",
  availableTape: "Disponível · fita BDXUSD ao vivo",
  signInSim: "Entre para carregar o livro simulado",
  badLogin: "E-mail ou senha incorretos.",
  subjectPh: "Prazo do depósito",
  messagePh: "Diga o que você precisa",
  amountPh: "Digite o valor… mín. $300",
  liveBdx: "BDXUSD ao vivo",
  livePrice: "Preço de mercado ao vivo",
  marketWord: "Mercado",
  liveWord: "Ao vivo",
  liveBeldex: "Preço da Beldex ao vivo",
  converter: "CONVERSOR BDX",
  calculator: "Calculadora de valor",
  waitingPrice: "Aguardando o preço ao vivo da Beldex",
  intraday: "Intraday (60 min)",
  codePrefix: "Código",
  chartFallback: "Gráfico da TradingView. Se o widget estiver bloqueado nesta prévia, abra a página oficial de BDXUSD.",
  trackOnTv: "Acompanhar BDXUSD na TradingView",
  liveBadge: "BDXUSD ao vivo · TradingView",
  eduDemo: "Dados ao vivo da TradingView · Demo educativa",
  linkExpired: "Esse link expirou.",
  errorTitle: "Algo deu errado",
  errorFallback: "Ocorreu um erro inesperado. Recarregue a página.",
  legalTitle: "Termos, privacidade e risco",
  legalIntro: "Esta mesa é uma demo educativa. Nada aqui é uma corretora, uma carteira ou uma oferta de compra de Beldex ou de outro ativo. Os gráficos vêm da TradingView. Os saldos não saem do navegador.",
  legalBack: "Voltar à plataforma",
  legalTerms: [
    "Você pode abrir uma conta, depositar um valor simulado a partir de $300, trocar entre o livro USD e BDX e bloquear fundos de GNS até Falcon. Essas ações só mudam números salvos neste aparelho.",
    "As senhas ficam na sua conta Supabase. Um e-mail de redefinição pode criar outra. Saldos da demo, códigos de dois fatores, pedidos e bônus de indicação ficam neste aparelho.",
    "Não use esta interface para enviar moedas reais. Os endereços depois de “Continuar para o pagamento” são marcas falsas do fluxo da demo.",
  ],
  legalPrivacy: [
    "Perfil, histórico e pedidos de suporte ficam no armazenamento local do aparelho. Não são enviados a um servidor da GLOBAL BELDEX, porque não existe um.",
    "Os preços ao vivo, quando a rede permite, vêm de fontes públicas. Velas e fita carregam os widgets públicos da TradingView. Esses terceiros veem um pedido normal do navegador, não o seu saldo da demo.",
  ],
  legalRisk: [
    "Os números dos planos — 1,90% em 1 mês até 23,78% em 5 anos — são ilustrativos. Não são previsão, nem promessa, nem o modo como a Beldex ou qualquer mercado paga de fato.",
    "O texto de alavancagem da página inicial (“até 400:1”) descreve a tela original. Esta demo não envia ordens alavancadas.",
    "Se você negociar ativos reais em outro lugar, pode perder dinheiro. Nada nestas telas é aconselhamento financeiro, jurídico ou fiscal.",
  ],
  faqs: [
    { q: "Isto é uma corretora de verdade?", a: "Não. A GLOBAL BELDEX aqui é uma demo educativa com gráficos ao vivo da Beldex da TradingView. Saldos, depósitos e planos são simulados no navegador." },
    { q: "Qual é o depósito mínimo?", a: "A demo usa um mínimo de $300 para seguir o fluxo original. Os fundos não saem do aparelho." },
    { q: "Como os planos funcionam?", a: "Cada plano bloqueia um valor simulado por um prazo fixo e acumula o lucro diário indicado. No fim, principal e lucro voltam ao saldo disponível." },
    { q: "De onde vêm os dados de mercado?", a: "Fita, visão e velas são widgets oficiais da TradingView para CRYPTO:BDXUSD e os pares principais." },
    { q: "Posso indicar amigos?", a: "Sim. Cada conta tem um link. Nesta demo, o bônus é simulado quando você copia e compartilha o link." },
  ],
};

export const pageNl: typeof pageEn = {
  heroTitle: "Vermogen opbouwen met visie.",
  heroSub: "Investeren in morgen, vandaag.",
  heroLead:
    "Global Beldex laat je beleggen in CFD’s op forex, BDX, crypto en indices. Geavanceerde tools, persoonlijke support en sterke beveiliging, voor beginners en ervaren beleggers.",
  registerNow: "Nu registreren",
  conditionsCharges: "Voorwaarden en kosten",
  platformsLead: "Bij GLOBAL BELDEX zijn er platforms voor beleggers van elk niveau.",
  goodCompany: "Je bent in goed gezelschap",
  companyCards: [
    { title: "Beginners", body: "Open een account, volg de live Beldex-prijs en kies het plan dat bij je saldo past." },
    { title: "Ervaren beleggers", body: "Forex, BDX, crypto en indices op één bureau, met dezelfde grafieken en de rekenhulp." },
    { title: "Support", body: "Bereik het bureau via telefoon, e-mail of het kantoor in Newcastle op deze site." },
  ],
  compareTitle: "Cryptoprijsvergelijking",
  minFunding: "Minimale inleg",
  openingAccount: "Registratie openen",
  openingLogin: "Inloggen openen",
  statZero: "Geen kosten",
  statZeroBody: "Geen commissie op transacties",
  statLev: "Tot 400:1",
  statLevBody: "Maximale hefboom",
  statInst: "Direct",
  statInstBody: "Uitvoering < 12 ms",
  liveMarketTv: "Live BDXUSD-markt · TradingView",
  trackBdx: "BDXUSD volgen",
  featured: "Uitgelicht product",
  tvChartTitle: "Beldex-prijs vandaag — BDXUSD-grafiek — TradingView",
  liveFromTv: "Live data van TradingView · CRYPTO:BDXUSD",
  liveOverview: "Live BDXUSD-overzicht",
  poweredBy: "Mogelijk gemaakt door TradingView · CRYPTO:BDXUSD",
  conditions: "BELEGGINGSVOORWAARDEN",
  trustTitle: "Sterke platforms waarop je kunt vertrouwen",
  safeTitle: "Veilig",
  safeBody: "Versleuteling op bankniveau en cold storage voor activa.",
  execTitle: "Directe uitvoering",
  execBody: "Orders onder 12 ms met 99,9% uptime.",
  awardTitle: "Bekroond",
  awardBody: "Beste beleggingsplatform 2024 — FinTech Awards.",
  step1t: "Open een account",
  step1d: "Registreer met e-mail — de welkomstbonus van $3 wordt meteen bijgeschreven in deze demo.",
  step2t: "Vul de wallet",
  step2d: "Simuleer een BELDEX-storting vanaf $300. Het tegoed staat er in minder dan twee seconden.",
  step3t: "Activeer een plan",
  step3d: "Blokkeer geld van GNS tot Falcon. Dagelijkse winst loopt door tot het einde van de termijn.",
  plansBoard: "GNS begint bij 4.000 BDX. Van Build Up tot Falcon gelden dezelfde voorwaarden in het account.",
  footerEdu: "© GLOBAL BELDEX — Live data van TradingView · Alleen educatief gebruik.",
  createToInvest: "Maak een account om te beleggen",
  accountOverview: "Accountoverzicht",
  liveDot: "Live · TradingView",
  viewChart: "Grafiek bekijken",
  symbolLine: "Symbool: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFFICIEEL",
  realtimeBlurb: "Realtime Beldex-prijs, grafiek, marktkapitalisatie en cijfers van TradingView",
  overviewStats: "BDXUSD-overzicht en cijfers",
  chartMeta: "1D · MA 9 · Volume",
  copyBtn: "Kopiëren",
  planMeta: "{amount} geblokkeerd · {pct}% ROI · {days} dagen",
  demoFoot: "Demo-interface · Live data van TradingView · Alleen een educatief sjabloon",
  dashPreview: "DASHBOARD-VOORBEELD",
  availableTape: "Beschikbaar · live BDXUSD-ticker",
  signInSim: "Log in om je gesimuleerde boek te laden",
  badLogin: "E-mail of wachtwoord is onjuist.",
  subjectPh: "Timing van de storting",
  messagePh: "Vertel wat je nodig hebt",
  amountPh: "Vul het bedrag in… min. $300",
  liveBdx: "Live BDXUSD",
  livePrice: "Live marktprijs",
  marketWord: "Markt",
  liveWord: "Live",
  liveBeldex: "Live Beldex-prijs",
  converter: "BDX-OMREKENER",
  calculator: "Bedragcalculator",
  waitingPrice: "Wachten op de live Beldex-prijs",
  intraday: "Intraday (60 min)",
  codePrefix: "Code",
  chartFallback: "Grafiek van TradingView. Als de widget in dit voorbeeld geblokkeerd is, open de officiële BDXUSD-pagina.",
  trackOnTv: "BDXUSD volgen op TradingView",
  liveBadge: "Live BDXUSD · TradingView",
  eduDemo: "Live data van TradingView · Educatieve demo",
  linkExpired: "Die link is verlopen.",
  errorTitle: "Er ging iets mis",
  errorFallback: "Er is een onverwachte fout opgetreden. Laad de pagina opnieuw.",
  legalTitle: "Voorwaarden, privacy en risico",
  legalIntro: "Dit bureau is een educatieve demo. Niets hier is een broker, een wallet of een aanbod om Beldex of een ander activum te kopen. Grafieken komen van TradingView. Saldi verlaten je browser niet.",
  legalBack: "Terug naar het platform",
  legalTerms: [
    "Je kunt een account openen, een gesimuleerd bedrag vanaf $300 storten, wisselen tussen het USD-boek en BDX, en geld blokkeren van GNS tot Falcon. Die acties wijzigen alleen getallen op dit apparaat.",
    "Wachtwoorden staan op je Supabase-account. Een resetmail kan een nieuw wachtwoord zetten. Demosaldi, tweestapscodes, tickets en verwijzingsbonussen blijven op dit apparaat.",
    "Gebruik deze interface niet om echte munten te sturen. Adressen na “Doorgaan naar betaling” zijn nepadressen voor de demo.",
  ],
  legalPrivacy: [
    "Profiel, transactiegeschiedenis en supporttickets blijven in de lokale opslag van je apparaat. Ze gaan niet naar een GLOBAL BELDEX-server, want die is er niet.",
    "Live prijzen, als het netwerk het toelaat, komen van openbare feeds. Kaarsen en de ticker laden publieke TradingView-widgets. Die partijen zien een gewone browseraanvraag, niet je demosaldo.",
  ],
  legalRisk: [
    "De plancijfers — 1,90% over 1 maand tot 23,78% over 5 jaar — zijn illustratief. Geen voorspelling, geen belofte, en niet hoe Beldex of een markt echt uitbetaalt.",
    "De hefboomtekst op de landingspagina (“tot 400:1”) beschrijft het oorspronkelijke scherm. Deze demo plaatst geen hefboomorders.",
    "Als je elders echte activa verhandelt, kun je geld verliezen. Niets op deze schermen is financieel, juridisch of fiscaal advies.",
  ],
  faqs: [
    { q: "Is dit een echte broker?", a: "Nee. GLOBAL BELDEX hier is een educatieve demo met live Beldex-grafieken van TradingView. Saldi, stortingen en plannen zijn gesimuleerd in je browser." },
    { q: "Wat is de minimale storting?", a: "De demo gebruikt een minimum van $300 om de oorspronkelijke flow te volgen. Geld verlaat je apparaat niet." },
    { q: "Hoe werken de plannen?", a: "Elk plan blokkeert een gesimuleerd bedrag voor een vaste duur en telt de genoemde dagelijkse winst op. Aan het einde gaan inleg en winst terug naar je beschikbare saldo." },
    { q: "Waar komen de marktgegevens vandaan?", a: "Ticker, overzicht en kaarsen zijn officiële TradingView-widgets voor CRYPTO:BDXUSD en de grote paren." },
    { q: "Kan ik vrienden verwijzen?", a: "Ja. Elk account heeft een link. In deze demo wordt de bonus gesimuleerd als je de link kopieert en deelt." },
  ],
};
