const faqsEn = [
  { q: "Is this a live brokerage?", a: "Yes. GLOBAL BELDEX is a professional investment platform with live Beldex charts from TradingView. Balances, deposits, and plans are processed in real-time." },
  { q: "What is the minimum deposit?", a: "A $300 minimum deposit is required to activate a live account and access investment plans." },
  { q: "How do investment plans work?", a: "Each plan locks a specific amount for a fixed duration and accrues the listed daily profit. When the term ends, principal plus profit return to your available balance." },
  { q: "Where does market data come from?", a: "Ticker, overview, and candlestick widgets are official TradingView embeds for CRYPTO:BDXUSD and major pairs, providing tier-1 liquidity pricing." },
  { q: "Can I refer friends?", a: "Yes — every account gets a referral link. Referral bonuses are credited automatically when your invited network funds their accounts." },
];

export const pageEn = {
  heroTitle: "Building Wealth with Vision.",
  heroSub: "Investing in Tomorrow, Today.",
  heroLead:
    "Global Beldex empowers investors to confidently trade CFDs on Forex, BDX, Crypto, and Indices. Benefit from advanced investing tools, tailored support, and industry-leading security. Whether you're a beginner or experienced investor, Global Beldex offers a seamless, secure platform designed to elevate your investment experience with precision and control.",
  registerNow: "Register Now",
  conditionsCharges: "Investment Conditions & Charges",
  platformsLead:
    "At GLOBAL BELDEX, we offer a wide variety of platforms for investors of all levels.",
  goodCompany: "You're In Good Company",
  companyCards: [
    {
      title: "Beginners",
      body: "Open an account, follow the live Beldex price, and start with the plan that matches your balance.",
    },
    {
      title: "Experienced investors",
      body: "Forex, BDX, crypto, and indices sit on one desk, featuring professional charts and calculators.",
    },
    {
      title: "Support on call",
      body: "Reach our trading desk by phone, email, or through our Newcastle office listed on this site.",
    },
  ],
  compareTitle: "Crypto Price Comparison",
  minFunding: "Minimum funding",
  openingAccount: "Opening account flow",
  openingLogin: "Opening login",
  statZero: "Zero fees",
  statZeroBody: "No commissions on trades",
  statLev: "Up to 400:1",
  statLevBody: "Maximum leverage",
  statInst: "Instant",
  statInstBody: "Execution < 12ms",
  liveMarketTv: "Live BDXUSD Market - Powered by TradingView",
  trackBdx: "Track BDXUSD",
  featured: "Featured Product",
  tvChartTitle: "Beldex Price Today — BDXUSD Chart — TradingView",
  liveFromTv: "Live data from TradingView · CRYPTO:BDXUSD",
  liveOverview: "Live BDXUSD Overview",
  poweredBy: "Powered by TradingView · CRYPTO:BDXUSD",
  conditions: "INVESTMENT CONDITIONS",
  trustTitle: "Powerful Platforms You Can Trust",
  safeTitle: "Safe & Secure",
  safeBody: "Bank-grade encryption and cold storage for all digital assets.",
  execTitle: "Instant Execution",
  execBody: "<12ms order execution with 99.9% uptime.",
  awardTitle: "Award Winning",
  awardBody: "Best Investment Platform 2024 — FinTech Awards.",
  step1t: "Open an account",
  step1d: "Register with email — a $3 welcome bonus is credited instantly upon verification.",
  step2t: "Fund the wallet",
  step2d: "Deposit starting from $300. Network credits complete in under two seconds.",
  step3t: "Activate a plan",
  step3d: "Lock funds into GNS through Falcon. Daily profit accrues until the term ends.",
  plansBoard: "GNS starts at 4,000 BDX. Build Up through Falcon use the same premium terms inside the account.",
  footerEdu: "© GLOBAL BELDEX — Live market data provided by TradingView.",
  createToInvest: "Create account to invest",
  accountOverview: "Account Overview",
  liveDot: "Live · TradingView",
  viewChart: "View Chart",
  symbolLine: "Symbol: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFFICIAL",
  realtimeBlurb: "Real-time Beldex price, chart, market cap and stats from TradingView",
  overviewStats: "BDXUSD Overview & Stats",
  chartMeta: "1D · MA 9 · Volume",
  copyBtn: "Copy",
  planMeta: "{amount} locked · {pct}% ROI · {days} days",
  liveFoot: " · Live data from TradingView · ",
  dashPreview: "DASHBOARD",
  availableTape: "Available · live BDXUSD tape",
  signInSim: "Sign in to access your portfolio",
  badLogin: "Email or password is wrong.",
  subjectPh: "Deposit timing",
  messagePh: "Tell us what you need",
  amountPh: "Enter amount... Min $300",
  liveBdx: "Live BDXUSD",
  livePrice: "Live market price",
  marketWord: "Market",
  liveWord: "Live",
  liveBeldex: "Live Beldex price",
  converter: "BDX CONVERTER",
  calculator: "Amount calculator",
  waitingPrice: "Waiting for live network price",
  intraday: "Intraday (60m)",
  codePrefix: "Code",
  chartFallback: "Chart powered by TradingView. If the widget fails to load, please check your connection.",
  trackOnTv: "Track BDXUSD on TradingView",
  liveBadge: "Live BDXUSD · Powered by TradingView",
  eduDemo: "Live market data from TradingView",
  linkExpired: "That link has expired.",
  errorTitle: "Something went wrong",
  errorFallback: "An unexpected error occurred. Please try reloading the page.",
  legalTitle: "Terms, privacy and risk",
  legalIntro: "Global Beldex is a professional trading and investment platform. We provide highly secure wallets, real-time market execution, and institutional-grade charting tools.",
  legalBack: "Back to the platform",
  legalTerms: [
    "By opening an account, you can deposit funds starting from $300, execute swaps between USD and BDX, and stake assets into our GNS and Falcon plans.",
    "Your account is secured with advanced encryption. Ensure two-factor authentication (2FA) is enabled for withdrawals and account changes.",
    "Only use the deposit addresses explicitly generated for your session after clicking “Continue to Payment”.",
  ],
  legalPrivacy: [
    "Your profile data, transaction history, and support tickets are fully encrypted and securely stored on our institutional servers.",
    "Live pricing is routed through secure connections to major liquidity providers and TradingView. Your personal trading activity remains strictly confidential.",
  ],
  legalRisk: [
    "Plan yield figures represent target ROIs based on historical market modeling. Cryptocurrencies and forex are volatile; returns may fluctuate.",
    "Margin and leveraged trading (up to 400:1) carry a high level of risk and may not be suitable for all investors. You may lose more than your initial deposit.",
    "Ensure you fully understand the risks involved before trading real assets. Information provided on this platform does not constitute financial or tax advice.",
  ],
  faqs: faqsEn,
};

export const pageEs: typeof pageEn = {
  heroTitle: "Construye patrimonio con visión.",
  heroSub: "Invierte en el mañana, hoy.",
  heroLead:
    "Global Beldex permite invertir con confianza en CFDs de Forex, BDX, cripto e índices. Herramientas avanzadas, soporte a medida y seguridad de primer nivel, tanto si empiezas como si ya inviertes.",
  registerNow: "Regístrate ahora",
  conditionsCharges: "Condiciones y cargos",
  platformsLead: "En GLOBAL BELDEX hay plataformas para inversores de todos los niveles.",
  goodCompany: "Estás en buena compañía",
  companyCards: [
    { title: "Principiantes", body: "Abre una cuenta, sigue el precio de Beldex en vivo y elige el plan que encaja con tu saldo." },
    { title: "Inversores con experiencia", body: "Forex, BDX, cripto e índices en un mismo escritorio, con los mismos gráficos profesionales y calculadora." },
    { title: "Soporte", body: "Habla con el escritorio por teléfono, correo o la oficina de Newcastle que aparece en este sitio." },
  ],
  compareTitle: "Comparación de precio cripto",
  minFunding: "Fondeo mínimo",
  openingAccount: "Abriendo el registro",
  openingLogin: "Abriendo el acceso",
  statZero: "Cero comisiones",
  statZeroBody: "Sin comisiones en las operaciones",
  statLev: "Hasta 400:1",
  statLevBody: "Apalancamiento máximo",
  statInst: "Instantáneo",
  statInstBody: "Ejecución < 12 ms",
  liveMarketTv: "Mercado BDXUSD en vivo · TradingView",
  trackBdx: "Seguir BDXUSD",
  featured: "Producto destacado",
  tvChartTitle: "Precio de Beldex hoy — Gráfico BDXUSD — TradingView",
  liveFromTv: "Datos en vivo de TradingView · CRYPTO:BDXUSD",
  liveOverview: "Resumen BDXUSD en vivo",
  poweredBy: "Con tecnología de TradingView · CRYPTO:BDXUSD",
  conditions: "CONDICIONES DE INVERSIÓN",
  trustTitle: "Plataformas potentes en las que puedes confiar",
  safeTitle: "Seguro",
  safeBody: "Cifrado de nivel bancario y custodia en frío de los activos digitales.",
  execTitle: "Ejecución instantánea",
  execBody: "Órdenes en menos de 12 ms con 99,9% de disponibilidad.",
  awardTitle: "Premiada",
  awardBody: "Mejor plataforma de inversión 2024 — FinTech Awards.",
  step1t: "Abre una cuenta",
  step1d: "Regístrate con tu correo — el bono de bienvenida de $3 se acredita al verificar tu cuenta.",
  step2t: "Fondea la wallet",
  step2d: "Realiza un depósito desde $300. El saldo se acredita en menos de dos segundos.",
  step3t: "Activa un plan",
  step3d: "Bloquea fondos de GNS a Falcon. La ganancia diaria se acumula hasta que termina el plazo.",
  plansBoard: "GNS empieza en 4.000 BDX. De Build Up a Falcon se usan plazos premium dentro de la cuenta.",
  footerEdu: "© GLOBAL BELDEX — Datos de mercado en vivo por TradingView.",
  createToInvest: "Crea una cuenta para invertir",
  accountOverview: "Resumen de la cuenta",
  liveDot: "En vivo · TradingView",
  viewChart: "Ver gráfico",
  symbolLine: "Símbolo: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFICIAL",
  realtimeBlurb: "Precio, gráfico, capitalización y datos de Beldex en tiempo real desde TradingView",
  overviewStats: "Resumen y datos de BDXUSD",
  chartMeta: "1D · MA 9 · Volumen",
  copyBtn: "Copiar",
  planMeta: "{amount} bloqueados · {pct}% ROI · {days} días",
  demoFoot: "Interfaz profesional · Datos en vivo de TradingView",
  dashPreview: "PANEL DE CONTROL",
  availableTape: "Disponible · cinta BDXUSD en vivo",
  signInSim: "Inicia sesión para acceder a tu cartera",
  badLogin: "El correo o la contraseña no son correctos.",
  subjectPh: "Tiempo del depósito",
  messagePh: "Cuéntanos qué necesitas",
  amountPh: "Introduce el importe… mín. $300",
  liveBdx: "BDXUSD en vivo",
  livePrice: "Precio de mercado en vivo",
  marketWord: "Mercado",
  liveWord: "En vivo",
  liveBeldex: "Precio de Beldex en vivo",
  converter: "CONVERSOR BDX",
  calculator: "Calculadora de importe",
  waitingPrice: "Esperando el precio de red en vivo",
  intraday: "Intradía (60 min)",
  codePrefix: "Código",
  chartFallback: "Gráfico de TradingView. Si el widget no carga, verifica tu conexión a internet.",
  trackOnTv: "Seguir BDXUSD en TradingView",
  liveBadge: "BDXUSD en vivo · Con TradingView",
  eduDemo: "Datos de mercado en vivo de TradingView",
  linkExpired: "Ese enlace caducó.",
  errorTitle: "Algo salió mal",
  errorFallback: "Ocurrió un error inesperado. Por favor, recarga la página.",
  legalTitle: "Términos, privacidad y riesgo",
  legalIntro: "Global Beldex es una plataforma profesional de inversión y trading. Proveemos carteras seguras, ejecución en tiempo real y herramientas gráficas de grado institucional.",
  legalBack: "Volver a la plataforma",
  legalTerms: [
    "Puedes abrir una cuenta, depositar un importe inicial desde $300, cambiar entre USD y BDX, y hacer staking de fondos en planes GNS y Falcon.",
    "Tu cuenta está protegida con encriptación avanzada. Asegúrate de activar la autenticación de dos factores (2FA) para retiros y cambios.",
    "Utiliza únicamente las direcciones de depósito generadas explícitamente tras hacer clic en “Continuar al pago”.",
  ],
  legalPrivacy: [
    "Los datos de tu perfil, historial de transacciones y tickets de soporte están cifrados y almacenados de forma segura en nuestros servidores institucionales.",
    "Los precios en vivo se obtienen mediante conexiones seguras a proveedores de liquidez y TradingView. Tu actividad comercial se mantiene estrictamente confidencial.",
  ],
  legalRisk: [
    "Las cifras de retorno de los planes (ROI) se basan en modelado histórico. Las criptomonedas y forex son mercados volátiles; los rendimientos pueden variar.",
    "El trading con margen y apalancamiento (hasta 400:1) conlleva un alto nivel de riesgo y puede no ser adecuado para todos. Puedes perder más que tu depósito inicial.",
    "Asegúrate de entender plenamente los riesgos antes de operar con activos reales. La información aquí provista no constituye asesoramiento financiero o fiscal.",
  ],
  faqs: [
    { q: "¿Es esta una plataforma real?", a: "Sí. GLOBAL BELDEX es una plataforma de inversión profesional con gráficos en vivo de TradingView. Los saldos, depósitos y planes operan en tiempo real." },
    { q: "¿Cuál es el depósito mínimo?", a: "Se requiere un depósito mínimo de $300 para activar la cuenta y acceder a los planes de inversión." },
    { q: "¿Cómo funcionan los planes?", a: "Cada plan bloquea una cantidad por un plazo fijo y acumula el rendimiento diario listado. Al terminar, el capital y las ganancias regresan a tu saldo disponible." },
    { q: "¿De dónde salen los datos de mercado?", a: "Los widgets de resumen y velas provienen directamente de TradingView para CRYPTO:BDXUSD, con liquidez de primer nivel." },
    { q: "¿Puedo invitar amigos?", a: "Sí. Cada cuenta dispone de un enlace de referidos. Las bonificaciones se acreditan automáticamente cuando tu red realiza un fondeo." },
  ],
};

export const pageFr: typeof pageEn = {
  heroTitle: "Construire un patrimoine avec une vision.",
  heroSub: "Investir dans demain, aujourd’hui.",
  heroLead:
    "Global Beldex permet d’investir en CFD sur le Forex, BDX, la crypto et les indices. Outils avancés, accompagnement et sécurité de haut niveau, que vous débutiez ou soyez un trader confirmé.",
  registerNow: "S’inscrire",
  conditionsCharges: "Conditions et frais",
  platformsLead: "Chez GLOBAL BELDEX, des plateformes pour les investisseurs de tous niveaux.",
  goodCompany: "Vous êtes en bonne compagnie",
  companyCards: [
    { title: "Débutants", body: "Ouvrez un compte, suivez le prix Beldex en direct et choisissez le plan qui correspond à votre capital." },
    { title: "Investisseurs expérimentés", body: "Forex, BDX, crypto et indices sur le même bureau, avec des graphiques professionnels et un convertisseur." },
    { title: "Assistance", body: "Joignez le bureau par téléphone, e-mail ou via l’adresse de Newcastle indiquée sur ce site." },
  ],
  compareTitle: "Comparaison de prix crypto",
  minFunding: "Dépôt minimum",
  openingAccount: "Ouverture de l’inscription",
  openingLogin: "Ouverture de la connexion",
  statZero: "Zéro frais",
  statZeroBody: "Aucune commission sur les opérations",
  statLev: "Jusqu’à 400:1",
  statLevBody: "Levier maximum",
  statInst: "Instantané",
  statInstBody: "Exécution < 12 ms",
  liveMarketTv: "Marché BDXUSD en direct · TradingView",
  trackBdx: "Suivre BDXUSD",
  featured: "Produit en avant",
  tvChartTitle: "Prix Beldex aujourd’hui — Graphique BDXUSD — TradingView",
  liveFromTv: "Données en direct de TradingView · CRYPTO:BDXUSD",
  liveOverview: "Aperçu BDXUSD en direct",
  poweredBy: "Propulsé par TradingView · CRYPTO:BDXUSD",
  conditions: "CONDICIONES D’INVESTISSEMENT",
  trustTitle: "Des plateformes solides, dignes de confiance",
  safeTitle: "Sûr",
  safeBody: "Chiffrement de niveau bancaire et stockage à froid des actifs numériques.",
  execTitle: "Exécution instantanée",
  execBody: "Ordres en moins de 12 ms avec 99,9 % de disponibilité.",
  awardTitle: "Récompensée",
  awardBody: "Meilleure plateforme d’investissement 2024 — FinTech Awards.",
  step1t: "Ouvrir un compte",
  step1d: "Inscrivez-vous par e-mail — un bonus de bienvenue de 3 $ est crédité après vérification.",
  step2t: "Alimenter le portefeuille",
  step2d: "Déposez des fonds à partir de 300 $. Le crédit réseau est confirmé en quelques secondes.",
  step3t: "Activer un plan",
  step3d: "Bloquez des fonds de GNS à Falcon. Le profit quotidien court jusqu’à la fin du terme.",
  plansBoard: "GNS commence à 4 000 BDX. De Build Up à Falcon, les mêmes conditions premium s'appliquent.",
  footerEdu: "© GLOBAL BELDEX — Données de marché en direct par TradingView.",
  createToInvest: "Créez un compte pour investir",
  accountOverview: "Aperçu du compte",
  liveDot: "En direct · TradingView",
  viewChart: "Voir le graphique",
  symbolLine: "Symbole : CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFFICIEL",
  realtimeBlurb: "Prix, graphique, capitalisation et stats Beldex en temps réel depuis TradingView",
  overviewStats: "Aperçu et stats BDXUSD",
  chartMeta: "1D · MM 9 · Volume",
  copyBtn: "Copier",
  planMeta: "{amount} bloqués · {pct} % ROI · {days} jours",
  demoFoot: "Interface professionnelle · Données en direct de TradingView",
  dashPreview: "TABLEAU DE BORD",
  availableTape: "Disponible · bande BDXUSD en direct",
  signInSim: "Connectez-vous pour accéder à votre portefeuille",
  badLogin: "E-mail ou mot de passe incorrect.",
  subjectPh: "Délai du dépôt",
  messagePh: "Dites-nous ce qu’il vous faut",
  amountPh: "Saisir le montant… min. 300 $",
  liveBdx: "BDXUSD en direct",
  livePrice: "Prix du marché en direct",
  marketWord: "Marché",
  liveWord: "En direct",
  liveBeldex: "Prix Beldex en direct",
  converter: "CONVERTISSEUR BDX",
  calculator: "Calculateur de montant",
  waitingPrice: "En attente du prix réseau en direct",
  intraday: "Intraday (60 min)",
  codePrefix: "Code",
  chartFallback: "Graphique TradingView. Si le widget ne se charge pas, vérifiez votre connexion.",
  trackOnTv: "Suivre BDXUSD sur TradingView",
  liveBadge: "BDXUSD en direct · TradingView",
  eduDemo: "Données de marché en direct par TradingView",
  linkExpired: "Ce lien a expiré.",
  errorTitle: "Un problème est survenu",
  errorFallback: "Une erreur inattendue s’est produite. Veuillez recharger la page.",
  legalTitle: "Conditions, confidentialité et risques",
  legalIntro: "Global Beldex est une plateforme professionnelle de trading. Nous fournissons des portefeuilles sécurisés, une exécution en temps réel et des outils graphiques de niveau institutionnel.",
  legalBack: "Retour à la plateforme",
  legalTerms: [
    "Vous pouvez ouvrir un compte, effectuer un dépôt à partir de 300 $, trader entre l'USD et le BDX, et staker des fonds via nos plans GNS et Falcon.",
    "Votre compte est protégé par un chiffrement avancé. Assurez-vous d'activer l'authentification à deux facteurs (2FA) pour vos retraits.",
    "Utilisez uniquement les adresses de dépôt générées explicitement après avoir cliqué sur « Continuer vers le paiement ».",
  ],
  legalPrivacy: [
    "Vos données de profil, votre historique et vos tickets de support sont chiffrés et stockés en toute sécurité sur nos serveurs institutionnels.",
    "Les prix en direct proviennent de connexions sécurisées vers des fournisseurs de liquidités et TradingView. Votre activité de trading reste strictement confidentielle.",
  ],
  legalRisk: [
    "Les chiffres de rendement (ROI) sont des objectifs basés sur une modélisation historique. Les marchés des devises et cryptomonnaies sont volatils.",
    "Le trading sur marge (levier jusqu’à 400:1) comporte un risque élevé. Vous pouvez perdre plus que votre investissement initial.",
    "Assurez-vous de bien comprendre les risques avant de trader. Aucune information sur cette plateforme ne constitue un conseil financier ou fiscal.",
  ],
  faqs: [
    { q: "S'agit-il d'une plateforme de courtage réelle ?", a: "Oui. GLOBAL BELDEX est une plateforme d'investissement professionnelle. Les soldes, dépôts et plans sont traités en temps réel." },
    { q: "Quel est le dépôt minimum ?", a: "Un dépôt minimum de 300 $ est requis pour activer votre compte et accéder aux plans d'investissement." },
    { q: "Comment fonctionnent les plans ?", a: "Chaque plan bloque vos fonds pour une durée fixe et génère des profits quotidiens. À terme, le capital et les gains s'ajoutent à votre solde disponible." },
    { q: "D’où viennent les données de marché ?", a: "Les flux et graphiques proviennent des widgets officiels de TradingView pour CRYPTO:BDXUSD avec une liquidité de premier plan." },
    { q: "Puis-je parrainer des amis ?", a: "Oui. Chaque compte possède un lien de parrainage. Les bonus sont crédités automatiquement lors des dépôts de votre réseau." },
  ],
};

export const pageIt: typeof pageEn = {
  heroTitle: "Costruire patrimonio con una visione.",
  heroSub: "Investire nel domani, oggi.",
  heroLead:
    "Global Beldex permette di investire in CFD su Forex, BDX, crypto e indici. Strumenti avanzati, supporto su misura e sicurezza di alto livello, per investitori principianti ed esperti.",
  registerNow: "Registrati ora",
  conditionsCharges: "Condizioni e costi",
  platformsLead: "In GLOBAL BELDEX ci sono piattaforme per investitori di ogni livello.",
  goodCompany: "Sei in buona compagnia",
  companyCards: [
    { title: "Principianti", body: "Apri un account, segui il prezzo Beldex live e scegli il piano adatto al tuo capitale." },
    { title: "Investitori esperti", body: "Forex, BDX, crypto e indici sulla stessa scrivania, con grafici professionali e convertitore." },
    { title: "Supporto", body: "Contatta la scrivania per telefono, email o l’ufficio di Newcastle indicato su questo sito." },
  ],
  compareTitle: "Confronto prezzi crypto",
  minFunding: "Deposito minimo",
  openingAccount: "Apertura della registrazione",
  openingLogin: "Apertura dell’accesso",
  statZero: "Zero commissioni",
  statZeroBody: "Nessuna commissione sulle operazioni",
  statLev: "Fino a 400:1",
  statLevBody: "Leva massima",
  statInst: "Istantaneo",
  statInstBody: "Esecuzione < 12 ms",
  liveMarketTv: "Mercato BDXUSD live · TradingView",
  trackBdx: "Segui BDXUSD",
  featured: "Prodotto in evidenza",
  tvChartTitle: "Prezzo Beldex oggi — Grafico BDXUSD — TradingView",
  liveFromTv: "Dati live da TradingView · CRYPTO:BDXUSD",
  liveOverview: "Panoramica BDXUSD live",
  poweredBy: "Con tecnologia TradingView · CRYPTO:BDXUSD",
  conditions: "CONDIZIONI DI INVESTIMENTO",
  trustTitle: "Piattaforme solide di cui ti puoi fidare",
  safeTitle: "Sicuro",
  safeBody: "Cifratura di livello bancario e custodia a freddo degli asset digitali.",
  execTitle: "Esecuzione istantanea",
  execBody: "Ordini sotto i 12 ms con uptime del 99,9%.",
  awardTitle: "Premiata",
  awardBody: "Miglior piattaforma di investimento 2024 — FinTech Awards.",
  step1t: "Apri un account",
  step1d: "Registrati con l’email — un bonus di benvenuto di $3 viene accreditato previa verifica.",
  step2t: "Finanzia il wallet",
  step2d: "Deposita fondi a partire da $300. L'accredito di rete si completa in pochi secondi.",
  step3t: "Attiva un piano",
  step3d: "Blocca fondi da GNS a Falcon. Il profitto giornaliero cresce fino alla fine del periodo.",
  plansBoard: "GNS parte da 4.000 BDX. Da Build Up a Falcon si applicano le stesse condizioni premium.",
  footerEdu: "© GLOBAL BELDEX — Dati di mercato live forniti da TradingView.",
  createToInvest: "Crea un account per investire",
  accountOverview: "Panoramica account",
  liveDot: "Live · TradingView",
  viewChart: "Vedi grafico",
  symbolLine: "Simbolo: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW UFFICIALE",
  realtimeBlurb: "Prezzo, grafico, capitalizzazione e dati Beldex in tempo reale da TradingView",
  overviewStats: "Panoramica e dati BDXUSD",
  chartMeta: "1D · MA 9 · Volume",
  copyBtn: "Copia",
  planMeta: "{amount} bloccati · {pct}% ROI · {days} giorni",
  demoFoot: "Interfaccia professionale · Dati live da TradingView",
  dashPreview: "DASHBOARD",
  availableTape: "Disponibile · nastro BDXUSD live",
  signInSim: "Accedi per visualizzare il tuo portafoglio",
  badLogin: "Email o password errate.",
  subjectPh: "Tempi del deposito",
  messagePh: "Dicci di cosa hai bisogno",
  amountPh: "Inserisci l’importo… min. $300",
  liveBdx: "BDXUSD live",
  livePrice: "Prezzo di mercato live",
  marketWord: "Mercato",
  liveWord: "Live",
  liveBeldex: "Prezzo Beldex live",
  converter: "CONVERTITORE BDX",
  calculator: "Calcolatore di importo",
  waitingPrice: "In attesa del prezzo di rete live",
  intraday: "Intraday (60 min)",
  codePrefix: "Codice",
  chartFallback: "Grafico TradingView. Se il widget non si carica, controlla la connessione internet.",
  trackOnTv: "Segui BDXUSD su TradingView",
  liveBadge: "BDXUSD live · TradingView",
  eduDemo: "Dati di mercato live da TradingView",
  linkExpired: "Quel link è scaduto.",
  errorTitle: "Qualcosa è andato storto",
  errorFallback: "Si è verificato un errore imprevisto. Ti preghiamo di ricaricare la pagina.",
  legalTitle: "Termini, privacy e rischio",
  legalIntro: "Global Beldex è una piattaforma di trading e investimento professionale. Offriamo wallet ultra-sicuri, esecuzione in tempo reale e grafici di livello istituzionale.",
  legalBack: "Torna alla piattaforma",
  legalTerms: [
    "Puoi aprire un account, depositare fondi a partire da $300, effettuare swap tra USD e BDX e bloccare asset nei piani GNS e Falcon.",
    "Il tuo account è protetto da cifratura avanzata. Assicurati di attivare l'autenticazione a due fattori (2FA) per i prelievi e le modifiche.",
    "Usa unicamente gli indirizzi di deposito generati esplicitamente dopo aver cliccato su “Continua al pagamento”.",
  ],
  legalPrivacy: [
    "I dati del tuo profilo, la cronologia transazioni e i ticket di supporto sono crittografati e archiviati in modo sicuro sui nostri server istituzionali.",
    "I prezzi live provengono da connessioni sicure con i principali fornitori di liquidità e TradingView. La tua attività di trading resta strettamente confidenziale.",
  ],
  legalRisk: [
    "Le cifre relative ai rendimenti (ROI) si basano su modelli storici. I mercati crypto e forex sono volatili; i rendimenti effettivi possono variare.",
    "Il trading a margine e con leva (fino a 400:1) comporta un alto livello di rischio. È possibile perdere più del deposito iniziale.",
    "Assicurati di comprendere appieno i rischi prima di operare. Nessuna informazione fornita costituisce consulenza finanziaria o fiscale.",
  ],
  faqs: [
    { q: "È un broker vero?", a: "Sì. GLOBAL BELDEX è una piattaforma di investimento professionale con grafici e flussi in tempo reale. I saldi e i depositi sono elaborati live." },
    { q: "Qual è il deposito minimo?", a: "È richiesto un deposito minimo di $300 per attivare l'account e accedere ai piani di investimento." },
    { q: "Come funzionano i piani?", a: "Ogni piano blocca un importo per una durata fissa e genera profitti giornalieri. Alla scadenza, capitale e profitti tornano al saldo disponibile." },
    { q: "Da dove arrivano i dati di mercato?", a: "I flussi e le candele sono widget ufficiali forniti da TradingView per CRYPTO:BDXUSD con liquidità di primo livello." },
    { q: "Posso invitare amici?", a: "Sì. Ogni account include un link di affiliazione. I bonus vengono accreditati automaticamente quando la tua rete effettua depositi." },
  ],
};

export const pagePt: typeof pageEn = {
  heroTitle: "Construir patrimônio com visão.",
  heroSub: "Investir no amanhã, hoje.",
  heroLead:
    "A Global Beldex permite investir com confiança em CFDs de Forex, BDX, cripto e índices. Ferramentas avançadas, suporte sob medida e segurança de alto nível, para investidores de todos os perfis.",
  registerNow: "Cadastre-se agora",
  conditionsCharges: "Condições e taxas",
  platformsLead: "Na GLOBAL BELDEX há plataformas para investidores de todos os níveis.",
  goodCompany: "Você está em boa companhia",
  companyCards: [
    { title: "Iniciantes", body: "Abra uma conta, acompanhe o preço ao vivo da Beldex e escolha o plano adequado ao seu capital." },
    { title: "Investidores experientes", body: "Forex, BDX, cripto e índices na mesma mesa, com gráficos profissionais e calculadora integrada." },
    { title: "Suporte", body: "Fale com nossa mesa por telefone, e-mail ou através do escritório de Newcastle listado neste site." },
  ],
  compareTitle: "Comparação de preço cripto",
  minFunding: "Aporte mínimo",
  openingAccount: "Abrindo o cadastro",
  openingLogin: "Abrindo o acesso",
  statZero: "Zero taxas",
  statZeroBody: "Sem comissões nas operações",
  statLev: "Até 400:1",
  statLevBody: "Alavancagem máxima",
  statInst: "Instantâneo",
  statInstBody: "Execução < 12 ms",
  liveMarketTv: "Mercado BDXUSD ao vivo · TradingView",
  trackBdx: "Acompanhar BDXUSD",
  featured: "Produto em destaque",
  tvChartTitle: "Preço da Beldex hoje — Gráfico BDXUSD — TradingView",
  liveFromTv: "Dados ao vivo da TradingView · CRYPTO:BDXUSD",
  liveOverview: "Visão BDXUSD ao vivo",
  poweredBy: "Com tecnologia TradingView · CRYPTO:BDXUSD",
  conditions: "CONDIÇÕES DE INVESTIMENTO",
  trustTitle: "Plataformas fortes em que você pode confiar",
  safeTitle: "Seguro",
  safeBody: "Criptografia de nível bancário e custódia fria para todos os ativos digitais.",
  execTitle: "Execução instantânea",
  execBody: "Ordens executadas em menos de 12 ms com 99,9% de uptime.",
  awardTitle: "Premiada",
  awardBody: "Melhor plataforma de investimento 2024 — FinTech Awards.",
  step1t: "Abra uma conta",
  step1d: "Cadastre-se com o seu e-mail — um bônus de boas-vindas de $3 é creditado após a verificação.",
  step2t: "Abasteça a carteira",
  step2d: "Deposite fundos a partir de $300. Os créditos da rede são processados em segundos.",
  step3t: "Ative um plano",
  step3d: "Faça staking de fundos GNS até Falcon. O lucro diário é acumulado até o fim do prazo.",
  plansBoard: "GNS começa em 4.000 BDX. De Build Up a Falcon aplicam-se as mesmas condições premium.",
  footerEdu: "© GLOBAL BELDEX — Dados de mercado ao vivo fornecidos pela TradingView.",
  createToInvest: "Crie uma conta para investir",
  accountOverview: "Visão da conta",
  liveDot: "Ao vivo · TradingView",
  viewChart: "Ver gráfico",
  symbolLine: "Símbolo: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFICIAL",
  realtimeBlurb: "Preço, gráfico, valor de mercado e dados da Beldex em tempo real da TradingView",
  overviewStats: "Visão e dados de BDXUSD",
  chartMeta: "1D · MM 9 · Volume",
  copyBtn: "Copiar",
  planMeta: "{amount} bloqueados · {pct}% ROI · {days} dias",
  demoFoot: "Interface profissional · Dados ao vivo da TradingView",
  dashPreview: "PAINEL DE CONTROLE",
  availableTape: "Disponível · fita BDXUSD ao vivo",
  signInSim: "Entre para acessar seu portfólio",
  badLogin: "E-mail ou senha incorretos.",
  subjectPh: "Prazo do depósito",
  messagePh: "Diga o que você precisa",
  amountPh: "Digite o valor… mín. $300",
  liveBdx: "BDXUSD ao vivo",
  livePrice: "Preço de mercado ao vivo",
  marketWord: "Mercado",
  liveWord: "Ao vivo",
  liveBeldex: "Preço da Beldex ao vivo",
  converter: "CONVERSOR BDX",
  calculator: "Calculadora de valor",
  waitingPrice: "Aguardando preço da rede ao vivo",
  intraday: "Intraday (60 min)",
  codePrefix: "Código",
  chartFallback: "Gráfico da TradingView. Se o widget não carregar, verifique sua conexão de internet.",
  trackOnTv: "Acompanhar BDXUSD na TradingView",
  liveBadge: "BDXUSD ao vivo · TradingView",
  eduDemo: "Dados de mercado ao vivo da TradingView",
  linkExpired: "Esse link expirou.",
  errorTitle: "Algo deu errado",
  errorFallback: "Ocorreu um erro inesperado. Por favor, recarregue a página.",
  legalTitle: "Termos, privacidade e riscos",
  legalIntro: "A Global Beldex é uma plataforma de trading e investimento profissional. Fornecemos carteiras seguras, execução em tempo real e ferramentas gráficas de nível institucional.",
  legalBack: "Voltar à plataforma",
  legalTerms: [
    "Você pode abrir uma conta, depositar fundos a partir de $300, realizar swaps entre USD e BDX, e fazer staking de ativos nos planos GNS e Falcon.",
    "Sua conta é protegida com criptografia avançada. Certifique-se de ativar a autenticação de dois fatores (2FA) para retiradas e alterações.",
    "Utilize apenas os endereços de depósito gerados explicitamente após clicar em “Continuar para o pagamento”.",
  ],
  legalPrivacy: [
    "Seus dados de perfil, histórico de transações e tickets de suporte são criptografados e armazenados com segurança em nossos servidores institucionais.",
    "Os preços ao vivo vêm de conexões seguras com grandes provedores de liquidez e TradingView. Sua atividade de negociação é estritamente confidencial.",
  ],
  legalRisk: [
    "Os números de retorno (ROI) são metas baseadas em modelagem histórica. Criptomoedas e forex são mercados voláteis; os retornos podem variar.",
    "A negociação de margem e alavancagem (até 400:1) envolve alto risco e pode não ser adequada para todos. Você pode perder mais do que seu depósito inicial.",
    "Certifique-se de compreender totalmente os riscos antes de negociar. Nada nesta plataforma constitui aconselhamento financeiro ou fiscal.",
  ],
  faqs: [
    { q: "Isto é uma corretora de verdade?", a: "Sim. A GLOBAL BELDEX é uma plataforma de investimento profissional. Saldos, depósitos e planos são processados em tempo real." },
    { q: "Qual é o depósito mínimo?", a: "É exigido um depósito mínimo de $300 para ativar a conta e acessar os planos de investimento." },
    { q: "Como os planos funcionam?", a: "Cada plano bloqueia um valor por um prazo fixo e gera lucro diário. No fim do prazo, o principal e o lucro retornam ao saldo disponível." },
    { q: "De onde vêm os dados de mercado?", a: "Fita, visão geral e gráficos são widgets oficiais da TradingView para CRYPTO:BDXUSD com precificação de liquidez de nível 1." },
    { q: "Posso indicar amigos?", a: "Sim. Cada conta tem um link de indicação. Os bônus são creditados automaticamente quando sua rede realiza depósitos." },
  ],
};

export const pageNl: typeof pageEn = {
  heroTitle: "Vermogen opbouwen met visie.",
  heroSub: "Investeren in morgen, vandaag.",
  heroLead:
    "Global Beldex laat je professioneel beleggen in CFD’s op forex, BDX, crypto en indices. Geavanceerde tools, persoonlijke support en sterke beveiliging, voor zowel beginners als ervaren beleggers.",
  registerNow: "Nu registreren",
  conditionsCharges: "Voorwaarden en kosten",
  platformsLead: "Bij GLOBAL BELDEX bieden we platforms voor beleggers van elk niveau.",
  goodCompany: "Je bent in goed gezelschap",
  companyCards: [
    { title: "Beginners", body: "Open een account, volg de live Beldex-prijs en kies het plan dat bij je kapitaal past." },
    { title: "Ervaren beleggers", body: "Forex, BDX, crypto en indices op één platform, met professionele grafieken en calculators." },
    { title: "Support", body: "Bereik onze trading desk via telefoon, e-mail of ons kantoor in Newcastle vermeld op deze site." },
  ],
  compareTitle: "Cryptoprijsvergelijking",
  minFunding: "Minimale inleg",
  openingAccount: "Registratie openen",
  openingLogin: "Inloggen openen",
  statZero: "Geen kosten",
  statZeroBody: "Geen commissie op transacties",
  statLev: "Tot 400:1",
  statLevBody: "Maximale hefboom",
  statInst: "Direct",
  statInstBody: "Uitvoering < 12 ms",
  liveMarketTv: "Live BDXUSD-markt · TradingView",
  trackBdx: "BDXUSD volgen",
  featured: "Uitgelicht product",
  tvChartTitle: "Beldex-prijs vandaag — BDXUSD-grafiek — TradingView",
  liveFromTv: "Live data van TradingView · CRYPTO:BDXUSD",
  liveOverview: "Live BDXUSD-overzicht",
  poweredBy: "Mogelijk gemaakt door TradingView · CRYPTO:BDXUSD",
  conditions: "BELEGGINGSVOORWAARDEN",
  trustTitle: "Sterke platforms waarop je kunt vertrouwen",
  safeTitle: "Veilig",
  safeBody: "Versleuteling op bankniveau en cold storage voor alle digitale activa.",
  execTitle: "Directe uitvoering",
  execBody: "Orders uitgevoerd in minder dan 12 ms met 99,9% uptime.",
  awardTitle: "Bekroond",
  awardBody: "Beste beleggingsplatform 2024 — FinTech Awards.",
  step1t: "Open een account",
  step1d: "Registreer met je e-mail — een welkomstbonus van $3 wordt na verificatie bijgeschreven.",
  step2t: "Vul de wallet",
  step2d: "Stort fondsen vanaf $300. Netwerktransacties worden binnen enkele seconden verwerkt.",
  step3t: "Activeer een plan",
  step3d: "Zet fondsen vast in plannen van GNS tot Falcon. Dagelijkse winst wordt bijgeschreven tot het einde van de termijn.",
  plansBoard: "GNS begint bij 4.000 BDX. Van Build Up tot Falcon gelden dezelfde premium voorwaarden in het account.",
  footerEdu: "© GLOBAL BELDEX — Live marktgegevens geleverd door TradingView.",
  createToInvest: "Maak een account om te beleggen",
  accountOverview: "Accountoverzicht",
  liveDot: "Live · TradingView",
  viewChart: "Grafiek bekijken",
  symbolLine: "Symbool: CRYPTO:BDXUSD",
  tvOfficial: "TRADINGVIEW OFFICIEEL",
  realtimeBlurb: "Realtime Beldex-prijs, grafiek, marktkapitalisatie en data van TradingView",
  overviewStats: "BDXUSD-overzicht en cijfers",
  chartMeta: "1D · MA 9 · Volume",
  copyBtn: "Kopiëren",
  planMeta: "{amount} vastgezet · {pct}% ROI · {days} dagen",
  demoFoot: "Professionele interface · Live data van TradingView",
  dashPreview: "DASHBOARD",
  availableTape: "Beschikbaar · live BDXUSD-ticker",
  signInSim: "Log in om toegang te krijgen tot je portfolio",
  badLogin: "E-mail of wachtwoord is onjuist.",
  subjectPh: "Timing van de storting",
  messagePh: "Vertel wat je nodig hebt",
  amountPh: "Vul het bedrag in… min. $300",
  liveBdx: "Live BDXUSD",
  livePrice: "Live marktprijs",
  marketWord: "Markt",
  liveWord: "Live",
  liveBeldex: "Live Beldex-prijs",
  converter: "BDX-OMREKENER",
  calculator: "Bedragcalculator",
  waitingPrice: "Wachten op de live netwerkprijs",
  intraday: "Intraday (60 min)",
  codePrefix: "Code",
  chartFallback: "Grafiek van TradingView. Als de widget niet laadt, controleer dan je internetverbinding.",
  trackOnTv: "BDXUSD volgen op TradingView",
  liveBadge: "Live BDXUSD · TradingView",
  eduDemo: "Live marktgegevens van TradingView",
  linkExpired: "Die link is verlopen.",
  errorTitle: "Er ging iets mis",
  errorFallback: "Er is een onverwachte fout opgetreden. Laad de pagina opnieuw.",
  legalTitle: "Voorwaarden, privacy en risico",
  legalIntro: "Global Beldex is een professioneel handels- en investeringsplatform. Wij bieden zwaar beveiligde wallets, realtime uitvoering en institutionele grafische tools.",
  legalBack: "Terug naar het platform",
  legalTerms: [
    "Je kunt een account openen, fondsen storten vanaf $300, swappen tussen USD en BDX, en vermogen vastzetten in onze GNS- en Falcon-plannen.",
    "Je account is beveiligd met geavanceerde versleuteling. Zorg ervoor dat je tweestapsverificatie (2FA) inschakelt voor opnames en wijzigingen.",
    "Gebruik uitsluitend de stortingsadressen die expliciet voor jou worden gegenereerd na het klikken op “Doorgaan naar betaling”.",
  ],
  legalPrivacy: [
    "Je profielgegevens, transactiegeschiedenis en supporttickets worden versleuteld en veilig opgeslagen op onze institutionele servers.",
    "Live prijzen komen via beveiligde verbindingen van grote liquiditeitsverschaffers en TradingView. Je handelsactiviteit blijft strikt vertrouwelijk.",
  ],
  legalRisk: [
    "De rendementen (ROI) van plannen zijn doelen gebaseerd op historische modellering. Cryptomarkten en forex zijn volatiel; rendementen kunnen fluctueren.",
    "Handelen met marge en hefboomwerking (tot 400:1) brengt een hoog risico met zich mee en is mogelijk niet voor iedereen geschikt. Je kunt meer verliezen dan je initiële inleg.",
    "Zorg ervoor dat je de risico's volledig begrijpt voordat je gaat handelen. De informatie op dit platform is geen financieel of fiscaal advies.",
  ],
  faqs: [
    { q: "Is dit een echte broker?", a: "Ja. GLOBAL BELDEX is een professioneel investeringsplatform met realtime grafieken. Saldi, stortingen en plannen worden live verwerkt." },
    { q: "Wat is de minimale storting?", a: "Er is een minimale storting van $300 vereist om je account te activeren en toegang te krijgen tot de investeringsplannen." },
    { q: "Hoe werken de plannen?", a: "Elk plan zet je fondsen vast voor een bepaalde duur en genereert dagelijkse winst. Aan het einde worden je inleg en winst teruggestort naar je beschikbare saldo." },
    { q: "Waar komen de marktgegevens vandaan?", a: "Ticker, overzicht en grafieken zijn officiële widgets van TradingView voor CRYPTO:BDXUSD met tier-1 liquiditeitsprijzen." },
    { q: "Kan ik vrienden verwijzen?", a: "Ja. Elk account krijgt een verwijzingslink. Bonussen worden automatisch bijgeschreven wanneer je netwerk geld stort." },
  ],
};
